TownyAdvanced/Towny

- src/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java
- src/com/palmergames/bukkit/towny/war/eventwar/War.java
Fixed point system so the attacker receives the correct amount of points. Also changed how some messages are displayed (townblock falling, mayor/king killed).
> Fix point system and displays.

- src/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java
- src/com/palmergames/bukkit/towny/war/eventwar/War.java
-The only time a king/mayor death cause the nation/town to fall and the
only time points are awarded for kills is when both the attacker and
defender are players and both are in warring towns.
-Members of the defending town get a notification for each call to
damage while members of that nation not in the town get notifications
every 10 hp.
> Changes to Player Deaths

- src/com/palmergames/bukkit/towny/huds/HUDManager.java
- src/com/palmergames/bukkit/towny/huds/PermHUD.java
- src/com/palmergames/bukkit/towny/huds/WarHUD.java
- src/com/palmergames/bukkit/towny/war/eventwar/War.java
- src/com/palmergames/bukkit/towny/war/eventwar/WarTimerTask.java
Fixed some bug with HUDs. Players can regen townblock HP in war if they
are an ally or part of the nation.
> HUD Fixes + War HP Regen

- src/com/palmergames/bukkit/towny/command/ResidentCommand.java
Make the permission node for /res jail "towny.command.resident.jail" instead of "towny.command.resident.tax"
> Fix permission node for /res jail

- src/com/palmergames/bukkit/towny/TownyEconomyHandler.java
- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Checks the player's new name for an economy account. If found, the account isn't destroyed and recreated.
Vault has no function to remove accounts, so name changes cause Towny to create a second account with the same UUID. In CraftConomy, this throws a database exception, which is not caught by Towny and breaks name changes.
> Fix for name changing with Vault economies that already support UUIDs

- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- src/com/palmergames/bukkit/towny/permissions/TownyPermissionSource.java
- src/plugin.yml
Added permission: towny.command.townyadmin.town.spawn in plugin.yml it is added to townyadmin.*
And added to the PermissionNodes.java its checked for in the command instead of the townyadmin perm
> - /t spawn permission override

- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
Yeah Quickfix, literally all we needed was 1 catch clause,
This gave me the oppertunity to check if the SQL_SCHEMA i did actually does work between multiple (not only 2) versions, which it does thankfully
> Quick fix for the NPE caused by Nations loading

- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/db/FlatFile_Task.java
- src/com/palmergames/bukkit/towny/object/TownyUniverse.java
- src/com/palmergames/bukkit/towny/tasks/ProtectionRegenTask.java
- src/com/palmergames/bukkit/towny/tasks/TownClaim.java
- src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java
- The /t unclaim outpost command does following:
It checks the arguments when in the AreaSelectionUtil.
If the value is outpost in the arguments it checks against the town
if the townblock really is an outpost.
If it is, it sets the outpost value to true and returns the townblock the
player is on (standard behavior for unclaiming a townblock)
since the code for deleting a townblock does remove the outpost itself from
the town.
> Added /t unclaim outpost command

- README.md
Converts the Readme from a Text file to Markdown. This allows for a slightly cleaner feel than a raw text file when viewing from GitHub (subjective), and adds the ability to use HTML tags for various elements if desired. (Such as the Towny logo)
Just thought I'd give back to the project a bit. ¯\\\_(ツ)_/¯
> Convert Readme to Markdown

- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/english.yml
- src/es-mx.yml
- src/french.yml
- src/german.yml
- src/italian.yml
- src/norwegian.yml
- src/russian.yml
- src/spanish.yml
Using this method players have successfully combat teleported away in an instant on EMC. I don't think anyone could create a counter argument to keep the functionality there that would be dubbed as "useful".
> Prevent players from jailing themself.

- src/com/palmergames/bukkit/config/ConfigNodes.java
Removes records that prevent entities in the WaterMob class from spawning in towns.
(Dolphins, Fish, Squid, Etc.)
Adds 'Guardian' class (Guardians, Elder Guardians) This might be unnecessary, but ensures the effect.
Should partially address #2995
> Delete refs of WaterMob removal; add Guardian

- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Previously tried to unjail the command sender instead of the target resident. Also, should be noted that the command is `/ta resident <resident> unjail` and not `/ta unjail` as the commit adding this command would suggest
> Fixed /ta resident <> unjail

- .classpath
- build.xml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownyEconomyHandler.java
- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/ResidentCommand.java
Why: iConomy5 should now be fully Vault-compliant (according to LlmDl) which should keep it compatible without necessarily building against - and there's currently no publicly facing maven repository, an issue that hinders Towny adopting it's own.
> Remove iConomy5 from dependencies

- .gitignore
You would need to delete the eclipse IDE files via GitHub and make a copy on your PC, so that git when it deletes them, doesn't destroy your setup - that's why i didn't delete them in this commit and just made github not track them anymore
> Updated .gitignore to include more IDEs and stopped tracking eclipse IDE

- src/com/palmergames/bukkit/towny/huds/HUDManager.java
- src/com/palmergames/bukkit/towny/huds/PermHUD.java
Might Close: https://github.com/TownyAdvanced/Towny/issues/3202
I can't test this, since my PC is too beefy to actually know what tick lag is.
Since we were getting a nullpointer on previously line 61: board.getTeam(), I presumed that either board or team is being null.
> Fix permissions HUD from throwing an exception.

- resources/plugin.yml
So, uh... Yeah.
Fixes an issue with runtime: Plugin won't load due to the api-version being called wrong.
This is due to a properties variable change in the pom file from commit https://github.com/TownyAdvanced/Towny/pull/3269/commits/a5274227a90d40d2750489e08c46af8f7df7a8a2
(Unnecessarily large diff due to growing pains with EditorConfig. File is just changing to use CRLF line endings. Only change is line 4.)
> Critical-Patch: Fix API-Version variable (Runtime Error)

- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/towny/command/commandobjects/CancelCommand.java
- src/com/palmergames/bukkit/towny/command/commandobjects/ConfirmCommand.java
- src/com/palmergames/bukkit/towny/confirmations/ConfirmationHandler.java
- src/com/palmergames/bukkit/towny/confirmations/ConfirmationType.java
- Adds console confirmations.
- /confirm and /cancel can now handle being run from the console.
- currently only being used by the /ta purge command.
> ConsoleConfirmations

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/command/TownyCommand.java
- src/com/palmergames/bukkit/towny/object/Town.java
- New Config Option: economy.new_expand.price_claim_townblock_increase
- default: 1.0
- How much every additionally claimed townblock increases in cost. Set
to 1 to deactivate this. 1.3 means +30% to every bonus claim block cost.
- Added townblocks and outpost claiming costs to the /towny prices
screen. Shows cost increase when it is used.
> Exponential Town Claiming Costs

- pom.xml
- Apparently, the GitHub Package Registry documentation is somewhat misleading. Maven searches through the wrong directory if the repository declaration is set up as it was previously. 
- And @creatorfromhell didn't have the older packages in the registry, either...
> Fix Maven Building (1.13)

- src/com/palmergames/bukkit/towny/TownyUniverse.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
Re-Opened PR of  #3486 due to bad merging on my part.
Hashtables are much slower than a normal hashmap. Although they provide thread-safety, they do so at the cost of locking the entire map for reads and writes.
They are also outdated compared to concurrenthashmaps (hashtables were introduced with the original java util, while concurrenthashmaps were introduced in jdk 1.5)
ConcurrentHashMaps are much more efficient because instead of locking the entire map, they lock individual bins. They also do not lock on reads, which makes read-access much faster than a hashtable. Furthermore, they offer thread-safe iteration since they copy the internal data to the iterator.
If that doesn't convince you to use ConcurrentHashMaps, then I don't know what will.
This PR simply changes the hashtables …
> Replace hashtables with concurrenthashmaps

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/ChunkNotification.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- New Feature: nation zones show notifications when you enter into them.
- New Config Option: global_nation_settings.nationzone.show_notifications
- When set to true, players will receive a notification when they enter into a nationzone.
- Set to false by default because, like the nationzone feature, it will generate more load on servers.
> nationzones added to the chunknotifier

- resources/chinese.yml
- resources/english.yml
- resources/es-mx.yml
- resources/french.yml
- resources/german.yml
- resources/italian.yml
- resources/korean.yml
- resources/norwegian.yml
- resources/russian.yml
- resources/spanish.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/Towny.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/TownyTimerHandler.java
- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/PlotCommand.java
- src/com/palmergames/bukkit/towny/command/ResidentCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/tasks/CooldownTimerTask.java
- src/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java
- New Feature: Cooldown timers for toggling PVP and using res/town spawn commands.
- Closes tickets #2224 #2315
- New Config Option: global_town_settings.spawn_cooldown_time
- default '30'
- Number of seconds that must pass before a player can use /n spawn, /t spawn or /res spawn.
- New Config Option: global_town_settings.pvp_cooldown_time
- default '30'
- Number of seconds that must pass before pvp can be toggled by a town using /t toggle pvp.
- Also applies to residents of the town using /res toggle pvp, as well as plots having their PVP toggled using /plot toggle pvp.
- /ta town {town} toggle pvp bypasses cooldowntimer.
- Language files bumped to 0.62.
> CooldownTimerTask

- src/com/palmergames/bukkit/towny/command/TownCommand.java
the /t deposit insufficient permission message was incorrectly defined and would fail to reply as such.
> Corrected spelling mistake for insufficient permission response

- .github/workflows/deploy-on-release.yml
- pom.xml
- pom_deb.xml
See individual commits for changes and summary. Addresses issue #3519. Individual developers are now responsible for building their own Javadocs and making necessary tweaks to the Pom file to automate them.
`pom_deb.xml` is now used for GitHub Actions' workflow. It can also be used on Debian-based distributions such as Ubuntu, Mint, and ZorinOS. To do so, Maven will need to be ran with the `--file` argument. IDE helper scripts may not work, or may need editing.
> Remove Javadocs from Maven's install phase, make Debian/GitHub Actions specific pomfile.

- resources/ChangeLog.txt
- resources/chinese.yml
- resources/english.yml
- resources/es-mx.yml
- resources/french.yml
- resources/german.yml
- resources/italian.yml
- resources/korean.yml
- resources/norwegian.yml
- resources/russian.yml
- resources/spanish.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/war/flagwar/TownyWarConfig.java
- src/com/palmergames/bukkit/towny/war/flagwar/listeners/TownyWarCustomListener.java
Closes ticket #3514
Adds language file entry to broadcast this to the attacking and defending towns.
See ChangeLog for full commit description.
(Also fixes spelling of WAR_ENEMY_FLAG)
> Flagwar Feature: Option to disable the capture of a defender's TownBlocks

- resources/ChangeLog.txt
>[1:46 AM] Silverwolfg11: Uh the changelog says the required config is to add townBlockBonusBuyLimit to each town level, however, the code actually searches for townBlockBuyBonusLimit, so one of those is wrong.
Confirmed the issue, this should fix it.
> Fix Documentation Error in Changelog

- src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
ISSUES FIXED
1.
* Currently, if "war_disables" config is set to false, the nationzone is always considered inactive.
* This is due to an if-statement logic issue in PlayerCacheUtil.getTownBlockStatus().
* Fixed.
2
* Currently, if "capital_bonus_size" is set to more than 0, this
actually reduces, rather than increases, the effective zone around the capital.
* This is due to the wrong variable being modified in PlayerCacheUtil.getTownBlockStatus().
* Fixed.
TESTING
* Set war_disables config to false, nation zone active during peace PASS
* Set war_disables config to true, nation zone active during peace PASS
* Set capital bonus to > 0, it increased the capital nation zone size by the correct amount PASS
> Fixes to Nationzone

- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- src/com/palmergames/bukkit/towny/object/Coord.java
- src/com/palmergames/bukkit/towny/object/WorldCoord.java
Minor Optimization PR
This adds a static method to WorldCoord that checks if a cell has changed without creating a new Coord entirely. Also changes internally how Coord is parsed simplifying the code to a `Math.floorDiv()`. 
The reason of this PR is to reduce two new object allocations every time a player moves a block.
> Reduce Object Allocation on Player Move

- src/com/palmergames/bukkit/towny/TownyFormatter.java
Something I forgot when adding the extra fields metadata. I just noticed that two lines of code were missing, meaning any fields that left a line <40 characters long wouldn't be shown. Don't know how I missed it, but here's the fix. Literally just 2 lines of code to add any leftovers that haven't been added to a list yet.
> Add missing code line to add remaining extra fields

- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/event/PreNewTownEvent.java
Adds a "pre" town creation event to facilitates the canceling the creation of towns if needed.
____
> Add new town creation pre event.

- resources/chinese.yml
- resources/english.yml
- resources/es-mx.yml
- resources/french.yml
- resources/german.yml
- resources/italian.yml
- resources/korean.yml
- resources/norwegian.yml
- resources/pt-br.yml
- resources/russian.yml
- resources/spanish.yml
- src/com/palmergames/bukkit/towny/command/PlotCommand.java
This fixes the NPE caused when a player executed `/plot group add` instead of `/plot group add {group}`. This PR also comes with the error message already placed in the lang files.
____
> Fix npe thrown from /plot group add when group name is not specified.

- .github/workflows/deploy-on-release.yml
- pom.xml
- pom_deb.xml
This PR is purely playing catch-up, since contributors do not always remember to update *both* of the Maven pom files.
- Pom_Deb should now use the same versions as the main Pom.
- Main Pom now defines to build JavaDocs on Install phase
- Deploy on Release now recognizes different 'servers' for the GitHub Package Registry
____
**NOT APPLICABLE**
____
**NOT APPLICABLE**
____
**NOT APPLICABLE**
> Update Pom_Deb to match Pom, necessary changes to deploy-on-release

- src/com/palmergames/bukkit/towny/command/PlotCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/confirmations/ConfirmationHandler.java
- src/com/palmergames/bukkit/towny/object/TownyPermission.java
- src/com/palmergames/bukkit/towny/object/TownyPermissionChange.java
The current way permissions were stored in the TownyPermissions class was through several individual booleans. While it worked, it was no doubt tedious to add permission levels or permission actions. This PR aims to alleviate that. 
Towny permissions are now stored in memory as a 2D boolean array. The first dimension represents the Permission Level (resident, ally, etc) which is referenced through the PermLevel enum. The second level is the Action type (switch, item use, etc) which is referenced through the ActionType enum. Both enums have hard-coded index values to allow fetching from the array. 
This PR also cleans up the `setTownBlockPermissions` and `setTownPermissions` method. Furthermore, the PR also adds permission changing caching. The `setTownBlockPermissions` method now returns …
> Rewrite TownyPermission data structure to a 2d boolean array

- src/com/palmergames/bukkit/towny/db/TownyDataSource.java
The aprostrof was missing. Present in all other error messages in this file.
Fixing typo
____
____
____
> Added missing aprostrof in Error string (typo)

- .github/workflows/deploy-on-release.yml
- pom.xml
- pom_deb.xml
A different CI can handle javadocs if it must - I do not believe GH Packages is capable of handling them in its current form. As for the authentication - this pretty much writes the maven config *without* creating the maven directory first. Recommend a "Testing" point release before 0.96.0.0 would go live.
Attempts to fix long-standing issues with GitHub Actions (Can't deploy javadocs), as well as newer ones (Can't auth TNE [regression]).
____
Restores the previous workflow file, but does not attempt to create the .m2 directory ("Already Exists" was a previous error, after some backend update...)
- POM files have their Javadoc functionality stripped out. You should still be capable of running `mvn javadoc:javadoc` to generate them yourself (currently errors out due to incomplete Javadoc …
> Restore TNE authentication / Remove Automated Javadoc Phase ENTIRELY

- src/com/palmergames/bukkit/towny/command/ResidentCommand.java
After browsing reddit, noticed one guy had an (probably unrelated) issue.
Did a quick search and found that this instance of "Modes set: " was hard-coded. Just rectifying that.
____
N/A - Translatable string already exists in language files
____
None - caught this while researching a [reddit post](https://www.reddit.com/r/townyplugin/comments/d1c6oc/how_can_i_change_the_color_of_modes_set_channel/).
____
* No tests have been preformed, this was done on downtime at work. Should work, simple change, but can test later on request.
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the …
> Langs: Use Pre-Existing Translatable String 'msg_modes_set' in ResidentCommand

- pom.xml
- pom_deb.xml
JDK 11 and 13 will currently fail to properly build Javadoc when the source level isn't declared. This PR rectifies the issue.
NOTE: Does not re-enable automatic building of Javadocs through GitHub Actions. AFAIK, that will still result in an error during the build process. Will get in touch with GitHub support.
____
Nothing new, just ensures that running `$ mvn javadoc:javadoc` doesn't fail due to:
```
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
```
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, …
> Ensure that recent JDKs do not error when `mvn javadoc:javadoc` is run

- src/com/palmergames/bukkit/towny/ChunkNotification.java
- src/com/palmergames/bukkit/towny/Towny.java
- src/com/palmergames/bukkit/towny/TownyFormatter.java
- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/TownyCommand.java
- src/com/palmergames/bukkit/towny/object/Nation.java
- src/com/palmergames/bukkit/towny/object/Resident.java
- src/com/palmergames/bukkit/towny/object/Town.java
- src/com/palmergames/bukkit/towny/object/TownyObject.java
- src/com/palmergames/bukkit/towny/war/eventwar/War.java
`TownyFormatter.getFormattedName(obj);`
`obj.getFormattedName();`
This is accomplished by adding `.getFormattedName()` to `TownyObject`, which just replaces underscores with spaces by default. It's up to the subclassed object to determine if the default behavior will be overridden. 
- Removed TownyFormatter.getNamePostfix and TownyFormatter.getNamePrefix as they were never used. And were redundant to the `TownySettings` methods.
____ …
> Reorganize TownyFormatter methods to prevent code verbosity

- src/com/palmergames/bukkit/towny/utils/NameUtil.java
While the issue of the NPE may not be concrete this prevents NPE's from disruption the tab complete.
____
Closes #3723
____
> Hotfix: Fix any *possible* NPE's in NameUtil.

- src/com/palmergames/bukkit/towny/war/flagwar/listeners/TownyWarCustomListener.java
Fixes issue where the "won" townblock would not be saved/transferred after restart in flag war.
____
> Hotfix: Fix Flagwar townblock town transfer.

- src/com/palmergames/bukkit/towny/command/BaseCommand.java
- src/com/palmergames/bukkit/towny/command/PlotCommand.java
Fix an issue where the toggle options for plots would not tab complete for `/plot toggle`. This was due to the wrong number of arguments being passed in. However instead of simply fixing the issue, I opted to remove the method from the base command (which was only being used by the plot toggle command) instead. This was to follow suit for what the other towny commands were doing for toggle which I believed was a better route. 
____ …
> Fix plot toggle tab-completion and remove unused code.

- src/com/palmergames/bukkit/towny/command/BaseCommand.java
- src/com/palmergames/bukkit/towny/command/InviteCommand.java
- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/PlotCommand.java
- src/com/palmergames/bukkit/towny/command/ResidentCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/towny/command/TownyCommand.java
- src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
This just gets rid of the redundant `new ArrayList<>()` call. It's important to note that `Arrays.asList()` creates a unique arraylist backed by a fixed array. This means that you cannot mutate the size of the list (attempting to will throw an `UnsupportedOperation Exception` . This works in our favor as Siris and I both agreed that we want a fixed list for the tab-completes.
____
> Remove redundant arraylist creation for tab-completion.

- src/com/palmergames/bukkit/towny/TownyFormatter.java
Add space after commas between nation/town ranks.
Addresses EarthMC/Issue-Tracker#1020 and imo looks nicer
____
> Add space after commas between nation/town ranks

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
One of the main complaints I have in terms of UX with Towny, is the lack of persistence with chunk notifications. While moving the text out of chat was a step forward, the small window of time that the notification currently stays on-screen seems like a step backward. So with this PR the duration of the action bar will be modifiable via the config, which sets the default at 15 seconds. This may seem like a lot compared to the ~3s time now, but persistence is the key here.
____
`notification.notification_actionbar_duration` with default value of `15`
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the …
> Add Duration Config Option for Action Bar and Increase Default Duration

- src/com/palmergames/bukkit/towny/ChunkNotification.java
- src/com/palmergames/bukkit/towny/TownyAPI.java
- src/com/palmergames/bukkit/towny/TownyAsciiMap.java
- src/com/palmergames/bukkit/towny/TownyUniverse.java
- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/command/TownyCommand.java
- src/com/palmergames/bukkit/towny/db/TownyDataSource.java
- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java
- src/com/palmergames/bukkit/towny/object/Nation.java
- src/com/palmergames/bukkit/towny/object/Town.java
- src/com/palmergames/bukkit/towny/object/TownBlock.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
- src/com/palmergames/bukkit/towny/object/WorldCoord.java
- src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
- src/com/palmergames/bukkit/towny/tasks/HealthRegenTimerTask.java
- src/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java
- src/com/palmergames/bukkit/towny/tasks/TownClaim.java
- src/com/palmergames/bukkit/towny/utils/CombatUtil.java
- src/com/palmergames/util/FileMgmt.java
This Branch will accomplish a number of things, most importantly:
- Stop saving and loading townblocklists (towny\data\townblocks.txt
- Townblocks are loaded from the towny\data\townblocks folder directly and stored in their Towns primarily, with a seconday map being held in TownyUniverse as a fallback.
- Remove townblocks from the TownyWorlds, where they were in far to large a group to reasonably save them.
- Hopefully solve the issue of disappearing townblocks.
____
None.
____
All of the tickets in the Disappearing Townblocks project.
#3783 #3796 #3813 #3821 #3844
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge …
> Branch will remove TownBlockLists saving/loading, remove TownBlocks from TownyWorld, add TownBlocks to Town and TownyUniverse.

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/object/Nation.java
- src/com/palmergames/bukkit/towny/object/Town.java
Adds the ability to set seperate tax limits for both towns and nations.
____
`economy.daily_taxes.max_town_tax_amount` - the max town tax
`economy.daily_taxes.max_town_tax_percent` - the max town tax percent
`economy.daily_taxes.max_nation_tax_amount` - the max nation tax
`economy.daily_taxes.max_plot_tax_amount` - the max plot tax
**Removed**
`economy.daily_taxes.max_tax_percent`
`economy.daily_taxes.max_tax_amount`
These values should be migrated to the new config options.
____
Closes #3598
____ …
> add separate tax limits for towns, nations and townblocks

- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/event/NationBonusCalculationEvent.java
This adds `NationBonusCalculationEvent` to the API which allows plugins to modify the nation bonus returned by a nation. This is a particularly useful if plugins want to add nation bonus blocks based on their own specific criteria rather than what is determined by Towny config.
The reason the event call was placed in the TownySettings directory was because that was the converging method call for fetching the nation bonus and thus removed the need for placing the event call in every location the nation bonus was accessed.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the …
> Nation Bonus Event

- resources/chinese.yml
- resources/english.yml
- resources/es-mx.yml
- resources/french.yml
- resources/german.yml
- resources/italian.yml
- resources/korean.yml
- resources/norwegian.yml
- resources/plugin.yml
- resources/polish.yml
- resources/pt-br.yml
- resources/russian.yml
- resources/spanish.yml
- resources/zh-TW.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/object/Town.java
- src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
This adds the config option for the max amount of tax money towns can collect from a tax percentage.
____
- default 10000
- Controls the highest amount of money that can be taken from a tax percentage.
New Command `/t set taxpercentcap {amount}`
**Now Tax percentages are default in the config instead of flat taxes.**
This also includes lang strings.
____
Closes #3967
____
- **Test 1**
Town Tax = 10%
Max Percent Tax Amount = `10,000`
Player balance: `$99,522,260`
Player balance after newday: `$99,512,260`
`10%` of `99,522,260` is `99,522,26`, 
- **Test 2**
Town Tax = 10%
Max Percent Tax Amount = `500` -> *Custom amount set via command*
Player balance: `$99,999,554`
Player balance after newday: `$99,999,054`
`10%` of `99,999,554` is `99,999,55`
- **Test 3**
Town Tax = 10%
Max Percent Tax …
> Add max tax amount for tax percent

- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- With current towny master code, certain misconfigurations of Townyperms.yml will cause a cascading DB failure
- The failure flow is as follows:
1. Server deploys a bad townyperms file, and starts server
2. Towny tries to load all residents
3. Towny tries to load resident x, but fails due to the bad townyperms.yml
4. Resident is consider 'bad data' and removed
5. All residents removed in turn
6. All towns removed as they are empty
7. All nations disbanded as they are empty
- I don't know what exactly it is in the townyperms.yml file which causes the exception.
- I have an exact example of such a townyperms.yml file, won't append here as it belongs to a particular server, but can provide on request if server agrees too.
- This pull request fixes the issue by not failing the resident load …
> Fixed issue where a badly configured townyperms.yml causes DB failure

- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
Fix H2 not accepting implicit relative paths. Ended up just using an absolute path because why not.
____
I tried to test it, but Idk how to install the h2 driver.
> Use absolute path for H2

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/Towny.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- src/com/palmergames/bukkit/util/Version.java
This makes towny respect respawn anchors precedence on player respawn, instead of defaulting to the town spawn. This also makes sure that the server is running at least 1.16.1, if not the behavior is unchanged, so it doesn't break compatibility.
____
`global_town_settings.respawn_anchor_higher_precendence` -  defaults to  'true'
When this is true, players will respawn to respawn anchors on death rather than their own town. 1.16+ only.
____
Closes #4132
____ …
> 1.16.1: Add Respawn Anchor Integration

- src/com/palmergames/bukkit/towny/object/Resident.java
- src/com/palmergames/bukkit/towny/utils/NameUtil.java
This fixes the formatted name for residents that have color codes in their username. For example &l&omy_username will now be translated properly to _**my_username**_ 
____
> Add color code translation to resident formatted names.

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/object/Nation.java
- src/com/palmergames/bukkit/towny/object/Town.java
The PR title says it all - it adds 2 config options to change the default town & nation board message.
____
- `town.default_board`
- `global_nation_settings.default.board`
____
N/A
____
> Add configurable default Town&Nation board

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/Towny.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Adds a config option to allow keeping inventory when dying on an arena plot.
____
`global_town_settings.keep_inventory_on_death_in_arena` - default `false`
Toggles keepinventory on arena plots.
____
Closes #4137 
____
> Add option for keep inventory for arena plots.

- src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java
Hi,
Add a fews PAPI placeholders for general use, or more specifics uses cases (see below).
____
PAPI Placeholders: 
- `%townyadvanced_town_prefix%`: Display the config-defined **prefix** of the player's **town** (ex: _ruins_, _settlement_, ...)
- `%townyadvanced_town_postfix%`: Display the config-defined **postfix** of the player's **nation** (ex: _ruins_, _settlement_, ...)
- `%townyadvanced_nation_prefix%`: Display the config-defined **prefix** of the player's **town** (ex: _lands_, _realms_, ...)
- `%townyadvanced_nation_postfix%`: Display the config-defined **postfix** of the player's **nation** (ex: _lands_, _realms_, ...)
- `%townyadvanced_player_jailed%`: Display `true` is the player is jailed, otherwise `false`.
- `%townyadvanced_player_plot_type%`: Display the townblock's type …
> New PlaceholderAPI placeholders

- src/com/palmergames/bukkit/towny/Towny.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/db/TownyDataSource.java
- src/com/palmergames/bukkit/towny/tasks/GatherResidentUUIDTask.java
- src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
- src/com/palmergames/bukkit/towny/tasks/TownyTimerTask.java
Just small minor cleanup. 
Changes TownyTimerTask to implement Runnable instead of TimerTask because it was literally doing nothing with the TimerTask extension. 
Also change the UUID task to implement Runnable to since it was being called with the Bukkit Scheduler.
Also the UUID task was using `.remove()` on a queue...so change it to use `poll()`.
Also encapsulate the UUID counter and smack on some accessor / mutator methods.
____ …
> Minor Task Cleanup

- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/object/Nation.java
- src/com/palmergames/bukkit/towny/object/Resident.java
- src/com/palmergames/bukkit/towny/object/TownBlock.java
- src/com/palmergames/bukkit/towny/object/TownyObject.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
Previously it was hard to get a specific customdatafield from the metadata which is often what plugins wanted to do. This PR changes the internal set to a map keyed by the customdatafield key and offers new granular methods to fetch metadata.
The customdatafield object was not changed in order to retain legacy compatibility, however I'm like 95% sure this PR will break legacy metadata compatibility because it changes `getMetadata()` to a collection rather than a set, so oh well.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution …
> Metadata Improvements

- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/util/FileMgmt.java
This fixes File IO synchronization to prevent race conditions for reads/writes, currently towny does something like this:
```java
public void writeFile(File file) {
synchronized (file) {
...
}
}
```
This does absolutely nothing because the given `file` parameter is different whenever another thread uses this method, thus bypassing the locking entirely. This PR fixes this and adds synchronization to other file IO methods.
____ …
> Hotfix: Fix file IO synchronization.

- src/com/palmergames/bukkit/towny/object/Government.java
- src/com/palmergames/bukkit/towny/object/Town.java
This should fix nation tax defaulting to -1. For some reason weird, towns were explicitly setting their taxes to -1 by default and then returning the default town tax if the actual tax value was -1. This PR just sets the default town tax initially and resets a tax to default if it's below 0.
____
> Fix taxes being below 0

- src/com/palmergames/bukkit/towny/TownySpigotMessaging.java
We had assumed that if you are running 1.16, you are running the latest version of BungeeCord. However, not everyone is and this assumption breaks when we try to use a `Content` class that is not on older versions of bungeecord that support 1.16.
This PR just catches the exception so it falls through. The recommended course of action still is for users to update Bungeecord.
____
Compiled Jar: …
> Fix ClassNotFound exception due to old bungeecord version

- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
- src/com/palmergames/bukkit/towny/tasks/TownClaim.java
- src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java
Residents were able to unclaim the town's homeblock through two methods: using `unclaim all` and `unclaim [rect/circle]`. This PR aims to prevent both of those because unclaiming the homeblock can result in desyncs and cause issues on loading the DB. 
____
> Prevent residents from being able to unclaim homeblocks.

- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
This fixes the error spam when do `/t {name}` where `{name}` fails the regex check.
____
Closes #4257
____
> Remove exception printing stacktrace from invalid name in getTown().

- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
Previously Towny was performing queries on every object in the DB. The number of queries could range in the thousands depending on how many townblocks and residents a server had. This PR just uses one query to fetch all rows for each loadable type and processes them with the result set. This should hopefully reduce the loadup time for users that use SQL storage. 
____
**DISCLAIMER: I tested …
> Reduce DB queries on startup.

- src/com/palmergames/bukkit/towny/TownyAPI.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
- src/com/palmergames/util/MathUtil.java
Optimizes the `hasNationZone()` method in the TownyAPI. This is done by removing the duplicate distance check and instead returning the closest townblock to a `Coord` object. The method of fetching the closest townblock is also optimized removing redundant object creation, and optimizing math calls. 
This optimization also introduces the class `MathUtil` which provides a math utility class that contains common functions or specified optimized methods. I plan to utilize this class to optimize other distance checks in another PR coming after this one is merged.
____
Tested on a local server with 1 town and 1 nation, feel free to test on a larger dataset. I don't expect any behavioral differences to be found between my small dataset and a large dataset.
By making this pull request, I …
> Optimize `hasNationZone()` method.

- resources/english.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownyFormatter.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
- src/com/palmergames/bukkit/towny/db/SQL_Schema.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/event/BedExplodeEvent.java
- src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
This PR will create a new setting per-world allowing for admins to turn off the explosion reverting caused by blocks (beds and respawn anchors as of modern minecraft,) independently from explosions caused by entities.
____
- New Config Option: new_world_settings.plot_management.wild_revert_on_block_explosion.enabled
- default: true
- Enabling this will slowly regenerate holes created in the wilderness by exploding blocks like beds.
- Is a default setting for new worlds only.
- New Config Option: new_world_settings.plot_management.wild_revert_on_block_explosion.blocks
- default: WHITE_BED,ORANGE_BED,MAGENTA_BED,LIGHT_BLUE_BED,YELLOW_BED,LIME_BED,PINK_BED,GRAY_BED,LIGHT_GRAY_BED,CYAN_BED,PURPLE_BED,BLUE_BED,BROWN_BED,GREEN_BED,RED_BED,BLACK_BED
- The list of blocks whose explosions should …
> Per-world Block Explosion Revert Setting.

- resources/pt-br.yml
Remove English messages from pt-BR translation.
____
> Adding pt-br translation to 0.85/0.86 version

- resources/ChangeLog.txt
- resources/chinese.yml
- resources/es-mx.yml
- resources/french.yml
- resources/german.yml
- resources/italian.yml
- resources/korean.yml
- resources/norwegian.yml
- resources/polish.yml
- resources/pt-br.yml
- resources/russian.yml
- resources/spanish.yml
- resources/zh-TW.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/db/SQL_Schema.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- src/com/palmergames/bukkit/towny/object/Town.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
- src/com/palmergames/bukkit/towny/utils/CombatUtil.java
- Added CombatUtil.preventFriendlyFire(attacker, defender, world).
- Deprecated CombatUtil.preventFriendlyFire(attacker, defender).
- Adds friendlyFire setting to database as a world setting.
____
- New Config Option: new_world_settings.pvp.friendly_fire_enabled
- Default: false.
- Do new world have friendly fire enabled by default?
- Does not affect Arena Plots which have FF enabled all the time.
- When true players on the same town or nation will harm each other.
- Removed Config Option: global_town_settings.friendly_fire
____
- Closes #1242.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced …
> Add per-world FriendlyFire setting.

- resources/config-migration.json
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/config/migration/ConfigMigrator.java
- src/com/palmergames/bukkit/towny/ChunkNotification.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/TownyUniverse.java
- src/com/palmergames/bukkit/towny/object/economy/BankAccount.java
- Fixes config migrator not working on town and nation level changes.
- Town and Nation levels were loading too early before migration and
throwing an exception for being incomplete.
- Fixes debt accounts not using custom town-account-prefixes.
- Was hardcoded to use "town-".
- Adds debtCapModifier to town levels.
- Uses debtCapModifier * debt_cap.override value.
____
- New Config Option: economy.bankruptcy.debt_cap.debt_cap_uses_town_levels
- default: false
- When true the debt_cap.override price will be multiplied by the debtCapModifier in the town_level section of the config. (Ex: debtCapModifier of 3.0 and debt_cap.override of 1000.0 would set a debtcap of 3.0 x 1000 = 3000.)
____
- Closes #4374.
____
By making this pull request, I represent that I have the right to waive copyright …
> Fix Config Migrator & Add debtCapModifier

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyVehicleListener.java
- src/com/palmergames/bukkit/towny/utils/CombatUtil.java
- src/com/palmergames/bukkit/towny/utils/EntityTypeUtil.java
- src/com/palmergames/bukkit/towny/utils/ExplosionUtil.java
- Fixes item_frames getting blown up.
- Fixes non-player entities being harmed by blockexplosions,
entityexplosions and lightning all in one tiny method.
- Fixes end crystals & respawn anchors blowing up armor stands.
- Moves one instance of non-player/non-player entity-on-entity damage
into the CombatUtil's preventDamage().
- The scenario where a dispenser fires an arrow/projectile at a
non-player.
- Unifies the canLocationExplode methods into one ExplosionUtil method.
- Rewrote the method to be more simple. It will change again when the
war parts are removed and turned into an event.
- Fixes vehicles being destroyed by null attackers (respawn anchor,
beds, tnt minecarts, probably others,) and adds Boats to the list of
protected things.
- Adds RespawnAnchors to the BedExplodeEvent …
> More explosions protections.

- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- Potential solution for #4100.
- Not ideal.
- So far I have not found a way to handle Dragon Fireballs better.
- They fire a ProjectileHitEvent which cannot be cancelled.
- They generate an AreaEffectCloud which only returns the type
UNCRAFTABLE.
- The only way so far is to listen for the AreaEffectCloudApplyEvent
and if it is UNCRAFTABLE, check the hurt entities one by one using the
CombatUtil.
- As this is technically a mob damage, it shouldn't really be
considered PVP (arrows fired by a skeleton from outside of town still
hurts players with PVP off.)
- Some people are using slimefun to have dragon pets that end up
shooting these fireballs...
____
____
#4100
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and …
> Dragon Fireball Damage handling.

- src/com/palmergames/bukkit/towny/command/NationCommand.java
There were several things in the neutral toggling code that were being mishandled.
First, several towny exceptions being thrown were preemptively caught. The handler of those exceptions then immediately set nation peaceful to off. This was fixed by removing the try-catch entirely and just letting the method executors handle the exceptions. 
Second, switching from peaceful to non-peaceful never charged a nation, however we were sending a falsely sending a "Nation has paid ..." message when nations switched to non-peaceful. This is fixed by just sending the message when toggling to peaceful.
____
Should fix #4467 (did not intentionally put closes since I don't know if this is the cause).
____
By making this pull request, I represent that I have the right to waive copyright and related …
> Fix nation neutral messages

- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Attempts to address the following issue.
> found out you can lock towny in safe mode by joining a town you're outlawed in using townyadmin, which will cause towny to startup in safe mode next restart - @GNosii 
____
____
____
> Hotfix: Prevent admins from Soft-Locking Towny by force-joining outlaws.

- resources/english.yml
- resources/plugin.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownyFormatter.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/command/PlotCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/towny/command/TownyCommand.java
- src/com/palmergames/bukkit/towny/db/SQL_Schema.java
- src/com/palmergames/bukkit/towny/db/TownyDataSource.java
- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/event/town/TownReclaimedEvent.java
- src/com/palmergames/bukkit/towny/event/town/TownRuinedEvent.java
- src/com/palmergames/bukkit/towny/object/Town.java
- src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
- src/com/palmergames/bukkit/towny/tasks/HourlyTimerTask.java
- src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
- src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
- src/com/palmergames/bukkit/towny/war/common/townruin/TownRuinSettings.java
- src/com/palmergames/bukkit/towny/war/common/townruin/TownRuinUtil.java
- src/com/palmergames/util/TimeTools.java
- Probably caught a 2nd bug with the mysql implementation of ruins' hours.
- Adds a permission node to /town reclaim.
- Adds TownReclaimedEvent & TownRuinedEvent.
- Cleans up TownRuinUtil to use the API in places it did not.
- Changes PlotCommand test to check the townblock's town and not the player running the command.
- Maxes out the RemainingHours at 1000.
- Remove unnecessary isRuined() tests in DailyTimerTask.
- the town.hasUpkeep() is false for all NPC mayor'd towns.
____
New Command:
- /town reclaim - Reclaims a town from ruin status, must be run by a town resident (but not the mayor.)
New Permission Node: 
- towny.command.town.reclaim
- childnode of towny.command.town.*
New Config Options:
- economy.new_expand.price_reclaim_ruined_town
- default: 500.0
- How much it costs to …
> Merges in the Ruined Town feature from Goosius' SiegeWar.

- resources/plugin.yml
- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/db/SQL_Schema.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/object/Government.java
- src/com/palmergames/bukkit/towny/object/Nation.java
- src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- src/com/palmergames/bukkit/towny/war/common/WarZoneListener.java
- src/com/palmergames/bukkit/towny/war/flagwar/listeners/FlagWarCustomListener.java
This PR will again lower the changes between Towny and SiegeWar Towny. 
It will also increase customize-ability of Event War and other plugins.
- Add towny.command.town.toggle.neutral permission node.
- Adds setNeutral, isNeutral to Government.
- Adds neutral setting to Towns in the database.
- Deprecates the Nation toggleNeutral.
- Does NOT add the /town toggle neutral|peaceful command yet.
- Moves the neutrality tests for war off of the Nation object and onto the war listeners.
____
Permission node: towny.command.town.toggle.neutral
- Child node of towny.command.town.toggle.*
____
Closes #4531 
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions …
> Move neutral setting to Government, allowing Towns to become neutral.

- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/event/town/toggle/TownToggleEvent.java
- src/com/palmergames/bukkit/towny/event/town/toggle/TownToggleExplosionEvent.java
- src/com/palmergames/bukkit/towny/event/town/toggle/TownToggleFireEvent.java
- src/com/palmergames/bukkit/towny/event/town/toggle/TownToggleMobsEvent.java
- src/com/palmergames/bukkit/towny/event/town/toggle/TownToggleNeutralEvent.java
- src/com/palmergames/bukkit/towny/event/town/toggle/TownToggleOpenEvent.java
- src/com/palmergames/bukkit/towny/event/town/toggle/TownTogglePVPEvent.java
- src/com/palmergames/bukkit/towny/event/town/toggle/TownTogglePublicEvent.java
- src/com/palmergames/bukkit/towny/event/town/toggle/TownToggleStateEvent.java
- src/com/palmergames/bukkit/towny/event/town/toggle/TownToggleTaxPercentEvent.java
These just make the TownToggleEvent subclasses prettier by adding an intermediary class called `TownToggleStateEvent` which is abstract and can be extended by events in the package. Furthermore, this PR resolves two bugs.
The first issue is that previously the toggle events assumed that the future state was going to be the opposite of the current state, however this is not the case if a boolean is specified when toggling. Thus, this PR forces all the toggle events to manually take in the new state. 
The second issue was that the `TownToggleOpenEvent` was being fired where the `TownToggleNeutralEvent` should have been.
Will make a similar PR fixing the Nation toggle events soon.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my …
> Fix/Improve Town Toggle Events

- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
The purpose of this PR is to fix a double negative I encountered while looking through some code. Currently, players with the required permissions are unable to pull entities with fishing rods, but those without permissions are able to. 
None
____
None
____
> Fix onPlayerFishEvent double negative

- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
Fixes null UUID on NationAddTownEvent when a new nation is created (as pointed out by XuPuPG on discord). Also fixes registered times being invalid when NationAddTownEvent / TownAddResident events are called because registered time is set later.
____
Closes #4557 
____
> Fix null UUID on NationAddTownEvent

- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
This PR allows admins to force delete a town right away by running `/ta town [town] delete` if it's already in ruins.
____
____
____
> Allow admins to force delete a town if it's already ruined

- src/com/palmergames/bukkit/towny/command/TownCommand.java
- Moves a number of town subcommands around, bringing them ahead of the ruin test.
- Creates a singular townStatusScreen method used in each place the
status screen can be called.
- Removes unneeded townMayor townHere methods.
- Enables ruined town members to still be able to do /t {othertown}.
- Switches out townyUniverse for permSource in a couple methods where we
were really only using it for the getPermissionsSource() anyways.
- Create new townResList and townOutlawList methods to minimize the
parseTownComamnd() and make it more readable.
____
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the …
> town command cleanup

- src/com/palmergames/bukkit/towny/command/InviteCommand.java
The purpose of this PR is to fix the bug of Towns being able to surpass the `max_residents_per_town` config option by inviting multiple residents before hitting the cap, and having them all join. This PR adds a check from the /town invite command to make sure the town the resident is trying to join isn't at or above the cap.
____
____
____
> Fix towns being able to go over the maximum residents.

- src/com/palmergames/bukkit/towny/object/Town.java
- With current code , when a town with an "isConquered" value of true (AKA an 'occupied town), leaves a nation, it retains the true value.
- This makes no sense, because by leaving the nation it is of course no longer occupied by any national power,
- Also the status of "(Conquered)" is still displayed on the town screen
- I fixed the above bug in this small PR by setting isConquered to false when a town leaves its nation
____
NA
____
NA
____ …
> Fixed Conquered Flag not changing when town leaves nation

- src/com/palmergames/bukkit/towny/TownyFormatter.java
- src/com/palmergames/bukkit/towny/TownyUniverse.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/event/LoadedMetadataEvent.java
- src/com/palmergames/bukkit/towny/exceptions/InvalidMetadataTypeException.java
- src/com/palmergames/bukkit/towny/object/Nation.java
- src/com/palmergames/bukkit/towny/object/Resident.java
- src/com/palmergames/bukkit/towny/object/Town.java
- src/com/palmergames/bukkit/towny/object/TownBlock.java
- src/com/palmergames/bukkit/towny/object/TownyObject.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
- src/com/palmergames/bukkit/towny/object/metadata/BooleanDataField.java
- src/com/palmergames/bukkit/towny/object/metadata/CustomDataField.java
- src/com/palmergames/bukkit/towny/object/metadata/DataFieldDeserializer.java
- src/com/palmergames/bukkit/towny/object/metadata/DataFieldIO.java
- src/com/palmergames/bukkit/towny/object/metadata/DecimalDataField.java
- src/com/palmergames/bukkit/towny/object/metadata/IntegerDataField.java
- src/com/palmergames/bukkit/towny/object/metadata/LongDataField.java
- src/com/palmergames/bukkit/towny/object/metadata/MetadataLoader.java
- src/com/palmergames/bukkit/towny/object/metadata/RawDataField.java
- src/com/palmergames/bukkit/towny/object/metadata/StringDataField.java
- src/com/palmergames/bukkit/towny/object/metadata/TownyCDFDeserializer.java
This is the last phase of metadata improvements. It allows for plugins to create and store their own custom metadata types.  It also changes how metadata is stored. Metadata is now stored as a JSON array of arrays. The reason for this is so that type ids, keys, values, and labels have no serialization restrictions. Previously, if any of those contained a `,` or `;`, then it would break. 
There is also some new useful API. Instead of fetching metadata by key and then having to check the type in two separate steps it can be done as one. E.g. To fetch an `IntegerDataField` meta with the key "kills", you can do `townyobject.getMetadata("kills", IntegerDataField.class)`.
The way to create a custom metadata type is pretty simple. A developer just needs to create a new class extending …
> Custom Metadata Types

- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
This PR fixes an exploit that would allow players to rename their towns/nations for free, by withdrawing gold from their banks before doing /confirm.
____
____
____
> Fix free town/nation rename exploit

- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Removes a double sendGlobalMessage that caused double town deletion messages.
____
____
____
> Fix town delete message being sent twice

- src/com/palmergames/bukkit/towny/event/town/TownMapColourCalculationEvent.java
- src/com/palmergames/bukkit/towny/object/Town.java
- I need an event for something I'm doing at the moment.
- This event will be when a town returns its map colour.
- This is to allow siegewar (for example) to intervene in the display of individual town map (ie dynmap) colours.
____
N/A
____
N/A
____
> Add event for the calculation of town map color

- src/com/palmergames/bukkit/towny/TownySpigotMessaging.java
- src/com/palmergames/bukkit/towny/event/nation/NationListDisplayedNumTownBlocksCalculationEvent.java
- With current code, the new list events do not fire on spigot
- This is because the logic for displaying the list branches for spigot (I didn't spot the branching)
- In this PR, I fix the issue (also was able to test to confirm the fix, now that I can use 0.96.7.8)
____
N/A
____
N/A
____
> Fix for displayed-nation-list events

- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/event/town/TownPreInvitePlayerEvent.java
Adds TownPreInvitePlayerEvent, a cancellable event that gets fired before a resident is invited to a town.
____
____
____
> Add TownPreInvitePlayerEvent

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/util/NameValidation.java
Adds a configurable blacklist that can be used to block certain town/nation names.
____
Adds plugin.name_blacklist:
- Default: empty
- A blacklist used for validating town/nation names.
- Names must be seperated by a comma: name1,name2
____
Closes #4875
____
> Add town/nation name blacklist config option

- resources/chinese.yml
- resources/english.yml
- resources/es-419.yml
- resources/french.yml
- resources/german.yml
- resources/italian.yml
- resources/korean.yml
- resources/norwegian.yml
- resources/plugin.yml
- resources/polish.yml
- resources/pt-br.yml
- resources/russian.yml
- resources/se-SV.yml
- resources/spanish.yml
- resources/zh-TW.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
Allows blocking commands while inside a town.
____
**CONFIG OPTIONS**
- global_town_settings.town_command_blacklisting.enabled
- global_town_settings.town_command_blacklisting.blacklisted_commands
- global_town_settings.town_command_blacklisting.limited_commands
**PERM NODES**
- towny.admin.town_commands.blacklist_bypass
____
Closes #4835 
____
> Town command blacklisting

- src/com/palmergames/bukkit/towny/utils/CombatUtil.java
____
Fixes entity vs entity combat always being allowed, because of the a == b check always returning true because both would be null. Also fixes wolves being able to attack protected mobs and players inside claimed areas.
____
____
> Fix entity-vs-entity combat always being allowed

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
- src/com/palmergames/bukkit/towny/object/WorldCoord.java
Fixes water & lava being usable to grief other towns, by using the same testBlockMove function that pistons use.
____
New Config Option: global_town_settings.prevent_fluid_griefing
- When enabled, blocks like lava or water will be unable to flow into other plots, if the owners aren't the same.
____
____
> Fix water & lava being usable to grief others.

- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/PlotCommand.java
- src/com/palmergames/bukkit/towny/command/ResidentCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/towny/command/TownyCommand.java
- src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
- src/com/palmergames/bukkit/towny/object/AddonCommand.java
Fixes the command variable always being null while running a subcommand, and fixed a TownyException being thrown if onCommand returns null.
____
____
Closes #4971 
____
> Fix command always being null

- src/com/palmergames/bukkit/towny/TownyMessaging.java
- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/object/comparators/ComparatorCaches.java
Creates caches for the town and nation lists:
- One cache for town listing, one for nation listing,
- Indexed by the ComparatorType, values are pre-formatted TextComponent lists.
~~TODO: return the ability to have the town list at random.~~
~~TODO: re-test that the newly-built caches are returning new data (I have seen the /t list by balance not update correctly.)~~
- I found that it does update, but sometimes the bank's cachedBalance hasn't quite expired due to both caches having 10 minute expirations.
____
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to …
> Town and Nation Listing get Cached.

- src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java
Make applicable placeholders available when a player is offline (all except for player_plot_* and player_location_*)
Make certain placeholders useable when a player is offline. This is all except for plot and location placeholders.
____
____
____
> Make applicable placeholders available when a player is offline

- src/com/palmergames/bukkit/towny/event/nation/DisplayedNationsListSortEvent.java
- src/com/palmergames/bukkit/towny/object/comparators/ComparatorCaches.java
- This PR adds a new event, DisplayedNationsListSortEvent
- The event is called after "/n list" is run and the nation list is ordered
- This allows for custom ordering of the list by plugins
- This is needed as part of the fix for https://github.com/TownyAdvanced/SiegeWar/issues/310
____
N/A
____
N/A
____
> SW-310: Added event for custom ordering of displayed nations list

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/db/SQL_Schema.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
- src/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java
- src/com/palmergames/bukkit/towny/regen/block/BlockLocation.java
This adds a block whitelist to the behavior that regenerates the wilderness after an explosion. Since it is a whitelist, if the config option is empty or not present, all blocks will be considered protected.
I have tested this in every configuration (configured with values, configured empty, and key not present) with the flatfile database, but I have not tested it with the SQL database as I don't have one set up.
____
Nodes:
wild_revert_on_explosion_block_whitelist: ''
New world settings:
PlotManagementWildRegenBlockWhitelist=
____
____
- [x ] I have tested this pull request for defects on a server. 
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions …
> Add a block whitelist to wilderness explosion regeneration

- pom.xml
- src/com/palmergames/bukkit/towny/hooks/LuckPermsContexts.java
Adds even more Towny contexts to luckperms.
With this feature, you can setup permissions for players with ranks which are at the moment inside town, which i find very useful
____
____
____
> Add town&nation rank luckperms contexts

- resources/plugin.yml
The purpose of this pull-request is to reinforce adding all listing options as `towny.command.town.list.*`.
As it currently stands, the admin has the option to allow users to do `/t list by <option>` which have corresponding permissions such as `towny.command.town.list.balance`. But if an admin wants to remove the option to use a certain `list by <option>`, they have to remove `towny.command.town.list`, which currently grants access to `towny.command.town.list.*` but the down side is the user is no longer able to use `/t list`, which is the most popular usage.
____
Changes `towny.command.town.list` to allow access to the root `/t list` command but not grant access to all listing options & their permissions.
____
N/A
___
By making this pull request, I represent that I have the right to …
> Remove "/t list"`s root permission granting access to all listing options.

- src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
- src/com/palmergames/bukkit/towny/object/WorldCoord.java
Fixes blocks not being pushable between 2 plot borders in the wilderness, and adds WorldCoord#isWilderness for better readability.
____
____
Closes #5127
____
> Allow moving of blocks between wilderness plot borders

- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Moves the isTownyAdmin permission check below the teleport request check, to avoid doing permissions checks for a player that does not have a teleport warmup.
____
____
____
> Move permissions check down in onPlayerMove

- src/com/palmergames/bukkit/towny/object/inviteobjects/PlayerJoinTownInvite.java
- src/com/palmergames/bukkit/towny/object/inviteobjects/TownJoinNationInvite.java
An AlreadyRegisteredException spawns when a user accepts two more invites without leaving a town prior. This check will warn the player they are already in a town and not add them but remove the invite. 
____
____
Didn't make an issue.
____
Tested on 1.17.1.
> Fix AlreadyRegisteredException when accepting two invites or more

- resources/config-migration.json
- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Prevents chickens from being spawned if a player does not have item_use permissions. Dispensers could be used to bypass this, but this is mainly meant for preventing players from spawning tons of chickens in areas that do not belong to them.
____
____
____
> Prevent chickens being spawned without permission

- jitpack.yml
> Make jitpack build using java 16

- resources/lang/en-US.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- src/com/palmergames/bukkit/towny/object/Resident.java
Players who have died and are being respawned in a location set by Towny (town_respawn: true in the config) will be granted a period of invulnerability. This is taken away early if the player attacks another player, or if they teleport.
____
- New Config Node: global_town_settings.respawn_protection
- Default; 10s
- When greater than 0s, the amount of time a player who has respawned
is considered invulnerable.
- Invulnerable players who attacker other players will lose their
invulnerability.
- Invulnerable players who teleport after respawn will also lose their
invulnerability.
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and …
> Adds spawn protection for players who've just died.

- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Fixes a towny issue and basically always ignores Citizens2 Player's in Towny events.
Mainly caused by a missing resident != null for the new resident spawn protection task.
____
Nope
____
#5318 
____
> Fix Citizens NPCs causing error on PlayerTeleportEvent.

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
> Add a size limit for the town_block_ratio option.

- resources/lang/en-US.yml
- resources/plugin.yml
- src/com/palmergames/bukkit/towny/TownyAPI.java
- src/com/palmergames/bukkit/towny/command/HelpMenu.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/towny/db/SQL_Schema.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/object/Town.java
- src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
Admins can set an override on a nationzone size per-town.
____
- New Command: /ta set nationzoneoverride [town] [size]
- Sets a town's nationzone override.
- New Permission Node: towny.command.townyadmin.set.nationzoneoverride
- Child node of towny.command.townyadmin.set.*
____
- Closes #4915.
____
> Adds ability to override a town's NationZone.

- resources/plugin.yml
- src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
Currently, in the plugin.yml and PermissionNodes, capital is called capitol, even though the perm node being tested for in NationCommand uses capital because of the catch-all permissions check.
____
____
____
> Fix typo in /n set capital node.

- src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java
- src/com/palmergames/bukkit/towny/utils/CombatUtil.java
This PR adds two new methods to CombatUtil that allow developers to check if two players are allied/enemied using their resident objects rather than name strings. 
When profiling my server's memory allocations, I noticed Towny's relational placeholder was a [big contributor](https://i.gyazo.com/eb87967ef5b8d55c0cb009fe98a903e6.png) to them as the use of the existing `CombatUtil#isAlly` and `CombatUtil#isEnemy` methods required fetching the players' resident objects from their names. Since we already have their resident objects, I changed the placeholder to use the new methods instead. This should reduce the garbage created by the placeholder on servers with many players.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related …
> Add new API to CombatUtil

- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- src/com/palmergames/bukkit/towny/regen/PlotBlockData.java
- src/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java
- src/com/palmergames/bukkit/towny/tasks/RepeatingTimerTask.java
- src/com/palmergames/bukkit/towny/tasks/TownClaim.java
Stops Towny from loading the entire regen queue into memory and
processing all the reverts at the same time.
Towny now loads the regen.txt into a list of WorldCoords which holds all
active and inactive revert-on-unclaims.
When there are less than 20 active reverts, Towny will look to see if
there are any available WorldCoords in the queue. If one is found only
then will the PlotBlockData object be created and loaded into memory.
____
____
Closes #5473 
____ …
> Queue the revert on unclaim feature.

- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/event/TownPreClaimEvent.java
If the claim is cancelled, then the Town is not claimed, and is immediately unregistered from TownyUniverse.
Shortfalls:
- The TownPreClaimEvent#getTown() is fairly unsafe to use, so there's warnings added to the javadocs.
- Someone listening for uncancelled PreNewTownEvents as a sure-fire sign that a town will be created will have a bad day (although I don't think anyone is going to use that over the NewTownEvent.)
____
____
Closes #3620 
____ …
> Add TownPreClaimEvent to initial TownBlock claimed during new Town code.

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/command/PlotCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
> Only apply the outsiders prevent pvp toggle when enabling pvp.

- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- src/com/palmergames/bukkit/towny/utils/CombatUtil.java
> Deprecate unused parameter in function

- src/com/palmergames/bukkit/towny/command/PlotCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java
Adds claim boolean to the selectWorldCoordArea, so that the available
selection size is only limited when the selection is actually for
claiming.
Selecting areas for unclaiming, and selecting areas to mark plot forsale
or notforsale are no longer limited to a town/residents availble claims.
Fixes resident claim limit not accounting for townblocks already
claimed.
Fixes /ta unclaim passing in a null TownBlockOwner meaning the available
value was left at 0.
- Closes #5606.
____
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution …
> Fix AreaSelectionUtil treating every selection like it will be for claiming.

- src/com/palmergames/bukkit/towny/object/WorldCoord.java
- src/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java
- src/com/palmergames/bukkit/towny/tasks/RepeatingTimerTask.java
- src/com/palmergames/bukkit/towny/tasks/ShortTimerTask.java
Slows down the attempted adding of PlotBlockData to the active regenerations, from every second to every 20 seconds.
Loads unloaded chunks so that PlotBlockDatas will revert land where players aren't actively logged in.
____
____
____
> Fix regen queue blocking up with unloaded chunks.

- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- src/com/palmergames/bukkit/towny/utils/TownRuinUtil.java
Currently, the delayFullRemoval boolean in TownyDatabaseHandler#removeTown will always be false, because the resident is removed before that code is called. This pr switches that around, so that the town can properly ruin.
____
____
____
> Put town into ruined state when last resident is deleted.

- src/com/palmergames/bukkit/towny/object/Translation.java
... and a plugin is calling for a string which was not translated to that locale.
____
____
____
> Correctly fall back to the en_US when a server is using not-en_US

- src/com/palmergames/bukkit/towny/object/TranslationLoader.java
Fixes the translation loader loading lang/global.yml instead of the correct lang/override/global.yml.
Also closes the InputStream used in that method correctly.
____
____
____
> Fix translation loader loading global from the wrong location.

- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/event/executors/TownyActionEventExecutor.java
- src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyVehicleListener.java
- src/com/palmergames/bukkit/towny/object/TownBlockTypeHandler.java
- src/com/palmergames/bukkit/towny/utils/EntityTypeUtil.java
- src/com/palmergames/bukkit/util/ItemLists.java
> ItemLists overhaul

- resources/config-migration.json
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
> Fix revert explosion entities being wiped

- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
This PR fixes a small issue with the `/ta checkperm` command having the tab completion of `/ta database`. I tested it for functionality and it works fine, but I am unsure as to how efficient it is (Especially on servers with lots of permissions. I have 16 plugins on my test server and did not notice any lag). I am also still very new to Git/PRs so if I messed anything up let me know.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) …
> Fix /ta checkperm having incorrect tab completions

- resources/lang/en-US.yml
- src/com/palmergames/bukkit/towny/command/NationCommand.java
Replaces #5824
Admins using /ta nation <nation> set <capital|king> now bypass checks for resident limits for the new and old capital. This makes it easier to transfer the nation to a new king without impacting the old capital or its residents.
____
____
____
> Let admins bypass nation capital checks

- src/com/palmergames/bukkit/towny/command/TownyCommand.java
`/towny top balance` outputs only the header. This PR fixes that, which was caused by the change to async even though the messages weren't being sent async. Initially I switched it back to sync, but I figured this was a better fix because it *should* still offer the performance boost for large servers.
____
N/A
____
Fixes #5838 
____
> Fix /towny top balance

- src/com/palmergames/bukkit/towny/hooks/LuckPermsContexts.java
Permission per town/nation is a must-have feature for people doing automation without new plugins. I don't understand why it is not a thing yet. Here's a PR to fix it
____
none.
____
Haven't seen one (surprisingly)
____
> added town & nation contexts

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/Towny.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/hooks/LuckPermsContexts.java
- src/com/palmergames/bukkit/towny/object/PlayerCache.java
> Allow specific luckperms contexts to be disabled

- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- src/com/palmergames/bukkit/util/ItemLists.java
Adds a build test to filling cauldrons and a destroy test to emptying a cauldron
____
____
____
> Protect against cauldron filling/emptying

- resources/config-migration.json
- resources/lang/en-US.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- src/com/palmergames/bukkit/towny/object/Resident.java
Adds an option to disable the ability for players to pickup items while under respawn protection.
____
New config option: global_town_settings.respawn_protection.allow_pickup
If disabled, players will not be able to pickup items while under respawn protection.
____
____
> Add option to disable pickups while under respawn protection

- src/com/palmergames/bukkit/towny/object/economy/AccountAuditor.java
- src/com/palmergames/bukkit/towny/object/economy/GovernmentAccountAuditor.java
> Add AccountAuditor#getTransactions

- src/com/palmergames/bukkit/towny/Towny.java
- src/com/palmergames/bukkit/towny/hooks/LuckPermsContexts.java
- src/com/palmergames/bukkit/towny/object/PlayerCache.java
Fixes:
```
[02:21:24] [pool-66-thread-1/WARN]: [LuckPerms] An exception was thrown by com.palmergames.bukkit.towny.hooks.LuckPermsContexts whilst calculating the context of subject CraftPlayer{name=Eurykles}
java.lang.NullPointerException: Cannot invoke "com.palmergames.bukkit.towny.object.WorldCoord.hasTownBlock()" because the return value of "com.palmergames.bukkit.towny.object.PlayerCache.getLastTownBlock()" is null
at com.palmergames.bukkit.towny.hooks.LuckPermsContexts.lambda$new$6(LuckPermsContexts.java:45) ~[Towny-0.98.2.0.jar:?]
at com.palmergames.bukkit.towny.hooks.LuckPermsContexts.calculate(LuckPermsContexts.java:95) ~[Towny-0.98.2.0.jar:?]
at com.palmergames.bukkit.towny.hooks.LuckPermsContexts.calculate(LuckPermsContexts.java:32) ~[Towny-0.98.2.0.jar:?]
at …
```
> Fix potential NPE in towny:insidetown luckperms context.

- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
> Make respawn anchors respect the deny bed use option

- src/com/palmergames/bukkit/towny/command/NationCommand.java
When setting nation tax to an amount greater than the maximum nation tax, the message sent will include the inputted amount, rather than the amount that the tax was actually set to.
____
N/A
____
N/A
____
> Fix nation tax message using inputted amount instead of what the taxes were actually set to

- src/com/palmergames/bukkit/towny/event/actions/TownyActionEvent.java
This pull request adds an Quality-of-Life change to the TownyActionEvent#setMessage(String) method by calling TownyActionEvent#suppressMessage(boolean) (added in #5925) if the content equals to `""`
____
____
____
> Auto-supress event message if empty

- resources/lang/en-US.yml
- src/com/palmergames/bukkit/towny/command/BaseCommand.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/towny/db/SQL_Schema.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/object/Town.java
- src/com/palmergames/util/StringMgmt.java
- /ta town NAME settownlevel #|unset.
- Changes a town's level from being population-based to something that
is overridden at townlevel calculation.
____
/ta town NAME settownlevel # or unset.
- Automatically will not set higher than there are levels.
____
____
> Add a command to manually override a town's TownLevel.

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/db/SQL_Schema.java
- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
- src/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java
- src/com/palmergames/bukkit/towny/tasks/RepeatingTimerTask.java
Allows Towny to delete all Entities of a given type from a TownBlock
when it is unclaimed by a town.
____
New Config Options:
- new_world_settings.plot_management.entity_delete.enabled
- new_world_settings.plot_management.entity_delete.unclaim_delete
- Default: "ENDER_CRYSTAL"
- These entities will be deleted upon a plot being unclaimed
____
Closes #5953.
____
> Add unclaimEntityTypeDelete to TownyWorld.

- src/com/palmergames/bukkit/towny/listeners/TownyVehicleListener.java
- src/com/palmergames/bukkit/util/ItemLists.java
Fixes vehicles not being killed by lava. At first I tried to store the vehicle's uuid in a list using the EntityCombustByBlockEvent, but that event doesn't get called for vehicles, so checking the fire ticks & attacker is the next best thing.
____
Closes #6007 
____
> Fix vehicles not being killed by lava

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/util/NameValidation.java
____
Adds 2 new config options: global_town_settings.allow_numbers_in_town_name & global_nation_settings.allow_numbers_in_nation_name
____
Closes #5954 
____
> Add option to disallow numbers in town/nation names

- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Allows spaces to be used in the town/nation rename commands, similar to how spaces are parsed in town/nation new commands.
Previous:
/t set name My Town -> town renamed to My
New:
/t set name My Town -> town renamed to My_Town
____
> Allow spaces to be used in town/nation rename commands

- resources/lang/en-US.yml
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towns can overwrite the upkeep setting of the config, but this setting wasn't modifyable per town by admins. This pull request adds a new admin town command toggle for upkeep.
____
`/ta town <town> toggle upkeep`
____
____
> Add admin town command upkeep toggle

- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
> Add /t & /n deposit all

- src/com/palmergames/bukkit/towny/TownyMessaging.java
- src/com/palmergames/bukkit/towny/object/Translatable.java
> Update translatable with changes from MiniMessage PR

- resources/config-migration.json
- resources/lang/en-US.yml
- src/com/palmergames/bukkit/config/migration/RunnableMigrations.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/object/Town.java
- src/com/palmergames/bukkit/towny/object/TownBlock.java
Allows server owners to configure plot limits for each town level
____
Adds a new townBlockTypeLimits entry to the town_levels
____
Closes #5889 
____
> Add configurable plot type limits

- src/com/palmergames/bukkit/towny/object/TownyObject.java
> Allow removing metadata by key

- src/com/palmergames/bukkit/towny/object/WorldCoord.java
> Add WorldCoord#getChunks

- src/com/palmergames/bukkit/towny/command/PlotCommand.java
Fixes the /plot info command (used by the ascii map) not being usable while standing in an unclaimed area.
____
> Fix plot info command not being usable in wilderness

- src/com/palmergames/bukkit/util/BookFactory.java
- src/com/palmergames/bukkit/util/FontUtil.java
> Use FontUtil's minecraftfont constant for bookfactory

- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Due to towns being able to set titles/surnames, it no longer makes sense to clear a resident's titles/surnames when a nation is removed.
____
N/A
____
N/A
____
> Stop removing title/surname when nation is deleted

- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- src/com/palmergames/bukkit/towny/utils/CombatUtil.java
Previously, axolotl would keep attacking the protected mobs by Towny within a town (so it looks like it's trying to keep attacking but no damage, forever). This PR additionally listens to the EntityTargetLivingEntityEvent, where it uses the original logic to check if the Axolotl is able to damage the defender. If it is not, then cancel the EntityTargetLivingEntityEvent and let the axolotl have its `has_hunting_cooldown` on (see [here](https://minecraft.fandom.com/wiki/Axolotl#Data_values) for this entity data).
I think this PR improves the code efficiency a bit because if the `has_hunting_cooldown` is on then axolotls won't having any attacking behaviour for at least 2 min. So neither EntityTargetLivingEntityEvent nor EntityDamageEvent will be called.
Previously, the axolotls would just …
> Prevent axolotls from targeting protected mobs

- src/com/palmergames/bukkit/towny/TownyMessaging.java
- src/com/palmergames/bukkit/util/Colors.java
- src/com/palmergames/util/StringMgmt.java
> Add colors class changes from minimessage branch

- src/com/palmergames/bukkit/towny/TownyAsciiMap.java
Fixes players being kicked by /towny map big if the map component is too big to be sent in a single packet, usually caused by tons of townblocks being near the player.
____
> Fix /towny map big kicking players in rare cases.

- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- src/com/palmergames/bukkit/towny/object/CommandList.java
Improves command blocking by preventing bypasses and accounting for namespaces.
Users can now block commands from a specific plugin by adding the namespace when adding a command, i.e. blocking towny:town will block both towny:town and town from being used, while still allowing otherplugin:town to be used.
If a command to be blocked does not contain a namespace, the command will be blocked in all namespaces.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE. …
> Improve command blocking

- src/com/palmergames/bukkit/towny/TownyCommandAddonAPI.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Added two new types for creating subcommands: TOWNYADMIN_TOWN and TOWNYADMIN_NATION which are triggered by /townyadmin town <town_name> and /townyadmin nation <nation_name> respectively
____
The purpose of this PR is to allow other developers to add their own subcommands for /townyadmin <town/nation> <government_name>. For example, /townyadmin town test mysubcommand.
I believe this will make the API more flexible
____
I tested this code on my local server paper 1.16.5
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the …
> API: Add TOWNYADMIN_TOWN and TOWNYADMIN_NATION CommandTypes

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/tasks/NewDayScheduler.java
Adds an option to use a timer for new day scheduling instead of using the bukkit scheduler, has the benefit of being guaranteed to be accurate without having to schedule lots of tasks.
____
New config option: plugin.day_timer.uses_timer
Default value: false
If enabled (disabled by default), a timer will be used for scheduling new days, which is more accurate but uses an extra thread.
____
Closes https://github.com/EarthMC/Issue-Tracker/issues/1585
____ …
> Add option to use a timer for new day scheduling.

- pom.xml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
> Remove old sculk spread option

- resources/lang/en-US.yml
- src/com/palmergames/bukkit/towny/TownyMessaging.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
> Town board command improvements

- src/com/palmergames/bukkit/towny/command/ResidentCommand.java
- src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Makes it so the brick into tool also requires /res toggle infotool before it can be used to prevent accidental use.
____
Closes #5875
____
> Put brick info tool behind infotool resident mode

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
____
New config option: global_town_settings.unkickable_ranks
Default value: assistant
List of ranks (separated by a comma) that will prevent a player from being kicked from a town.
____
Closes https://github.com/EarthMC/Issue-Tracker/issues/1523
____
> Make unkickable ranks configurable

- src/com/palmergames/bukkit/towny/TownyTimerHandler.java
- src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
- src/com/palmergames/bukkit/towny/object/CellBorder.java
- src/com/palmergames/bukkit/towny/tasks/DrawSmokeTask.java
- src/com/palmergames/bukkit/util/DrawSmokeTaskFactory.java
- src/com/palmergames/bukkit/util/DrawUtil.java
- src/com/palmergames/bukkit/util/LocationRunnable.java
> Change border smoke color based on affiliation

- resources/config-migration.json
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownyAPI.java
- src/com/palmergames/bukkit/towny/object/Resident.java
- src/com/palmergames/bukkit/towny/object/spawnlevel/NationSpawnLevel.java
- src/com/palmergames/bukkit/towny/object/spawnlevel/TownSpawnLevel.java
- src/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java
- src/com/palmergames/bukkit/towny/utils/SpawnUtil.java
```
- Allow for all nation spawn and town spawn types to have individual spawn cooldowns.
- Your previous global_town_settings.spawn_cooldown_time setting will be migrated to the new settings.
- Closes #6224.
- New Config Nodes: 
- global_town_settings.spawning_cooldowns.town_spawn_cooldown_time
- Default: 30 
- Number of seconds that must pass before a player can use /t spawn or /res spawn.
- global_town_settings.spawning_cooldowns.outpost_cooldown_time 
- Default: 30 
- Number of seconds that must pass before a player can use /t outpost.
- global_town_settings.spawning_cooldowns.nation_member_town_spawn_cooldown_time
- Default: 30
- Number of seconds that must pass before a player of the same nation can use /t spawn.
- global_town_settings.spawning_cooldowns.nation_ally_town_spawn_cooldo …
```
> Make spawn types' cooldowns separate and configurable.

- src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java
- Added PAPI placeholders:
- %townyadvanced_player_town_is_trusted% - returns True or False based on whether the player is in a town, and is trusted in the town.
- %townyadvanced_player_plot_is_trusted% - returns True or False based on whether the player is in a town, and is trusted in the plot.
____
____
Closes #6230 
____
> Added %townyadvanced_is_trusted% placeholder

- src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java
Adds placeholders for town's and nation's unformatted balance. They can be use to create leaderboards with another third-party plugin like ajLeaderboards.
- `%townyadvanced_town_balance_unformatted%`
- `%townyadvanced_nation_balance_unformatted%`
____
#5073
____
> Added unformatted town/nation balance placeholders

- resources/lang/en-US.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/command/NationCommand.java
Adds a config option to set the maximum amount of residents for nations.
____
```
- New Config Option: global_nation_settings.max_residents_per_nation
- Default: 0
- If higher than 0, it will limit how many residents can join a nation. Does not affect existing nations that are already over the limit.
```
____
#2402
____
> Added max residents per nation

- resources/plugin.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownyFormatter.java
- src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/command/HelpMenu.java
- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/db/SQL_Schema.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/event/nation/toggle/NationToggleTaxPercentEvent.java
- src/com/palmergames/bukkit/towny/object/Nation.java
- src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
Adds Tax percentage for nations
____
```
- New Commands:
- `/nation toggle taxpercent` - Toggle percentage nationtax on or off.
- `/nation set taxpercentcap` - Sets the max amount of money which can be gotten via percent nationtax, from a town.
```
```
- New Permission Nodes:
- `towny.command.nation.toggle.taxpercent` - Child node of towny.command.nation.toggle.*.
- ` towny.command.nation.set.taxpercentcap` - Child node of towny.command.nation.set.*.
- No changes to townyperms.yml required.
```
```
- New Config Options:
- nation.default_taxes.tax
- Default: 0.0
- Default amount of tax of a new nation. This must be lower than the economy.daily_taxes.max_nation_tax_amount setting.
- nation.default_taxes.taxpercentage
- Default status of new nation's taxpercentage. True …
```
> Nation tax percent

- src/com/palmergames/bukkit/towny/TownyTimerHandler.java
> Deprecate leftover uuid task method

- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
> Fix potion splash event edge case

- pom.xml
- src/com/palmergames/bukkit/towny/Towny.java
This PR includes some improvements to the way Javadocs are generated on build:
- Updates `maven-javadoc-plugin`
- Adds groups, allowing for an better and easier navigation through the documentation
- Switched an usage of an plain text link to an `<a>` tag
____
____
____
> Improve javadocs with <group> tags.

- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- src/com/palmergames/bukkit/towny/event/DeleteNationEvent.java
DeleteNationEvent#getNationKing was returning the UUID of the king, but
DeleteTownEvent#getMayor is returning a Resident.
So i've added two methods and deprecated the old one in DeleteNationEvent.
____
____
____
> DeleteNationEvent continuity fix

- resources/lang/en-US.yml
- resources/plugin.yml
- src/com/palmergames/bukkit/towny/command/BaseCommand.java
- src/com/palmergames/bukkit/towny/command/HelpMenu.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/towny/db/SQL_Schema.java
- src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- src/com/palmergames/bukkit/towny/event/town/TownTrustTownAddEvent.java
- src/com/palmergames/bukkit/towny/event/town/TownTrustTownRemoveEvent.java
- src/com/palmergames/bukkit/towny/object/Town.java
- src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
This pull request adds a new command to town commands titled `trusttown`, this allows a town member with appropriate permissions the ability to trust an entire town at once. This is envisioned to greatly supplement servers which use war modes which have true conquering of towns, as nation level permissions can often become messy.
____
New permission nodes:
`towny.command.town.trusttown`
`towny.command.townyadmin.town.trusttown`
New commands:
`/t trusttown add *townname*`
`/t trusttown remove *townname*`
`/t trusttown list`
`/ta *townname* trusttown add *townname*`
`/ta *townname* trusttown remove *townname*`
`/ta *townname* trusttown list`
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that …
> TrustTown command

- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- src/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
> Prevent falling blocks from being launched into towns

- src/com/palmergames/bukkit/towny/command/BaseCommand.java
- src/com/palmergames/bukkit/towny/command/NationCommand.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
The sender variable is now properly passed through all methods instead of referencing a field, this prevents the sender changing in the middle of a confirmation just because someone ran /ta for example.
Also fixes a bunch of places where player was used without checking if it was null or not, more commands can be used by console now.
____
____
____
> Remove townyadmin's getSender()

- src/com/palmergames/bukkit/towny/huds/HUDManager.java
Sets the player's scoreboard to the main scoreboard instead of an empty new one so that players don't need to relog to reset it.
____
> Set to main scoreboard when toggling hud off

- src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
Removes an old workaround for a glitch related to powdered snow keeping grass snowy, was fixed by Paper back in february.
____
____
____
> Remove old powdered snow workaround

- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
> Replace deprecated getPassenger

- src/com/palmergames/bukkit/towny/ChunkNotification.java
- src/com/palmergames/bukkit/towny/command/PlotCommand.java
- src/com/palmergames/bukkit/towny/event/asciimap/WildernessMapEvent.java
- src/com/palmergames/bukkit/towny/huds/MapHUD.java
- src/com/palmergames/bukkit/towny/object/WorldCoord.java
- src/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java
- src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
WorldCoord#getTownyWorld no longer throws a NRE as of last february, so the getTownyWorldOrNull was doing the exact same thing.
____
____
____
> Deprecate redundant WorldCoord#getTownyWorldOrNull method

- resources/lang/en-US.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
____
- New Config Option: global_town_settings.outsiders_prevent_unclaim_townblock
- If set to true, Towny will prevent a townblock from being unclaimed while an outsider is within the townblock's boundaries.
- When active this feature can cause a bit of lag when the /t unclaim command is used, depending on how many players are online.
____
____
> Outsiders can prevent unclaiming.

- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
HangingBreak method gets broken down and more readable.
- Probably properly handling cancelling hanging entities that are attached to blocks which have been broken by a reverted block-explosion.
Projectile Hit Event listeners get combined into one, we start protecting against non-player hits in towns.
____
____
____
> Refactor TownyEntityListener hangingbreak and projectilehit event handlers.

- src/com/palmergames/bukkit/towny/TownyUniverse.java
Changes it so the server will wait for up to 30 seconds for the backup task to finish when shutting down.
____
____
Closes #6411 
____
> Add a 30 second timeout for backup future

- resources/lang/en-US.yml
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/tasks/TownClaim.java
- src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java
The AreaSelectionUtil could not account for larger radii being supplied from within an already claimed space.
ex: /t claim 5 and then /t claim 6,
on the 2nd usage, it would think it would require all 6 layers of TownBlocks available to claim.
This PR removes the available aspect of the selection, which means it will just pass a selection and the incorrect TownBlocks are filtered out afterwards (as you see done in the TownCommand.
This also takes outpost-selecting out of the util.
This also redoes a fair number of the filtering methods to use Streams.
Fixes a missing feedback message when `/t unclaim all` is used.
____
____
Closes #6431.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright …
> Make area selection tool able to handle already claimed plots.

- resources/ChangeLog.txt
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/event/teleport/UnjailedResidentTeleportEvent.java
- src/com/palmergames/bukkit/towny/utils/JailUtil.java
- src/com/palmergames/bukkit/towny/utils/SpawnUtil.java
```
- New Config Option: jail.unjailed_players_get_teleported
- Most types of unjailing result in a player being teleported when they are freed.
- Setting this to false will prevent that teleporting, resulting in the player not being teleported when they are freed.
- API: Added UnjailedResidentTeleportEvent.
- Lets other plugins move unjailed residents to a location of their choice, or cancel the teleport altogether.
```
____
____
Closes #6437.
____ …
> Config and API options for handling unjailed player teleports.

- src/com/palmergames/bukkit/towny/object/TownyInventory.java
Fixes a selection gui being opened with a null selection type when a player clicks the back item in a non-selection gui.
____
> Fix NPE when clicking back button in a non-selection gui

- src/com/palmergames/bukkit/towny/command/PlotCommand.java
- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- src/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java
- src/com/palmergames/bukkit/towny/regen/WorldCoordEntityRemover.java
- src/com/palmergames/bukkit/towny/regen/WorldCoordMaterialRemover.java
- src/com/palmergames/bukkit/towny/tasks/RepeatingTimerTask.java
Puts a hard cap of 10 WorldCoords that can have their Materials and Entities removed. (10 for Materials and 10 for Entities.)
Deprecates the methods in TownyRegenAPI for new classes WorldCoordMaterialRemover and WorldCoordEntityRemover.
This has the benefit of making TownyRegenAPI less cluttered and also being able to replace mentions about IDs with Materials (IDs are no longer used to describe MC blocks.)
____
____
____ …
> Put limits on how many unclaimed townblocks can have their material/entity deletions run at once.

- resources/lang/en-US.yml
- src/com/palmergames/bukkit/towny/command/PlotCommand.java
- src/com/palmergames/bukkit/towny/tasks/PlotClaim.java
Removes the logic for buying a plot back to the town when a mayor runs /plot claim on an owned plot that isn't for sale in favour of the better /plot evict command. The buyback functionality was already broken for a while since plots that aren't for sale are filtered out before the claim process starts.
____
> Remove /plot claim repossesion logic in favour of /plot evict

- src/com/palmergames/bukkit/towny/tasks/TownClaim.java
/ta unclaim provides a null town which causes an NPE when trying to save it.
____
> Fix /ta unclaim causing an NPE

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
- src/com/palmergames/bukkit/towny/tasks/ResidentPurge.java
____
Adds resident_settings.delete_old_residents.only_remove_town
Default: false
When true players will be removed from their town and become a nomad instead of being fully deleted.
____
Closes #6506
____
> Add remove town only option to resident purge

- resources/plugin.yml
A long time ago plugins were no longer allowed to use spaces in names. It appears that Towny still soft-depends on my plugin MyWorlds with the space in the name, even though this was replaced with _ a long time ago.
This small PR fixes that issue, so that MyWorlds loads before Towny.
It's unsure if soft-depending on "My Worlds" will still properly make "My_Worlds" load before. At least with recent Paper plugin loading changes, its doubtful.
____ …
> Update plugin.yml to use the proper name for MyWorlds

- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- src/com/palmergames/util/FileMgmt.java
Changes the date format used for backup file names to iso 8601 and removes having the full timestamp part of the file name by using the DateFormat#parse method to get the time as a long.
____
> Change format used for backup file names

- src/com/palmergames/bukkit/towny/object/economy/BankAccount.java
- src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
Bankrupt towns' balances would return a negative amount when a nation had % tax enabled.
This called the payTo() function with a negative amount for the collector which then hits Vault with a negative deposit (which we are warned not to do.)
Solution:
Don't pay a nation tax if the amount is less than or equal to zero.
Also added is an override to BankAcount for canPayFromHoldings() that tests if a town is able to pay with debt.
____
____
Closes #6540.
____ …
> Make sure we aren't paying negative amounts to a Nation bank account during tax time.

- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/db/DatabaseConfig.java
- src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Adds an option that allows MySQL users to disable the warning that's shown when a backup is made.
____
> Add an option to disable the mysql backup warning

- src/com/palmergames/bukkit/towny/command/InviteCommand.java
- src/com/palmergames/bukkit/towny/invites/Invite.java
- src/com/palmergames/bukkit/towny/object/inviteobjects/AbstractInvite.java
Fixes invite objects holding a reference to a CommandSender which can cause the internal ServerPlayer to stick around
Should also make invite persistence across restarts easier to do, since we no longer need the CommandSender instance but just the name & uuid.
____
> Fix invite objects holding a reference to command senders

- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/listeners/TownyVehicleListener.java
____
```
- New Config Option: protection.mob_types_protected_from_boat_theft
- When set to true, the above mob_types will be protected when they are in a town, from being able to enter empty boats.
- This protects the mobs from being stolen using boats.
```
____
Closes #6554 
____
> Add option to stop protected mobs from entering empty boats in Towns.

- src/com/palmergames/bukkit/towny/object/WorldCoord.java
Fixes it returning too many chunks on townblock sizes greater than 16. Previously, with a townblock size of 32 (which perfectly fits inside 2x2 chunks) you'd get 9 chunks returned.
____
> Fix WorldCoord#getChunks sometimes being wrong

- src/com/palmergames/bukkit/towny/object/economy/Account.java
> Make account a bit smarter

- resources/lang/en-US.yml
- resources/plugin.yml
- src/com/palmergames/bukkit/config/ConfigNodes.java
- src/com/palmergames/bukkit/towny/TownySettings.java
- src/com/palmergames/bukkit/towny/command/TownCommand.java
- src/com/palmergames/bukkit/towny/event/TownClaimEvent.java
- src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
- src/com/palmergames/bukkit/towny/object/Town.java
- src/com/palmergames/bukkit/towny/object/TownyWorld.java
- src/com/palmergames/bukkit/towny/object/WorldCoord.java
- src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
- src/com/palmergames/bukkit/towny/tasks/TownClaim.java
- src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java
- src/com/palmergames/bukkit/towny/utils/OutpostUtil.java
Adds WorldCoord#canBeStolen
Adds new config option allowing over-claimed town (ie 120/100 townblocks) to have their land taken from them.
- Config option explains that outposts should be disabled, a number of adjacent townblocks > 1 should be set.
- Does not work on outposts, or when new towns are being made.
Adds new config option setting the price of taking over a claim.
Adds new `/t takeoverclaim` command that initiates stealing a single townblock.
Adds warning messages 
- claiming that approaches the limit (and when losing a resident would put you in real danger.)
- logging in while overclaimed.
- losing a resident that puts you into overclaimed status.
Deprecates a couple of TownyWorld distance checks and replaces them with new methods with better names.
- …
> Allow overclaimed towns to have their land stolen from them.

- src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
Fixes an exception when a non-player entity causes an EntityChangeBlockEvent using a splash potion on a non-campfire block. Also improves the protection by adding a check for dispensers using BorderUtil.
____
> Make campfire water bottle protection a bit better

- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- Towny/src/main/resources/plugin.yml
Adds a new permission node that server admins can use to prevent players from inviting/uninviting multiple players at once.
____
> Add new perm node for inviting multiple residents

- Towny/pom.xml
- Towny/src/main/java/com/palmergames/util/StringMgmt.java
- Towny/src/test/java/com/palmergames/bukkit/towny/test/text/HexConversionTests.java
Fixes minimessage gradient tags with hex colors being mistakenly converted from \<gradient:#hex1:#hex2> to <gradient:<#hex1>:<#hex2>> by tweaking our hex regex pattern to not consider #aaaaaa valid for converting.
____
Closes #6291
____
> Fix hex gradients with minimessage not working

- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TeleportRequest.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/SpawnUtil.java
These fields are only ever used for online residents who want to teleport, so moving them away will probably reduce the used memory at least a bit. All the different variables used for a teleport are now stored together so that there's also a smaller likelyhood of it entering an invalid state.
____
> Remove teleport related fields from Resident

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyTimerHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/HealthRegenTimerTask.java
Fixes some tasks that used to be async pre-folia now being sync, also makes the health regen task more safe on folia by running it on the player's region thread.
____
> Fix previously async timers tasks being sync

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyUniverse.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java
An issue exists, where some MySQL servers are having their worlds take on default settings during the loading process, I believe this PR solves that problem, introduced in 0.98.6.4 with https://github.com/TownyAdvanced/Towny/pull/6377/
____
____
____
> Fix world settings being wiped on load.

- Towny/src/main/java/com/palmergames/bukkit/towny/hooks/TownyPlaceholderExpansion.java
* Fixes #6703:
* Whenever the placeholder `player_location_plot_name` is used inside a Plot Group, and the individual plot has no name, it displays the Plot Group's name instead.
____
* None
____
* #6703 
____
> Fallback to Plot Group name when Plot has no name

- Towny/src/main/java/com/palmergames/bukkit/towny/utils/MoneyUtil.java
The hasAccount call wasn't being done on the right thread if the async_economy option was set to false, this PR just changes it to run the entire task on the economy executor and additionally saves the town after a conversion.
____
> Fix legacy debt converter not respecting isEconomyAsync

- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DrawSpawnPointsTask.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/HealthRegenTimerTask.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java
Starts/stops the timers when the config option changes after a config reload, so that the value of the option always matches the state of the task.
____
> Add reload listeners to some timer tasks

- Towny/src/main/java/com/palmergames/bukkit/towny/command/InviteCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlockTypeHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Translation.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TranslationLoader.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/comparators/ComparatorCaches.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/Account.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/metadata/MetadataLoader.java
- Towny/src/main/java/com/palmergames/bukkit/towny/permissions/TownyPerms.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/ProtectionRegenTask.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/ResidentUtil.java
- Towny/src/main/java/com/palmergames/bukkit/util/NameValidation.java
- Towny/src/main/java/com/palmergames/util/FileMgmt.java
Changes all of our uses of printStackTraces to use our logger instead, and removes some redundant catches entirely. The benefit of this is so that stacktraces can easily be attributed back to us, which services like sentry use.
____
> Replace all printStackTraces with the logger

- Towny/src/main/java/com/palmergames/bukkit/towny/object/AbstractRegistryList.java
- Towny/src/main/java/com/palmergames/bukkit/util/ItemLists.java
Also changes the existing `withTag`s to use a constant from bukkit's Tag class.
____
> Add new excludeTag method

- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Adds a check to our editing/waxing protection for signs to prevent the event from being cancelled if the sign is already waxed. The reason we're not just using spigot's isEditable method is because it only returns true if the sign is not waxed and there is a player actively editing the sign.
____
> Use paper's isWaxed API for signs

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/hooks/TownyPlaceholderExpansion.java
```
- New Placeholders:
- %townyadvanced_top_town_balance_n% - (Replace n with a number) Displays the nth Town by money in the town bank.
- %townyadvanced_top_town_residents_n% - (Replace n with a number) Displays the nth Town by number of residents.
- %townyadvanced_top_town_land_n% - (Replace n with a number) Displays the nth Town by number of townblocks claimed.
- New Config Option: filters_colour_chat.papi_leaderboard_formatting.format"
- Default: "%s - %s",
- How the %townyadvanced_top_....% placeholders will appear, first %s being the town name, with the second being the balance, resident count or town size.
```
PlaceholderExpansion class gets a private getMoney() method to reduce code.
____
____
Closes #5073.
____
By making this pull request, I represent that I have the right to …
> Add Town leaderboard PAPI Placeholders

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/SpawnUtil.java
____
```
- New Config Option: global_town_settings.allow_enemies_spawn_to_peaceful_towns
- When true, players will be allowed to spawn to peaceful/neutral towns in which they are considered enemies.
- Setting this to true will make town spawn points unsafe for private towns which are part of nations with enemies.
```
____
Closes #6401.
____
> Add option to allow enemies to spawn to neutral/peaceful towns.

- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- Towny/src/main/java/com/palmergames/bukkit/util/ItemLists.java
Instead of modifying the existing sign tag, vanilla instead added a new all_signs tag which made our tests not catch hanging signs. The signs itemlist already contained hanging signs via the endsWith but also has the all_signs tag now just in case.
____
Closes #6780
____
> Fix hanging signs not being edit protected

- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
The player field is never reassigned so having it as volatile seems a bit useless, at least from my understanding of it
____
> Remove useless volatile keyword in OnPlayerLogin

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/config/migration/WorldMigrationAction.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/executors/TownyActionEventExecutor.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyInventoryListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyVehicleListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlockData.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlockTypeHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyWorld.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/gui/EditGUI.java
- Towny/src/main/java/com/palmergames/bukkit/towny/regen/NeedsPlaceholder.java
- Towny/src/main/java/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/CombatUtil.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/EntityTypeUtil.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/ResidentUtil.java
- Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java
- Towny/src/main/java/com/palmergames/bukkit/util/EntityLists.java
- Towny/src/main/java/com/palmergames/util/JavaUtil.java
- Towny/src/main/resources/config-migration.json
This PR makes some changes required for the upcoming removal of various Bukkit enums, most notably material & entitytype.
Since some methods were returning EnumSets, we do have some breaking changes unfortunately. Mainly in TownyWorld and TownySettings, I've changed some return types and parameter types to Collection to avoid breakage if we ever change the impl again.
Also fixes an issue with large fireballs left over from when we were doing entity types with class names.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the …
> Bukkit enum eradication futureproofing

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyMessaging.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/permissions/TownyPermissionSource.java
Allows admins to have both towny.admin permissions while still negating some specific permissions.
Also removes a weird '-'-prefixed permission check being done, was likely just an artifact of the past.
____
Closes #6543 (no longer needed)
____
> Make explicitly false nodes bypass towny admin check

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TownClaim.java
- Towny/src/main/resources/lang/en-US.yml
````
- Add new options to the overclaiming feature:
- A configurable cooldown between using /t takeoverclaim.
- A configurable age requirement to prevent new towns using /t takeoverclaim.
- Closes #6734.
- New Config Option: town.overclaiming.town_age_requirement
- Default: 7d - When in use, requires that a town be of a minimum age in order to overclaim another town. This prevents new towns being made just to overclaim someone.
- Default is for 7 days.
- New Config Option: town.overclaiming.command_cooldown 
- Default: 0m 
- When in use, requires an amount of time to pass before the /t takeoverclaim command can be used again.
````
____
____
Closes #6734.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree …
> New overclaiming restrictions/features.

- Towny/pom.xml
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
The latest spigot builds now have an isWaxed method, so reflection is no longer needed for it.
____
> Remove reflection for isWaxed method

- Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java
\W is equivalent to [^a-zA-Z0-9_] which doesn't include the : character, so if we passed minecraft:creeper to it it'd change that to minecraftcreeper which is obviously not a valid name.
____
> Fix matchRegistry filtering out ':'

- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java
Return null early if the filtered key is empty, not sure if the wild regen entities being empty is due to a different issue but this fixes part of it at least.
____
> Fix exception being thrown for empty key

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java
Uses a paper specific method to allow us to check an entity's spawn reason outside the actual creature spawn event, there's currently a bug in Paper where summoned entities have a spawn reason of DEFAULT but that will be fixed soon.
____
New config option: protection.town_mob_removal_ignored_spawn_causes
Default: "" (none)
A comma seperated list of spawn causes, if an entity has a spawn cause that is in this list they will not be removed by town mob removal.
For the list of valid spawn causes, see https://jd.papermc.io/paper/1.20/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
Due to technical reasons, this setting only works on Paper servers.
____
Closes #6832
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my …
> Add ignored entity spawn reason option

- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
Because we're setting a townblock's type before the resident, while loading most of the plot types are choosing the permission line of the town, when the changed flag is also false.
____
____
Closes #6856 
____
> Fix personal permission line loading in TownBlocks.

- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
There are occasions where plugins will cancel one of the above aspects of the PlayerInteractEvent without cancelling the event as a whole.
Because we were specifically calling for the event to be uncancelled we were overriding previously set use-item and interact-with-block decisions made by other plugins.
This PR has Towny ~~making setUseItemInHand and setUseInteractedBlock decisions rather than fully uncancelling/cancelling events.~~ only cancelling events when we're actually denying it. We will no long setCancelled(false) when players are allowed to do their actions.
.
____
____
Closes #6861
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are …
> Fix Towny uncancelling PlayerInteractEvents.

- Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java
The actual matchRegistry doesn't have this second replace, no idea where I got it from. This prevents us from removing valid namespace/key characters like - and /. If the input contains invalid characters then the fromString method will just silently fail by returning null.
____
> Remove unneeded filtering from matchRegistry

- Towny/pom.xml
- Towny/src/main/java/com/palmergames/bukkit/towny/object/AbstractRegistryList.java
- Towny/src/test/java/com/palmergames/bukkit/towny/test/RegistryListTests.java
Adds a (very simple) test for the registry list add method, can't think of what else we would test since we'd need to alter our expected values every update which is probably not ideal.
Currently fails because of #6866
____
> Add testing for registry lists

- Towny/src/main/java/com/palmergames/bukkit/towny/utils/CombatUtil.java
Sentinel could cause Towny to throw events that assume a player is involved, but the lack of a backing Resident can cause issues for plugins using our events.
This change should result in non-player-involved damage events being thrown instead.
____
____
https://mclo.gs/brb2gHd
____
> Fix edge case scenario where NPCs can be treated like Players in Combat. 

- Towny/src/main/java/com/palmergames/bukkit/config/CommentedConfiguration.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/util/FileMgmt.java
> Use constant for line separator string

- Towny/src/main/java/com/palmergames/bukkit/config/migration/RunnableMigrations.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyWorld.java
- Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java
- Towny/src/main/java/com/palmergames/util/StringMgmt.java
- Towny/src/main/resources/config-migration.json
- Towny/src/test/java/com/palmergames/bukkit/towny/test/ConfigMigrationTests.java
- Towny/src/test/java/com/palmergames/bukkit/towny/test/EntityTypeConversionTests.java
- Towny/src/test/java/com/palmergames/bukkit/towny/test/RegistryListTests.java
* Moved the entity class name migration done inside setPlotManagementWildRevertEntities to a one time migration
* Added a switch case with all old entity names so that these can still be looked up correctly
* Fixes unclaimDeleteEntityTypes saving using EntityType enum names instead of keys 
____
> Fix all the weirdness around world entity key loading

- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
The methods are named exactly the same so it's only the class name that matters here. the paper event is preferred over spigot's event
____
> Add spigot fallback to sign open event

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/plot/toggle/PlotToggleTaxedEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlock.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
- Towny/src/main/resources/lang/en-US.yml
Adds `Plot Tax:` to the townblock status screen.
API: PlotToggleTaxedEvent
- Cancellable event that stops a mayor toggling taxation off/on on a townblock.
____
New Command: /plot toggle taxed
- Uses the towny.command.plot.asmayor permission node
- Allows a mayor to decide whether a plot will require the plotowner to pay the plot taxes.
____
Closes #3675.
____
> Add ability for mayors to exempt their townblocks from paying taxes.

- Towny/src/main/java/com/palmergames/bukkit/towny/object/Position.java
> Replace lang3 validate with guava

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Government.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Nation.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
- Towny/src/main/java/com/palmergames/util/MathUtil.java
- Towny/src/main/resources/lang/en-US.yml
____
```
- New Config Option: economy.daily_taxes.allow_negative_town_tax
- If enabled, and a town tax is set to a negative amount and is a fixed amount (not percentage,) it will result in every resident being paid by the town bank (if the town can afford it.)
- New Config Option: economy.daily_taxes.allow_negative_nation_tax
- If enabled, and a nation tax is set to a negative amount and is a fixed amount (not percentage,) it will result in every town in the nation being paid by the nation bank (if the nation can afford it.)
```
____
Closes #6705.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I …
> Add ability for towns and nations to have a negative fixed-rate tax amount.

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/ResidentCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
Adds a new config option for the resident about section, similar to nation/town statuses. The about is only saved if it's non-default, so that if the value in the config changes, then the message shown in /res will too (after the next database reload).
____
New config node: resident_settings.default_about
Default: /res set about [msg]
The default resident about text, shown in the resident's status screen.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md …
> Make the default resident about configurable

- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Coord.java
- Towny/src/main/java/com/palmergames/bukkit/towny/permissions/TownyPerms.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java
- Towny/src/main/java/com/palmergames/util/JavaUtil.java
- Fixed 1.16/1.17 compat
- Added forward compat for if PotionEffectType#getName ends up changing
- Added a listener for paper's dragon fireball hit event to discard it as soon as it hits in a townblock with pvp off
- Optimized the code that checks whether to discard detrimental effect clouds to reduce the amount of checks
____
____
____
> Area effect cloud protection improvements

- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
A recent commit made it so that we actually act upon a resident removing their town fulfilling the EmptyTownException. 
____
____
____
> Fix towns being deleted causing a second (pointless) town deletion when the last resident is removed.

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyMessaging.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/ResidentCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- Towny/src/main/resources/lang/en-US.yml
- Towny/src/main/resources/plugin.yml
This PR makes it possible to see a list of plots owned by a player, and their location, town, plottype and plot name.
When an admin uses the command, they also get hoverable/clickable lines which runs the /ta tpplot {worldname} {x} {z} command, allowing them to teleport easily to a player's plots.
____
New Permission Node: towny.command.resident.plotlist
New Command: /res plotlist {#} - Shows a player their own list of plots, with an optional page number.
New Command: /res plotlist [name] {#} - Shows a a list of plots for the given player name, with an optional page number.
____
Closes #7075
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are …
> Add /res plotlist Command

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Nation.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/ProximityUtil.java
- Towny/src/main/resources/config-migration.json
Optionally, towns in a nation can grant nearby towns the ability to bypass the proximity-to-the-nation-capital value.
Also Optionally, there can be a hard-cap on how far a town can be from the nation capital, even when a nation-town is nearby, preventing nations going "wide."
Renames/moves the config settings into the Global Nation Settings section & migrates old configs' settings.
Adds a new ProximityUtil where all the heavy lifting is done.
Spruced up the code in the various methods that used the proximity settings.
____
```
- Moved Config Option: global_town_settings.nation_requires_proximity -> global_nation_settings.proximity.nation_proximity_to_capital_city
- Your config's setting value will be transferred to the new location.
- New Config Option: …
```
> Enhance Nation Requires Proximity Feature

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyEconomyHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/BaseCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/ResidentCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/confirmations/ConfirmationHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/confirmations/ConfirmationTransaction.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/TownRuinUtil.java
Alter ConfirmationTransaction to no longer take in an Account in the constructor, instead it takes in a TownyObject, which will resolve an account. This prevents errors when non-Economy-enabled servers attempt to create a Confirmation with a cost set on it.
Make TownyEconomyHandler#getFormattedBalance able to handle returning a formatted balance when the Economy is not active.
Add prettyMoney method to BaseCommand, use it throughout the command classes to make things look cleaner.
____
____
____ …
> Make Towny more resiliant to errors which come from having no Economy present on the server.

- Towny/src/main/java/com/palmergames/bukkit/towny/command/HelpMenu.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/nation/NationSanctionTownAddEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/nation/NationSanctionTownRemoveEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Nation.java
- Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- Towny/src/main/java/com/palmergames/bukkit/util/NameValidation.java
- Towny/src/main/resources/lang/en-US.yml
- Towny/src/main/resources/plugin.yml
____
```
- New Command: /nation sanctiontown
- add [Townname] - Adds a town to the sanctioned town list.
- remove [Townname] - Removes a town from the sanctioned town list.
- list - Lists your nation's sanctioned towns.
- New Command: /ta nation [nationname] sanctiontown
- add [Townname] - Adds a town to the sanctioned town list.
- remove [Townname] - Removes a town from the sanctioned town list.
- list - Lists the nation's sanctioned towns.
- New Permission Node: towny.command.nation.sanctiontown
- Allows adding/removing sanctioned towns, a child node of towny.command.nation.*.
- No townyperms.yml change is required.
- New Permission Node: towny.command.townyadmin.nation.sanctiontown
- Allows admins to add/remove sanctioned towns from a given nation, a child node of …
```
> Add the ability for nations to sanction towns, preventing them from joining the nation via invite or join.

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyUniverse.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLTask.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
Fixes a minor memory/connection leak when using mysql, the load datasource is now properly shut down when it's no longer needed and re-used if possible. By re-using it we also avoid doing some double work, such as all the tables being checked & altered, which saves a bit of time.
____
> Seperate the load and save data sources

- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/TownClaimEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/town/TownUnclaimEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TownClaim.java
Adds a boolean to check if a claim/unclaim resulted from `/t takeoverclaim` to the respective events
____
N/A
____
N/A
____
> Add an isOverClaim property to TownClaimEvent and TownUnclaimEvent

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyAPI.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TownClaim.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/ProximityUtil.java
Adds TownyAPI methods to give other plugins an easy way to determine if a town can claim or unclaim an area.
```
testTownClaimOrThrow(Town town, WorldCoord coordToClaim, boolean outpost, boolean newTown)
testTownUnclaimOrThrow(Town town, WorldCoord coordToUnclaim)
```
Moves responsibility for more of the distance code out of the TownCommand into the ProximityUtil.
Closes #6004.
____
____
____
> Add method to ProximityUtil to determine ability to claim land,

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
Takes care of a loophole that would let merging towns farm bonus townblocks.
____
```
- New Config Option: claiming.new_town_bonus_claims
- Default: 0
- An amount of additional townblocks that a town will receive when it is first created, in addition to any amount given via the town_block_ratio or town_levels.
- As an example: This can be used to add 10 townblocks to a town when it is made so the borders can be grown a bit more before the mayor has to seek out residents.
```
____
Closes #7195.
____ …
> Add a configurable amount of bonus townblocks given to new towns.

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
- Towny/src/main/resources/lang/en-US.yml
This adds a "[Sanctioned Towns]" section to the end of the nation status screen, it acts just like the enemies, allies, towns etc. hover components, clicking runs the list command (pictured below)
____
N/A
____
N/A
____
> Add sanctioned towns hover component to nation status screen

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/hooks/LuckPermsContexts.java
Add the `towny:nation_resident` LuckPerms context. This is the nation equivalent of already existing resident LuckPerms context.
____
No new permission nodes.
____
No relevant issues.
____
> Add nation_resident LuckPerms context

- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java
PotionEffectType has implemented Keyed since around 1.18 and not 1.20.3, but with this approach we shouldn't need any version checks for it at all
____
> Remove version check from potion effect name method

- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyServerListener.java
Bukkit's plugin loader class is deprecated on paper, PluginManager#disablePlugin is the intended way to disable plugins now
____
> Replace deprecated plugin loader with manager

- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
> Fix comod error when removing all sent invites

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyWorld.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/ProtectionRegenTask.java
Prevents wilderness explosions from overwriting newly placed blocks, ie chests inside of creeper holes.
____
```
- New Config Option: new_world_settings.plot_management.wild_revert_explosions_blocks_to_not_replace
- Default: ""
- This section is applied to new worlds as default settings when new worlds are detected.
- This is the list of blocks that should not be overwritten by wilderness explosion reverts.
- (if empty all blocks placed into regenerating explosions will be overwritten with the original pre-explosion blocks.)
- This list is useful if you have a death chest plugin which could put a player's inventory inside chest that is inside of a regenerating creeper explosion pit.
- For Example: By putting CHEST here you can prevent the chest from being overwritten by the dirt block …
```
> Add do-not-overwrite block list to worlds that affects wilderness explosion reverts.

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyTimerHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/SpawnPoint.java
Calculates the offsets for the points in spawn point circles instead of using precalculated values, the benefit of this is that it's easier to see what it's doing and makes it easier to make changes to it. Due to imprecision the offsets won't be exactly the same but the difference isn't significant
____
> Remove magic values from spawnpoint ring offsets

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/resources/config-migration.json
Having the on/off toggle for all economy related things in the economy section seems more logical
____
> Move using_economy to the eco section of the config

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
- Towny/src/main/resources/lang/en-US.yml
Something I've wanted to do for a while, removes sending players the message about their locale being used since it's not very relevant for the average player
____
> Remove locale message on first join

- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
Currently broken because MethodHandle is always null for the getPlayer...
```
[11:29:35 WARN]: [Towny] An exception occurred while invoking com.destroystokyo.paper.event.player.PlayerElytraBoostEvent#getPlayer reflectively
java.lang.NullPointerException: Cannot invoke "java.lang.invoke.MethodHandle.invoke(org.bukkit.event.player.PlayerEvent)" because "com.palmergames.bukkit.towny.listeners.TownyPaperEvents.GET_BOOSTING_PLAYER" is null
at com.palmergames.bukkit.towny.listeners.TownyPaperEvents.lambda$playerElytraBoostListener$1(TownyPaperEvents.java:122) ~[towny-0.100.1.18.jar:?]
at com.palmergames.bukkit.towny.listeners.TownyPaperEvents.lambda$registerEvent$0(TownyPaperEvents.java:114) ~[towny-0.100.1.18.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) …
```
> Add listener for Paper's PlayerElytraBoostEvent.

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/HelpMenu.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlock.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java
- Towny/src/main/java/com/palmergames/util/TimeTools.java
- Towny/src/main/resources/lang/en-US.yml
Limits who can claim plots in towns, based on their join date, allowing mayors to set aside land for new players or old players.
Does not affect embassy plots.
____
New Command: /plot set minjoindays {number|clear}
New Command: /plot set maxjoindays {number|clear}
____
Closes #7164.
____
> Add MinJoinDays and MaxJoinDays to TownBlocks

- Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
- providers/BaseProviders/src/main/java/com/palmergames/bukkit/towny/scheduling/TaskScheduler.java
- providers/BaseProviders/src/main/java/com/palmergames/bukkit/towny/scheduling/impl/BukkitTaskScheduler.java
- providers/FoliaProvider/src/main/java/com/palmergames/bukkit/towny/scheduling/impl/FoliaTaskScheduler.java
- providers/PaperProvider/src/main/java/com/palmergames/bukkit/towny/scheduling/impl/PaperTaskScheduler.java
Replaces runnable params with consumers for cases where we'd want to get the task from inside itself.
The run, runLater and runRepeating on methods on folia will also now use the async scheduler by default since there was no reason for them to use the global one, new runGlobal methods have been added for things that actually do need to run on the global thread (currently none)
____
> Add consumer methods to the task scheduler

- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/BankAccount.java
> Fix deleted town/nation bank refund duplication

- Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/TownUtil.java
- Towny/src/main/resources/lang/en-US.yml
Uses the nation.exists to determine if the removal of the nation was successful or not, and displays messages to match the outcome.
____
____
Closes #7380.
Supercedes #7381.
____
> Fix nation deleted message showing when a predeletenationevent is cancelled.

- Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlock.java
> Allow setting a default plot price of -1

- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Dragon eggs currently teleport when an untrusted player left clicks on them (though right click is properly protected). This adds a check for dragon egg left clicks under switching protection to prevent players from teleporting the eggs.
____
N/A
____
N/A
____
> Fix dragon egg teleportation on left click

- Towny/pom.xml
Since we don't do any intensive reflection into internals, the plugin doesn't need any remapping done, setting the manifest entry prevents that.
Also some other general pom file maintenance:
- Removed exclusion for the bukkit api from vault api, 1.7.1 no longer exposes it
- Removed commons text, we don't use it anywhere
- Changed inclusions to exclusions in the shade plugin
- Added transformers to the shade plugin
- manifest transformer: makes sure that our manifest.mf ends up in the final jar
- apache license transformer: prevents apache licenses from ending up in our manifest
- apache notice transformer: combines notices together into one NOTICE file
____
By making this pull request, I represent that I have the right to …
> Set mappings namespace in manifest

- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
> Go into safemode if no sql connection could be made

- .github/CONTRIBUTING.MD
- Towny/pom.xml
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/confirmations/ConfirmationHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/hooks/LuckPermsContexts.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/AddonCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/CellSurface.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/ChangelogResult.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/SpawnPoint.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TeleportWarmupParticle.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlockTypeHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TranslationLoader.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/BorderUtil.java
- Towny/src/main/java/com/palmergames/util/FileMgmt.java
- Towny/src/test/java/com/palmergames/bukkit/towny/object/CommandListTests.java
- pom.xml
- providers/BaseProviders/pom.xml
- providers/FoliaProvider/pom.xml
- providers/PaperProvider/pom.xml
The majority of servers have already updated their java version to 17 since it's been the minimum version for 2+ years now (since 1.18), so it seems overdue to update to java 17 ourselves aswell.
The main reason I am making this now is because jabel 1.0.0 is incompatible with java 21, which is required for 1.20.5 to run, and version 1.0.1 of jabel is not published anywhere official.
____
> Raise java version to 17

- Towny/src/main/java/com/palmergames/bukkit/towny/object/WorldCoord.java
This PR fixes `WorldCoord#unloadChunks` adding plugin chunk tickets instead of removing them, which was causing chunks loaded by TownyRegenAPI to stay loaded indefinitely.
I closed the previous PR as it contained unrelated commits.
____
____
____
> Fix WorldCoord#unloadChunks adding plugin chunk tickets

- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
> Handle empty towns during duplicate resident removal

- Towny/src/main/java/com/palmergames/bukkit/towny/object/PlotGroup.java
This PR adds a null check to `PlotGroup#getTownBlocks` and `PlotGroup#hasTownBlock` like the other methods in the class. This fixes these methods throwing NPEs if the `townBlocks` field has not yet been initialised.
____
____
____
> Fix potential NPEs in PlotGroup

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
Just a redaction error fixment
____
____
____
> Fixed typo

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyEconomyHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/economy/BankTransactionEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/economy/NationPreTransactionEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/economy/NationTransactionEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/economy/TownPreTransactionEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/economy/TownTransactionEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/economy/TownyPreTransactionEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/event/economy/TownyTransactionEvent.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/EconomyAccount.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Government.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Transaction.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TransactionType.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/Account.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/BankAccount.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/BankTransaction.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/GovernmentAccountAuditor.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/TownyServerAccount.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/TownyServerAccountEconomyHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/transaction/Transaction.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/transaction/TransactionBuilder.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/transaction/TransactionType.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/MoneyUtil.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/SpawnUtil.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/TownRuinUtil.java
Deprecates the original Transaction and creates a new Transaction class in its own package within the `object.economy` package.
The new Transaction uses a amount, TransactionType and two accounts (sender and receiver.) Transactions are made using a factory pattern which makes it clearer who is paying and who is being paid. This builder can create Transactions as well as TownyTransactionEvents (for which Transactions are usually being used.)
Additionally, this PR makes it so that TownyTransactionEvents are thrown much more frequently, rather than only under very limited circumstances.
Additionally, this PR adds an EconomyHandler to the Account class, reducing the importance of an Account's Name field.
Additionally, this PR alters the TownyServerAccount to now also implement EconomyHandler …
> Alter Account & Transaction and fix TownyTransactionEvent.

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- Towny/src/main/java/com/palmergames/bukkit/util/ItemLists.java
____
```
- New Config Option: global_town_settings.prevent_item_degrading_in_arenas
- While true, weapons and armour items worn by players in Arena plots will not lose durability.
```
____
Closes #7549.
____
> Add the ability to stop weapons and armour degrading in arena plots.

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/SpawnUtil.java
- Towny/src/main/java/com/palmergames/bukkit/util/ItemLists.java
- Towny/src/main/resources/lang/en-US.yml
Teleport a player near a safe location when teleporting to town spawn/outpost/nation spawn, for now it only fails the teleport
____
#7463 
____
> Add safe-teleport detection to spawn points.

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
- Requires Paper for this to work.
```
- New Config Option: global_town_settings.beacons_for_allies_only
- When true, a beacon placed in a town will only affect the allies of the town. This includes residents, nation residents and allied nation residents.
- New Config Option: global_town_settings.beacons.exclude_conquered_towns
- When true, conquered towns are not considered allies.
```
____
____
- Closes #7532
____ …
> Add the ability to block non-allies gaining benefits from Beacons placed in towns.

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/CombatUtil.java
This would cause the common CombatUtil.isAlly(Town, Town) method call to return differently when a town which is conquered and a non-conquered town of the same nation are tested.
____
```
New Config Option:
global_nation_settings.are_conquered_towns_considered_allies
- While true, conquered towns will be considered a member of good standing in the nation.
- When set to false CombatUtil#isAlly() tests will treat conquered towns and their nations as not allied.
- Setting this to false could result in strange unforseen behaviour.
```
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the …
> Add experimental option to consider conquered towns as not allies.

- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
> Fix deleting objects from the SQL DB which are keyed by a UUID.

- Towny/src/main/java/com/palmergames/bukkit/towny/event/executors/TownyActionEventExecutor.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/MinecraftVersion.java
- Towny/src/main/resources/lang/en-US.yml
Adds a new listener that takes care of only WindCharge entity explosions.
- Removes blocks that are switches that cannot be used by the player.
Adds a new silent option to the isAllowedAction method, which allows Towny to suppress spammy permission tests.
Stops players using switch blocks when they're activated by wind charge explosions.
____
____
Closes #7648 
____
> Prevent wind charge exploits on switch blocks.

- .github/workflows/deploy_prerelease.yml
- .github/workflows/test.yml
- Towny/pom.xml
Allows paper-api to be included in the pom.xml (so our testing will run via MockBukkit) and still be able to deliver messages in game.
____
____
____
> Fix adventure relocation not excluding things from paper-api. 

- Towny/src/main/java/com/palmergames/bukkit/towny/TownyEconomyHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Nation.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/PlayerCache.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/SpawnPointLocation.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TeleportWarmupParticle.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlock.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyWorld.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/jail/Jail.java
- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/ProtectionRegenTask.java
- Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java
As is standard with the beginning of a new release cycle (0.101.*.*), the methods deprecated in 0.99.*.* are removed.
____
____
____
> Remove methods deprecated during the 0.99.*.* release cycle, in time for the beginning of the 0.101.*.* release cycle.

- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/HealthRegenTimerTask.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/MinecraftVersion.java
Attribute.valueOf also does not work on older versions, this fixes that using the registry
____
> Re-fix max health attribute

- Towny/pom.xml
- Towny/src/main/java/com/palmergames/bukkit/towny/object/EconomyAccount.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/Account.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/BankAccount.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/TownyServerAccount.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/adapter/VaultUnlockedEconomyAdapter.java
> Update VaultUnlocked support 2.9.0.

- Towny/src/main/java/com/palmergames/bukkit/towny/huds/MapHUD.java
Added ": " to where the String for the line that has "Owner" in /towny map hud is concatenated so that the format is correct.
____
NA
____
NA
____
> Fixed format for "Owner" in MapHUD

- jitpack.yml
Updated the Java version used by JitPack from 17 to 21. The reason for this is:
1) This fixes compilation on JitPack. The build fails while trying to compile `towny-paper-provider` due to `class file has wrong version 65.0, should be 61.0`. JitPack shows that the status is `ok`, but it only actually publishes artifacts for `towny-folia-provider`, `towny-base-providers`, and `towny-parent`. Crucially, no artifact for the `towny` module is published, as you can see in the [logs for 0.101.1.1](https://jitpack.io/com/github/TownyAdvanced/Towny/0.101.1.1/build.log).
2) This brings it in line with the version used by the Actions workflow to compile the project.
____
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, …
> Use Java 21 on Jitpack

- Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java
- Towny/src/main/java/com/palmergames/bukkit/towny/utils/SpawnUtil.java
It's possible for a teleport to not succeed (i.e. the bukkit teleport event being cancelled by another plugin), in those cases we shouldn't be firing a successful teleport event
____
> Only fire successful teleport event on successful teleport

- Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
Fixed /plot district add causing an ArrayIndexOutOfBoundsException when attempting to transfer a plot to a different district with no district name specified.
____
____
____
> Fix ArrayIndexOutOfBoundsException in /plot district add

- Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/resident/mode/ResidentModeHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- Towny/src/main/resources/plugin.yml
Allows residents to set /res toggle district, which will add any plots that they walk into to a district, as long as the resident has a district name set in memory. This is set when a resident runs /plot district add NAME.
There is now tab completion for "new" and "create" as arguments for /plot district, aligning it with the help for /plot district and the actual codebase.
____
Adds `/res toggle district` and the permission `towny.command.resident.toggle.district` for it.
Adds tab completion for "new" and "create" for /plot district.
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced …
> Add a new resident district mode and aligned tab completion for /plot district with help and codebase 

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Moves the per-outpost-cost from the front to the back when per-plot-upkeep is enabled.
____
____
____
> Fix the per_outpost_cost causing very large amount of upkeep on per_plot_upkeep-using servers.

- Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
Directly converts the outpost spawn position to a worldcoord rather than doing position -> location -> worldcoord to prevent an exception if the position doesn't have a valid bukkit world when removing it.
____
> Correctly remove bad outpost spawns in getOutpostNames

- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
The 'uuid' column is not included in a SQL statement in TownySQLSource.java at line 573 despite attempted usage of it on line 584. This causes a silent failure in a try/catch leading to a failure to correctly load Towny Worlds from our database on our server. This commit adds the missing column to the statement and has resolved the issue on our server.
____
N/A
____
N/A
____
> Fix: uuid column not being queried from db

- Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Fixes an issue I encountered where if finishTasks takes a long time to shut down, tasks in the background continue running. This causes a bunch of error spam due to new tasks being attempted to be scheduled while the plugin is already considered disabled.
____
> Shut down tasks/timers before datasource

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
This PR adds a new config option `non_public_towns_show_map_link` under the web map integration section. When enabled, it allows non-public towns to display a clickable map link in the town status screens, making it easier for players and admins to locate towns on the web map, even if the towns are private.
____
- plugin.interfacing.web_map.non_public_towns_show_map_link
- boolean
- default: false
- description: If enabled, non-public towns will show a link to their map location in the town status screen.
____
Closes #7872 
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the …
> Config option for non-public towns to show map link  #7872

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/HelpMenu.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyWorld.java
- Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- Towny/src/main/resources/lang/en-US.yml
- Towny/src/main/resources/plugin.yml
Allow server admins to toggle whether or not a user is able to be jailed while in x world
____
/tw toggle jailing
towny.command.townyworld.toggle.jailing
new_world_settings.plot_management.jailing_enabled
____
Closes https://github.com/TownyAdvanced/Towny/issues/7817
____
- [x ] I have tested this pull request for defects on a server. 
> Toggle Jailing in world | Issue #7817

- Towny/src/main/java/com/palmergames/bukkit/towny/command/BaseCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/resident/mode/ResidentModeHandler.java
- Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
- Towny/src/main/resources/plugin.yml
A new resident mode that keeps players from receiving invitations to towns.
____
New permission node: towny.command.resident.toggle.ignoreinvites
- Child node of towny.command.resident.toggle.*, no changes to townyperms.yml required.
____
____
> Add res toggle ignoresinvites.

- Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
- Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
- Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
Adds a setting in the config to make a town's town_level's index based off of the town's townblock count instead of the resident count.
____
```
- New Config Option: global_town_settings.town_level_is_determined_by_townblock_count_instead_of_resident_count
- When set to true, the town's TownLevel is determined by the number of townblocks the town owns, instead of the number of residents.
- This setting will have no effect when town_block_ratio is set to 0.
```
____
Closes #7947
____ …
> Add option to make a town's town_level determined by their townblock count, instead of resident count.

- Towny/src/main/java/com/palmergames/bukkit/towny/object/resident/mode/ResidentModeHandler.java
This PR fixes the resident mode names shown to the player in a list to now be separated by a comma and a space, instead of just a comma.
____
____
____
> Fix formatting for listing resident modes
