TownyAdvanced/Towny

src/com/palmergames/bukkit/towny/TownyMessaging.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java
Fixed point system so the attacker receives the correct amount of points. Also changed how some messages are displayed (townblock falling, mayor/king killed).
=> Fix point system and displays.

src/english.yml
Changed language file version number
=> Version change

src/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java
Changed condition to ally's can't kill from only enemies can kill.
=> Reverted a Change

src/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java, src/com/palmergames/bukkit/towny/war/eventwar/WarTimerTask.java
-Small firework at each damage
-Large firework at intervals of 10
-Creeper firework when captured
-Add tags to war spoils page at end of war
=> Fireworks!

src/com/palmergames/bukkit/towny/war/eventwar/War.java
=> Fireworks 2.0

src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java, src/english.yml
Fireworks fix (hopefully) and spoils message formatted
=> Fireworks 3.0 and War Spoils Message

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java, src/com/palmergames/bukkit/towny/war/eventwar/WarTimerTask.java
Similar to Flag War, added the option for only edge blocks to be
captured.
=> Added Edges Only Option

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/war/eventwar/TownScoredEvent.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java, src/com/palmergames/bukkit/towny/war/eventwar/WarHUD.java, src/com/palmergames/bukkit/towny/war/eventwar/WarListener.java
A scoreboard for war that can be toggled (test version). Also, score list for war only
shows towns with a score greater than zero.
=> Scoreboard + Score List

src/com/palmergames/bukkit/towny/war/eventwar/War.java, src/com/palmergames/bukkit/towny/war/eventwar/WarHUD.java, src/com/palmergames/bukkit/towny/war/eventwar/WarListener.java
This is scoreboard 2.0. The logic for creating the scoreboard has been completely changed. More information has been added, not all of it has been implemented yet though. Expect crashing when suffix length is greater than 16 (town names that are long)! Will be fixed later.
=> Scoreboard 2.0

src/com/palmergames/bukkit/towny/war/eventwar/TownScoredEvent.java, src/com/palmergames/bukkit/towny/war/eventwar/WarListener.java
=> Scoreboard 2.1

src/com/palmergames/bukkit/towny/war/eventwar/WarListener.java
=> Scoreboard 2.2

src/com/palmergames/bukkit/towny/war/eventwar/WarListener.java
=> Scoreboard 2.3

src/com/palmergames/bukkit/towny/huds/HUDManager.java, src/com/palmergames/bukkit/towny/huds/WarHUD.java, src/com/palmergames/bukkit/towny/war/eventwar/PlotAttackedEvent.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java, src/com/palmergames/bukkit/towny/war/eventwar/WarTimerTask.java, src/com/palmergames/bukkit/towny/war/eventwar/WarZoneData.java
Changes to the new heal plots during war
- new messages
- calculate health changes AFTER each player has been processed in WarTimerTask
- changed PlotAttackedEvent to be more efficient
=> War revamp

build.xml
Not really a big pull request but it makes this work again :P
=> Fix build.xml

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/english.yml, src/es-mx.yml, src/german.yml, src/spanish.yml
- Added checks to see if the target nation's mayor is an NPC or is
offline
- Fixed errors casting Resident to CommandSender for error messages
=> andrewyunt's Nation Alliances - Bug fixes + Added alliance checks

src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
First attempt failed, somehow.
Fix Attempt for : https://github.com/LlmDl/Towny/issues/2544
=> Piston Head Issue Fix Attemps #2

src/ChangeLog.txt, src/plugin.yml
- Bump for release version number. First 1.9 release version.
=> v0.91.3.0:

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/ResidentCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
The server already logs command inputs. No reason to needlessly spam things up with duplicate log entries.
Screenshot: https://gyazo.com/13f3d7df0988013b24d58b17873827db
=> Remove the annoying and useless hardcoded debug messages for [PLAYER_COMMAND]

.gitignore, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/object/TownBlock.java, src/com/palmergames/bukkit/towny/object/TownyPermission.java, src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java, src/com/palmergames/bukkit/util/BukkitTools.java, src/com/palmergames/util/KeyValueTable.java
Nothing big; My commit messages and descriptions are hopefully self-explanatory.
=> Resolve minor issues all over the project

src/ChangeLog.txt, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/event/DeletePlayerEvent.java
- Fixed Typo in ChangeLog.txt
- Added DeletePlayerEvent
- Called DeletePlayerEvent from TownyDatabaseHandler
=> Added DeletePlayerEvent

src/com/palmergames/bukkit/towny/event/NationTagChangeEvent.java, src/com/palmergames/bukkit/towny/event/TownTagChangeEvent.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Town.java
- Added NationTagChangeEvent
- Added TownTagChangeEvent
- Called TownTagChangeEvent from .setTag() method in Town
- Called NationTagChangeEvent from .setTag() method in Nation
Ends Issue # 1970
=> - Added Town- & NationTagChangeEvent

build.properties, src/com/palmergames/bukkit/towny/event/PlotChangeOwnerEvent.java, src/com/palmergames/bukkit/towny/event/PlotChangeTypeEvent.java, src/com/palmergames/bukkit/towny/object/TownBlock.java, src/com/palmergames/bukkit/towny/permissions/VaultPermSource.java
Leaving the UUIDs for now, going to see how im going to do it and test it out in a correct enviroment,
Till then I've done with PlotChangeType & Owner Event ending #1628
=> PlotChangeType & PlotChangeOwner Events

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/db/TownyDataSource.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Disabled toggling pvp while an outsider (someone not in your town) is in your town,
Added method getTown(UUID) & getNation(UUID)
=> Disable toggling pvp with an outsider in your town

src/com/palmergames/util/FileMgmt.java
Changed from US-ASCII to UTF-8 to allow special Charcters in config
=> Changed from US-ASCII to UTF-8 to allow special Charcters in config

src/ChangeLog.txt, src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/ResidentCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/db/SQL_Schema.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Town.java, src/plugin.yml, src/townyperms.yml
Added registered value to flatfile & SQL
Added registered value to the objeckts
Added registered value if not 0 (set to zero if null) to the
Townyformatter
=> Added registered value for Nations & Towns,

src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
=> Actually call PlayerEnter & Leave Events

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownyEconomyHandler.java, src/com/palmergames/bukkit/towny/TownyTimerHandler.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/event/PlotChangeTypeEvent.java, src/com/palmergames/bukkit/towny/listeners/TownyBlockPhysicsListener.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java, src/com/palmergames/bukkit/towny/object/Coord.java, src/com/palmergames/bukkit/towny/object/TownyObject.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java, src/com/palmergames/bukkit/towny/object/WorldCoord.java, src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java, src/com/palmergames/bukkit/towny/permissions/TownyPerms.java, src/com/palmergames/bukkit/towny/regen/block/BlockInventoryHolder.java, src/com/palmergames/bukkit/towny/regen/block/BlockMobSpawner.java, src/com/palmergames/bukkit/towny/regen/block/BlockSign.java, src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java, src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java, src/com/palmergames/bukkit/towny/tasks/RepeatingTimerTask.java, src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java, src/com/palmergames/bukkit/util/NameValidation.java, src/com/palmergames/util/TimeTools.java
These were the main problems my IDE was bitching about, however there are about 500 Javadocs which have no tag description at all or are incorrect, these ones were shown as full on errors though
=> Fixed some Javadoc Errors / Mistakes

src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
=> Added Confirmation Message to /ta rename

src/com/palmergames/bukkit/towny/TownyMessaging.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java, src/com/palmergames/bukkit/towny/listeners/TownyVehicleListener.java, src/com/palmergames/bukkit/towny/object/TownyUniverse.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java, src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java, src/com/palmergames/bukkit/util/ChatTools.java
Also fixed some Javadoc issues
=> Syntax Cleanup (Fixed small issues such as diamond operator missing)

src/com/palmergames/bukkit/towny/event/TownAddResidentRankEvent.java, src/com/palmergames/bukkit/towny/event/TownRemoveResidentRankEvent.java, src/com/palmergames/bukkit/towny/object/Resident.java
This would close issue #3041 if merged.
=> Added Town rank related events

src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Just skips the unreadable ones instead.
=> Made towny not go into safe mode when reading outdated outlaws

src/com/palmergames/bukkit/towny/command/ResidentCommand.java
Also clarified the existing check is only for essentials
=> Fix players being able to /res spawn out of jails

src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Partial Re-submission of #3147, sans the passenger-as-a-list commit (cleanup)
=> Redo: TP Cause and getItemInMainHand

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/util/NameValidation.java
I also fixed a javadoc issue in NameValidation
Closes: #3108
=> Fixed long town-boards colours breaking & allowed special characters.

src/com/palmergames/bukkit/towny/object/TownyUniverse.java, src/com/palmergames/bukkit/util/BukkitTools.java
=> Fixed Citizens NPCs being able to be invited.

src/com/palmergames/bukkit/towny/event/PlotChangeOwnerEvent.java, src/com/palmergames/bukkit/towny/event/RenameResidentEvent.java
=> Added the missing super(async) method call to 2 events.

src/com/palmergames/bukkit/towny/TownyFormatter.java, src/english.yml, src/es-mx.yml, src/french.yml, src/german.yml, src/italian.yml, src/norwegian.yml, src/russian.yml, src/spanish.yml
Some of my users asked me that they could see in which cities they have embassies executing /p
https://i.gyazo.com/a8a7532f27eca32d9f99cfd0b92f8428.png
=> Add embassies in resident status

src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/confirmations/ConfirmationHandler.java
- Adds confirmations to /ta town {townname} delete
- Both Console and Ingame-Use now have Confirmations.
=> Confirmations for /ta town {townname} delete

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- New Command /ta town {townname} toggle ....
- New Command /ta town {townname} set ....
- New Command /ta nation {nationname} toggle ....
- New Command /ta nation {nationname} set ....
=> Add nationSet/Toggle & townSet/Toggle to /ta abilities.

pom.xml
- Fix issues with building from TheNewEconomy's GitHub Package Registry
-- Identical changes to #3449 - just keeping the branches seperate
=> Fix Maven Building (master)

src/com/palmergames/bukkit/towny/TownyLogger.java
Signed-off-by: Articdive <articdive@users.noreply.github.com>
=> Possibly fix doubled TownyLogger

src/com/palmergames/bukkit/towny/TownyLogger.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Signed-off-by: Articdive <articdive@users.noreply.github.com>
=> Fix logger toggling

src/com/palmergames/bukkit/towny/command/InviteCommand.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/invites/Invite.java, src/com/palmergames/bukkit/towny/invites/InviteHandler.java, src/com/palmergames/bukkit/towny/object/inviteobjects/NationAllyNationInvite.java, src/com/palmergames/bukkit/towny/object/inviteobjects/PlayerJoinTownInvite.java, src/com/palmergames/bukkit/towny/object/inviteobjects/TownJoinNationInvite.java
The purpose of this pull request is to update the Invite system to allow it to be more expandable.
In its current state, the invite system does not allow for developers looking to add extensions to Towny without changing the source to add their own types of Invites. This pull request seeks to remedy that by moving the code for accepting or denying an invite into the invite class itself.
All current invite types have been updated to fit this new form, as have the commands to create/accept/deny/revoke those invites.
=> Adjusting the Invite System to Allow Expandability

resources/ChangeLog.txt, src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java
Just fixes various issues with the ConfigNodes file, such as spellings, pointers to the proper documentation, and addition of a description for a node.
Contains required config change. (d0619665cdc9272fb06356e88598626440a64c0d)
=> Various config changes

src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Fix the command not working for towns not owned by the admin.
=> Fix townyadmin meta command

src/com/palmergames/bukkit/towny/TownyMessaging.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/event/NationAddEnemyEvent.java, src/com/palmergames/bukkit/towny/event/NationPreAddEnemyEvent.java, src/com/palmergames/bukkit/towny/event/NationPreRemoveEnemyEvent.java, src/com/palmergames/bukkit/towny/event/NationRemoveEnemyEvent.java, src/com/palmergames/bukkit/towny/war/flagwar/TownyWar.java
Added Events and Pre Events for adding/removing enemies, and a few functions to get the cells that are currently under attack, both the full amount of them, as well as the ones that are in a specified town.
Also fixed TownyMessaging having a ClassCastException when passing a Resident object as the sender to the `sendErrorMessage` methods.
=> Expansions to FlagWar

src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java, src/com/palmergames/bukkit/towny/tasks/ProtectionRegenTask.java
=> Fix container blocks not regenerating properly

src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/object/Resident.java
A hotfix to remove plot group resident modes as they don't serve a purpose and they are throwing NPE's because they're not completed.
____
____
____
=> Hotfix: Remove plot group resident modes

src/com/palmergames/bukkit/towny/object/PlotObjectGroup.java, src/com/palmergames/bukkit/towny/object/Town.java
@suneettipirneni Going to remove the following methods I've marked as deprecated. The core method has unused variables and at this point is entirely unused, along with the rest of these methods.
____
=> Plotgroupcleanup

src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/event/PreNewTownEvent.java
Fixed some bugs with the PreNewTownEvent firing.
____
=> Fixed some bugs with the PreNewTownEvent firing.

pom.xml, src/com/palmergames/bukkit/towny/TownyEconomyHandler.java
This is a PR to update the Reserve methods utilized within Towny to the upcoming 1.4.3 API which is the version that will be utilized by EssentialsX.
____
____
____
=> Update Reserve methods to upcoming 0.1.4.3

src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/tasks/ProtectionRegenTask.java
To fix regens of spawners, which would spawn as pig spawners instead of the actual spawner destroyed.
____
#3627
____
=> Fix regen pig problem

src/com/palmergames/bukkit/towny/TownyMessaging.java
Fix small formatting issue where hyphen was green instead of white on deny line.
____
=> Hotfix: Fixed hypen still being green

src/com/palmergames/bukkit/towny/TownySpigotMessaging.java
`mvn javadoc:javadoc` was failing to run prior to this commit. It was either this, or to remove an asterisk.
____
N/A
____
N/A - Though semi-related to PR #3654 
____
=> Adds Parameters to Javadoc comment

src/com/palmergames/bukkit/towny/object/Town.java
=> continue != break.

src/com/palmergames/bukkit/towny/object/EconomyAccount.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Town.java
=> Add collect() and pay() back as deprecated methods.

src/com/palmergames/bukkit/towny/command/InviteCommand.java
This pull request adds tab completion for the 3 arguments of /invite as well as suggesting town names from /invite accept <town> and /invite deny <town>
____
Tab completion for /invite
____
None
____
=> Implement tab completion for /invite

.gitignore, src/com/palmergames/bukkit/towny/invites/TownyInviteReceiver.java
=> Add .ds_store to .gitignore

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/utils/NameUtil.java
This pull request adds proper /nation tab complete support. Some more important changes are the returning of an `Collections.emptyList()` instead of `null` if there are no valid tab completes. `null` simply returns online players, and can lead to irrelevant results. 
Additionally, the names of nations will only be returned if the player is not typing any valid sub commands. For example, typing  `/nation e` will only return sub commands such as `enemylist`, If `/nation ev` is typed, nation names will be returned such as an example nation called `Everett`. This reduces clutter and reduces the times where all nation names are checked.
This pull request also adds more methods to `NameUtil.java`. These methods are used for getting the resident names of a player's town or nation, and getting …
=> Added proper tab completion for /nation

src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/command/BaseCommand.java, src/com/palmergames/bukkit/towny/command/InviteCommand.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/ResidentCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/util/Trie.java
See commits for individual changes.
This PR changes commands to:
- Be more readable
- Return more relevant subcommands/residents/towns/nations/worlds
- Add missing features for certain subcommands, like /t invite
- Return empty list instead of null (online players) when no completions match
Fixed Trie to not be case sensitive when searching, and to respect case when adding new keys. Also fixed adding only lowercase strings in TownyUniverse.
____ …
=> Better tab completes

resources/zh-TW.yml
=> fix zh-TW.yml

src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/utils/CombatUtil.java
Fix an issue where enabling plot pvp in a town that has pvp off would not enable pvp.
Prevent plot pvp from being toggled if admin pvp is enabled/disabled (both handled) in the town.
____
____
____
=> Fix toggling plot pvp

src/com/palmergames/bukkit/towny/command/BaseCommand.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/utils/NameUtil.java
Fixed NPE when using certain sub commands of /ta
- Moved command specific methods out of NameUtil
- TownyAdmin finds tab completions by arguments, not null player value
- Fixed scopes and functions of TownCommand and NationCommand
____
Fixes #3724
____
=> Fixed NPE when using certain sub commands of /ta

src/com/palmergames/bukkit/towny/command/BaseCommand.java, src/com/palmergames/util/Trie.java
Random residents/towns/nations were not showing up when attempting to tab complete them. The issue had to do with the search finding trie nodes that matched the first found result for upper and lower cases. For example, if "hElp" and "hello" existed, "he" would only return "hElp", and "hel" return nothing because the trie would only search for nodes under "hE", not "he". This bugfix makes the trie only search for nonmatching case if no matching cases are found.
____ …
=> *HOTFIX* Fixed missing tab completions

src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
- Added /ta town/nation new foo mayor
- Added /ta toggle townwithdraw/nationwithdraw and removed withdraw
- Added /t mayor
- Added /plot perm hud
Fixes several minor parts of tab completes
____
Resolves [#3733](https://github.com/TownyAdvanced/Towny/issues/3733)
____
=> Fixed several tab completions

src/com/palmergames/bukkit/towny/listeners/TownyLoginListener.java
Small typo fix, you can just completely ignore my last pull request I closed, I realized what I did as soon as I submitted it lol.
____
____
____
=> Small typo fix

src/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java
Fixed nether grief where outsiders could spawn nether portals within other towns without proper permissions.
____
=> fix for nether portal town griefing

src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
Fix townyworld set messages for console not being used. Apparently it was just using the regular console help messages.
____
=> Fix townyworld set messages for console not being used.

src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Town.java, src/com/palmergames/bukkit/towny/object/TownBlock.java, src/com/palmergames/bukkit/towny/object/TownyObject.java
Removes warnings for raw parameterization of `CustomDataField`
____
=> remove metadata raw access warnings

src/com/palmergames/bukkit/towny/event/PreNewDayEvent.java, src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
Adds a PreNewDayEvent to the API for plugins to execute whatever operations they need before towny handles its new day operations.
____
#3765
____
=> Add PreNewDay Event

legacy/TownyHModFlatFileSource.java, legacy/wallgen/blockqueue/BlockQueue.java, legacy/wallgen/blockqueue/BlockWorker.java, legacy/wallgen/notready/WallGen.java
Signed-off-by: Articdive <13535885+Articdive@users.noreply.github.com>
This pull request just removes some todos in legacy files that we don't require anymore
____
It does not.
____
It does not.
____
This has no effect on code.
=> Remove TODOs in legacy files.

src/com/palmergames/bukkit/towny/command/NationCommand.java
Fix `/n online` not tab-completing with nation names.
____
=> Add nation tab-complete to `/n online`.

src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/event/NationUpkeepCalculationEvent.java, src/com/palmergames/bukkit/towny/event/TownUpkeepCalculationEvent.java, src/com/palmergames/bukkit/towny/event/TownUpkeepPenalityCalculationEvent.java
Added Calculation Events
____
https://github.com/TownyAdvanced/Towny/issues/3781
____
=> Add Calculation Events

src/com/palmergames/bukkit/towny/event/NationTagChangeEvent.java, src/com/palmergames/bukkit/towny/object/Nation.java
The intent is to make it possible to know which nation the tag is being changed for in the NationTagChangEvent.
____
I have not tested because this minor code addition isn't going to break anything.
=> Add a Nation getter to NationTagChangeEvent

src/com/palmergames/bukkit/towny/command/NationCommand.java
=> Fix resident tab-complete for nation rank manipulation.

src/com/palmergames/bukkit/towny/command/PlotCommand.java
The wheel keeps on turnin'.
____
=> Fix plot toggle mobs tab-complete.

src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Add economy commands to town/nation sub-commands within `/townyadmin`.
The appropriate language strings have not been added (but have been stubbed). I was not sure if we should use existing ones or create new ones.
____
Withdraw/Deposit Sub-commands to `/ta town` and `/ta nation`. Example Usage: `/ta town TestTown withdraw 5`.
____
Closes #3687 
____
=> Add economy commands to towny admin.

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/util/NameValidation.java
This fixes errors of Unicode characters ie "Ã" being stripped and not saving properly this mainly effected users who used non-English languages with special character sets.
____
This changes the default regex configurations to allow unicode.
____
Closes #3805, Closes #3803
____
=> Fix unicode not being saved

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/db/SQL_Schema.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Town.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java, src/com/palmergames/bukkit/towny/tasks/TownClaim.java, src/com/palmergames/bukkit/towny/utils/CombatUtil.java, src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
Towns have changed from town.getWorld() to town.getHomeblockWorld(),
with getWorld() becoming deprecated and returning getHomeblockWorld().
Some instances of town.getWorld() are now correctly using
townblock.getWorld() or something similar when it is called for.
Stop getHomeblockWorld() from returning null when towns have claimed 0
townblocks.
Towny.setWorldFlags() from startup sequence is gone.
SQL now drops old towns columns and saves/loads worlds without towns
like flatfile.
____
____
____ …
=> Branch will remove TownyWorlds saving a list of towns.

resources/ChangeLog.txt
This Branch will accomplish a number of things, most importantly:
- Stop saving and loading townblocklists (towny\data\townblocks.txt
- Townblocks are loaded from the towny\data\townblocks folder directly and stored in their Towns primarily, with a seconday map being held in TownyUniverse as a fallback.
- Remove townblocks from the TownyWorlds, where they were in far to large a group to reasonably save them.
- Hopefully solve the issue of disappearing townblocks.
____
None.
____
All of the tickets in the Disappearing Townblocks project.
#3783 #3796 #3813 #3821 
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that …
=> Branch will remove TownBlockLists saving/loading, remove TownBlocks from TownyWorld, add TownBlocks to Town and TownyUniverse.

resources/chinese.yml, resources/english.yml, resources/es-mx.yml, resources/french.yml, resources/german.yml, resources/italian.yml, resources/korean.yml, resources/norwegian.yml, resources/pt-br.yml, resources/russian.yml, resources/spanish.yml, resources/zh-TW.yml, src/com/palmergames/bukkit/towny/TownySpigotMessaging.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java
This adds the ability to click on a list item in `t list` or `n list` to spawn to the respective nation or town: (Available on Spigot derivatives only)
Lang Strings are included with this PR.
____
Closes #3827 
____
=> Add Click-to-Spawn for Town Lists and Nation Lists

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Signed-off-by: Articdive <13535885+Articdive@users.noreply.github.com>
So this just moves the onLogin and onLogout code into where they are called PlayerJoinEvent and onEnable(), in general just cleaning up the TownyUniverse class for the big refractor.
____
____
____
=> Move onLogin and onLogout out of TownyUniverse.

src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
The townyadmin economy sub-commands should now handle incorrect number of arguments properly.
____
=> Handle invalid arguments for townyadmin economy cmds.

pom.xml, src/com/palmergames/bukkit/towny/utils/SpawnUtil.java
Many paper based servers use the benefits of async chunk loading. With this PR we can leverage this async chunk loading with town spawning. This makes teleporting faster for paper users while maintaining support for non-paper users.
____
=> Use Paperlib for Async Chunk Loading

resources/english.yml, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/object/Nation.java
Adds confirmations when towns will be lost by moving their homeblocks.
Adds proximity awareness to nation merging confirmations.
Appears to have a major effect in reducing Exception spam that can be seen in startup.
____
____
Closes #3740 
____
=> Branch fixes nation-requires-proximity

src/com/palmergames/bukkit/towny/tasks/SetDefaultModes.java
This fixes the message "Modes set: " from appearing for no apparent reason. I've tested creating/deleting a town and logging in/out.
____
____
#3857 
____
=> Fixes issue #3857

src/com/palmergames/bukkit/towny/confirmations/Confirmation.java, src/com/palmergames/bukkit/towny/confirmations/ConfirmationHandler.java
=> Make overlapping confirmations properly cancel prior ones.

resources/chinese.yml, resources/english.yml, resources/es-mx.yml, resources/french.yml, resources/german.yml, resources/italian.yml, resources/korean.yml, resources/norwegian.yml, resources/polish.yml, resources/pt-br.yml, resources/russian.yml, resources/spanish.yml, resources/zh-TW.yml, src/com/palmergames/bukkit/towny/TownySpigotMessaging.java, src/com/palmergames/bukkit/util/ChatTools.java
Adds the ability to click forward and back between pages with a town list,
or nation list:
____
Closes #3853
____
=> Add Clickable List Navigation

resources/french.yml
French translations for messages added between 0.72 and 0.82. 
Validated using yamllint.com + Tested Ingame.
____
=>  Update french.yml

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/ResidentCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java
This fixes the error where no feedback was given on the console when towny couldn't find a specified object with the given name.
____
Closes #3957
____
=> Fix Console not Showing Errors

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/util/NameValidation.java
This limits the unicode allowed to language characters only this means symbols are excluded.
Required Config Changes if using old unicode supported regex
____
=> Allow only Language Unicode

src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/event/PlotPreChangeTypeEvent.java
This PR aims to add a cancellable pre event for the PlotChangeTypeEvent
____
=> add a pre plot change type event

resources/pt-br.yml
Traslated the new messages from the 0.83 version to Brazilian Portuguese
____
____
____
=> Traslated messages from 0.83 to Brazilian Portuguese

src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/object/TownBlock.java
Fix /plot set reset not working due to it expecting a proper town block type.
Also includes some very minor cleanup to the plot set type code.
Also fixes the issue for plot groups and calls PlotPreChangeTypeEvent for plot groups as well.
____
=> Fix /plot set reset.

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/permissions/TownyPerms.java
This branch makes Towny go into safe mode if the townyperms.yml file does not load properly
____
____
#4003 
____
=> Place Towny into Safe Mode when a bad townyperms.yml file is loaded or reloaded.

pom.xml
This replaces all dependencies with gh account access with ones that aren't so Towny can properly build on jitpack.io. Whenever a release is made with towny, jitpack.io will automatically build a maven artifact. Any older releases using the gh packages will still remain. In addition sources are now attached so developers can see our internal comments and in-code javadocs in their IDE.
____
=> Switch to JitPack and Remove GH packages dependencies.

pom.xml
This adds attaches javadocs to maven, with the `mvn clean install` command, it won't be run with a normal `mvn install` command.
____
=> Add javadocs to maven

pom.xml
Bump spigot dependency in pom.xml
____
I mean no, but it compiles so...
=> Things that Go Bump in the Night

src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/object/TownComparators.java
Simple moves comparators to their own file, and adjusts the open sorting algorithm.
____
=> Move comparators to own file and clean up listing code.

resources/pt-br.yml
Translated the 0.84 message to Brazilian Portuguese
=> Translated the 0.84 message to Brazilian Portuguese

src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java, src/com/palmergames/bukkit/towny/object/Town.java
Hi,
I'm still learning programming.
I hope these changes aren't full of bad coding practices. In this case, I will be happy to have a feedback on how to fix them.
This small PR add 3 news "placeholders" usable in `notification.titles.*` config node:
- `{town_motd}` : show the town's townboard.
- `{town_residents}` : show the number of residents of the town.
- `{town_residents_online}` : show the number of online residents (including npcs) of the town.
The way of how thoses placeholders are applied to the `title` and `subtitle` string variables has been modified. Placeholders are now stored inside a HashMap, and applied inside a loop of each HashMap's entries.
`{town_residents_online}` is using a new Town method, `getNumResidentsOnline()`.
____
- None
____
- None
____
By making this pull …
=> Add 3 "placeholders" usable in "entering town titles".

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/command/commandobjects/CancelCommand.java, src/com/palmergames/bukkit/towny/command/commandobjects/ConfirmCommand.java, src/com/palmergames/bukkit/towny/confirmations/Confirmation.java, src/com/palmergames/bukkit/towny/confirmations/ConfirmationBuilder.java, src/com/palmergames/bukkit/towny/confirmations/ConfirmationHandler.java, src/com/palmergames/bukkit/towny/object/TownBlock.java, src/com/palmergames/bukkit/towny/tasks/TownClaim.java, src/com/palmergames/bukkit/towny/utils/SpawnUtil.java
The confirmation system has a new declarative syntax for creation and does not require the use of an instance variable. This is how the system looks currently:
```java
Confirmation confirmation = new Confirmation(() -> {
System.out.println("I was accepted");
});
confirmation.setTitle("My awesome title");
ConfirmationHandler.sendConfirmation(player, confirmation);
```
This has process has been condensed to:
```java
Confirmation.runOnAccept(() -> {
System.out.println("I was accepted");
})
.setTitle("My awesome title")
.send(player);
```
____
In addition, there is now a handler for when a confirmation is canceled. Also, you can now run the handlers async but using the `Confirmation.runOnAcceptAsync()` builder. 
By making this pull request, I represent that I have the right to waive copyright …
=> Confirmation System QOL Improvements/Changes

src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/util/StringMgmt.java
=> Add hex support to lang files

src/com/palmergames/bukkit/towny/event/TownClaimEvent.java, src/com/palmergames/bukkit/towny/tasks/TownClaim.java
=> Add resident to town claim event.

src/com/palmergames/bukkit/towny/TownySpigotMessaging.java
This makes sure that clickable commands use the namespace `towny:` to make sure that it doesn't conflict with another plugin command.
____
=> Hotfix: Add namespacing for commands run by clickable text

src/com/palmergames/bukkit/towny/TownySpigotMessaging.java
=> Fix HoverEvent deprecation and add adapter to for backwards compatibility.

src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
This fixes an issue where Towny would not load townblocks because it would encounter a system file in the townblocks directory.
____
=> Fix loading system files when loading all townblocks.

src/com/palmergames/bukkit/towny/TownyEconomyHandler.java, src/com/palmergames/bukkit/towny/object/economy/Account.java, src/com/palmergames/bukkit/towny/object/economy/BankAccount.java
The title says all, some users have had an issue were their eco provider gives each account a default amount of money, this affected the debt accounts as well, this PR fixes that. As well as the debug error messages.
____
Closes #4192
____
=> Make sure debt accounts start with zeroed out balance.

src/com/palmergames/bukkit/towny/object/Government.java
Nation tags were being cut to 3 letters, so fix that.
____
=> Fix nation tags being cut short

pom.xml, src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/util/FileMgmt.java
It seems that the current compression of `zip` is very finicky when it comes to filenames with utf-8 characters this has to do with the zip's reliance on platform encodings. For example some servers will have safe-mode errors because of the encodings not unzipping properly. To resolve this, we should be using the `tar.gz` which is universal across many platforms.
____
Changed default node `plugin.database.flatfile_backup` to `plugin.database.flatfile_backup_type` and the default value is now `tar`
it will still work if the value is `zip` so it's backward compatible.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge …
=> Do compression via tar and not zip

src/com/palmergames/bukkit/towny/object/economy/Account.java, src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
This simply removes the method from throwing an exception. I've done my best to backtrack and it seems like anything that calls the method does not rely on the exception for determining funds and handles insufficient funds properly w/o the exception.
This exception was also the reason that the new day was not collecting tasks properly as the new day task handles the exception in the first level of the task meaning the exception would stop the task entirely.
Added more explicit debugging to that to make sure it's easily traceable in case it happens again.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the …
=> Fix new day task not collecting taxes properly.

pom.xml, src/com/palmergames/bukkit/towny/permissions/GroupManagerSource.java
GM Source fetching player suffix instead of prefix
and fix GroupManager dependency in the pom.xml
____
____
____
=> GM Source fetching player suffix instead of prefix

pom.xml, pom_deb.xml
The purpose is to get rid of the crappy Github Packages references.
____
____
____
=> Update Reserve/TheNewChat maven repositories.

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java
Simply checks the success state of the withdraw on Town confirmation and discontinues if the withdraw did not succeed.
____
=> Fix economy bug with town confirmation.

pom.xml
Fix some things that don't need to be shaded, being shaded into the jar:
- GroupManager shouldn't be shaded
- Gson shouldn't be shaded (already in the server jar)
- Relocate apache commons-compress.
____
=> Fix shaded dependencies.

resources/chinese.yml
Now correctly translate "allow explosion" in Chinese. 
It was originally translated to "explosion protect"
____
Nope
____
Nope
____
=> Correctly translate "allow explosion" in Chinese

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownyTimerHandler.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java, src/com/palmergames/util/FileMgmt.java
This makes locking more efficient by separating locking between reads and writes. As a result, reads can be done concurrently, while writes are still synchronized and happen sequentially with reads. This is an improvement over the prior implementation where reads and writes were *both* synchronized. This will make sure any post-reads to the database are not held up by a backup.
This PR also address some other concurrency issues:
- In the event where a server is being reloaded while towny is performing its backup task, the server would complain about the backup task not being terminated properly after the plugin was disabled, this has been fixed by flushing the task when the plugin is disabled (if the task is running). This prevents incomplete backups from being created.
- The …
=> Concurrency QOL

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Previously using "tar.gz" as an option would not do tar backups it had to be "tar". This allows both "tar.gz" and "tar" to be used as config options.
____
=> Hotfix: Make "tar.gz" a valid config option.

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/object/Town.java
I hope this is working. Please forgive me If I´m doing something wrong...I´ve never worked with github before
Added a config value for the maximum price for a town block
____
economy.new_expand.max_price_claim_townblock
____
____
=> added a maximum price for claiming town blocks

src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/event/DeleteNationEvent.java, src/com/palmergames/bukkit/towny/event/DeletePlayerEvent.java, src/com/palmergames/bukkit/towny/event/DeleteTownEvent.java, src/com/palmergames/bukkit/towny/event/PreDeleteNationEvent.java, src/com/palmergames/bukkit/towny/event/TownyObjDeleteEvent.java
This PR aims to improve the towny object delete events. It adds fetching the UUID, and the time registered for each towny object: Resident, Town, and Nation. 
It also allows fetching the nation from the `PreDeleteNationEvent` so that behavior of the `PreDeleteTownEvent` (brought to my attention by NNYaKNpGms0eUVpiSdHx on discord). 
____
=> Improve delete events.

src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java, src/com/palmergames/bukkit/towny/utils/OutpostUtil.java
This PR optimizes the minimum town distance methods by removing redundant object creation and removing constantly square rooting for distance. Furthermore, it removes duplicate distance checking in some areas, opting to store the value in a variable instead for repeated use. 
____
=> Optimize town distance checks.

src/com/palmergames/bukkit/towny/db/SQL_Schema.java
This is meant to simplify the sql_schema's cleanup() method while also adding to see if the column we're attempting to drop hasn't been dropped yet.
Tested successfully.
____
____
____
=> simplify sql_schema's cleanup()

src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/db/TownyDataSource.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
- Moves flatfile-dependant methods from TownySQLSource and
TownyFlatfileSource to TownyDatabaseHandler.
- PlotBlockData/RegenList/SnapshotList methods.
- Removes TownySQLSource's ffQueryQueue.
- Moves TownyFlatfileSource queryQueue to TownyDatabaseHandler.
- Moves methods around to put things back into a sensible order.
- Fix a call to getTownWorld() that should have been getWorld() in
TownyPlayerListener.
- Use previously unused TownyDatasource method to load residents'
friends.
- Use previously unused TownyDatasource method to load nations' allies
and enemies.
- Deprecates getTownWorld().
- Deprecates getResidentKeys(). (Unused)
- Deprecates getTownsKeys(). (Unused)
- Deprecates getNationsKeys(). (Unused)
____
____
____
By making this pull request, I represent that I have the right to …
=> Datasource Cleanup

src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/db/TownyDataSource.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/tasks/CleanupTask.java, src/com/palmergames/util/FileMgmt.java
=> Archive plot-block-data to save HDD space.

src/com/palmergames/bukkit/towny/tasks/GatherResidentUUIDTask.java, src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
This commit will make it so that true offlineMode servers will not have their databases wiped out by the GatherResidentUUIDTask.
____
____
____
=> Offline mode UUID task mercy branch

src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/object/metadata/BooleanDataField.java, src/com/palmergames/bukkit/towny/object/metadata/CustomDataField.java, src/com/palmergames/bukkit/towny/object/metadata/CustomDataFieldType.java, src/com/palmergames/bukkit/towny/object/metadata/DecimalDataField.java, src/com/palmergames/bukkit/towny/object/metadata/IntegerDataField.java, src/com/palmergames/bukkit/towny/object/metadata/LongDataField.java, src/com/palmergames/bukkit/towny/object/metadata/StringDataField.java
This was initially supposed to be a really minor PR, but then I kind of went down a rabbit hole. 
This PR adds a new metadata field to store `longs` by introducing the `LongDataField`.
In additions, it also ends up fixing numerous bugs (like the bug where admins didn't even set metadata properly via the command).
Furthermore, it makes the `CustomDataField` class truly abstract relying less on switch statements and makes it much easier to add new metadata types in the future, potentially paving the way for even allowing developers to add their own metadata types in the future.
This PR does not break any API usage at all. 
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related …
=> Metadata Improvements

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/listeners/TownyInventoryListener.java, src/com/palmergames/bukkit/towny/object/Resident.java, src/com/palmergames/bukkit/towny/object/TownyInventory.java, src/com/palmergames/bukkit/towny/utils/ResidentUtil.java
Opens GUI screens to visually show what the item_use and switch materials are to the players.
____
- New Command: /towny switches
- Opens GUI showing all of the switch materials.
- New Command: /towny itemuse
- Opens GUI showing all of the itemuse materials.
____
Closes #4396 
____
=> Switch and ItemUse GUIs.

src/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java
Fixes teleport warmup forcing a sync load. This just removes that logic and let's PaperLib handle it depending on server environment. 
____
#4391 
____
=> Fix sync loading chunk on teleport warmup.

src/com/palmergames/bukkit/towny/TownyMessaging.java, src/com/palmergames/bukkit/towny/event/executors/TownyActionEventExecutor.java, src/com/palmergames/bukkit/towny/object/metadata/CustomDataField.java, src/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java, src/com/palmergames/bukkit/towny/utils/NameUtil.java, src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java, src/com/palmergames/bukkit/towny/utils/ResidentUtil.java, src/com/palmergames/bukkit/util/ItemLists.java
Maven was complaining on clean/build/package phase due to the Javadoc plugin. Fixes the related errors so that it no longer fails for these specific issues.
Relevant changes:
- Fix inappropriate @param references
- Should be the variable name, not the object.
- Add missing tags & descriptions
- Some @returns and @params were not added when initially written.
- Deprecated methods still need these, too. The Javadoc plugin *will* throw errors otherwise.
- Escape '<' & '>'; remove inappropriate @throws
____
N/A - Some Javadoc tags were added / modified / removed.
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that …
=> Fix Javadoc Errors (Again...)

src/com/palmergames/bukkit/towny/TownyAPI.java, src/com/palmergames/bukkit/util/BukkitTools.java
This PR aims to slightly optimize the TownyAPI which will benefit its use in hot areas. One of the goals was to reduce / eliminate the creation of exception objects which can be expensive in hot areas. The second goal was to optimize resident -> player conversion by utilizing the newly stored resident UUIDs (the server can fetch a player from a UUID faster than it can from a name), but still falls back to fetching the player from the name. 
____ …
=> Optimize TownyAPI

resources/french.yml
Translation of messages from version 0.83 to 0.88. Also fix a mistype on destroy. 
____
____
____
=> French Translation v0.88

src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Looks like a bad merge screwed up the Javadoc for TownyPlayerListener.onPlayerBlowsUpBedOrRespawnAnchor - preventing maven from properly functioning.
____
N/A
____
Allows progress for https://github.com/TownyAdvanced/Towny/pull/4422
____
=> Fix Malformed Javadoc

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java, src/com/palmergames/bukkit/towny/db/SQL_Schema.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java, src/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java
Add the ability to turn Mobs in the wilderness on and off.
____
NWS_WILDERNESS_MONSTERS_ON
PROT_MOB_REMOVE_WILDERNESS
____
https://github.com/TownyAdvanced/Towny/issues/4169
____
=> Wilderness mob toggle

src/com/palmergames/bukkit/towny/command/NationCommand.java
This Pull Request adds the ability to use `/n list by resident`. Currently, `/n list by` will take "residents", but "resident" has been a valid comparator in `msg_error_invalid_comparator_nation:` and has worked with `/t list by resident`.
____
- New command: /n list by resident
- Lists nations by residents.
____
____
=> Add /n list by resident

resources/ChangeLog.txt, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/tasks/PlotClaim.java, src/com/palmergames/bukkit/towny/tasks/TownClaim.java, src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java
- Area selection util was also determining if something could be claimed, while it should have only been getting a shape of WorldCoords.
- Remove a pile of redundant stuff in the claiming code.
- Actually filter radius claims going too close to homeblocks.
- Make /plot nfs not work on PlotGroups and make use of unused language string.
Area selection changes:
- The `/t claim rect|circle #` commands both make perfect rings, with no half-made rings of claims. (Either a perfect square or circle.)
- They will auto-lower the desired radius to accomplish this.
- Results in a centered rectangle instead of claims being made primarily in the upper left corner.
- Closes #4395.
- Claiming is now done using a spiral outwards from the stood-in plot.
- Makes for perfect-looking claims when /t claim …
=> Claiming & AreaSelectionUtil Fix Up.

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java
The intention of this pull request is to enable those who use SQL options for Towny to have more customization options for SQL Flags, which in some cases, especially for myself, where I would have to edit the source-code on my own to get Towny to be align with MySQL's structure.
____
Removed configuration option for "`ssl: 'false'`" under "sql:" in the config.yml and replaced it with "`flags: '?verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf-8'`"
____
https://github.com/TownyAdvanced/Towny/issues/4446
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization …
=> Adds SQL Flags to Towny

src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/object/Resident.java
`Resident#removeTown()` will currently check if the town has no residents after removing themselves from the town, and if the town is empty, it will call the `TownyDatabaseHandler#removeTown()` method which deletes the town. However, the issue is that the db handler method calls the resident remove town method which eventually calls the db handler's remove town method again. This causes a double-delete which has not seemingly caused any issues, but has the potential to.
The reality is that the resident shouldn't even handle that logic anyway since it's out of scope for the purpose of the resident class, and it's actually not needed. This PR removes that logic in the resident method. It also implements the replacement logic in only one neccesary area …
=> Don't delete town inside of `Resident#removeTown()`

src/com/palmergames/bukkit/towny/event/actions/TownyBurnEvent.java, src/com/palmergames/bukkit/towny/event/executors/TownyActionEventExecutor.java, src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java, src/com/palmergames/bukkit/towny/war/common/WarZoneListener.java
- New Event: TownyBurnEvent(Block block, Location location, TownBlock townblock, boolean cancelled).
- New TownyBurnEvent allows for Towny, and then Towny's war systems and
other plugins to decide if a block can ignite or burn.
- Moves Event and Flag war onto new TownyBurnEvent.
____
____
____
=> TownyBurnEvent - Expanding the API project.

src/com/palmergames/bukkit/towny/TownyAPI.java, src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java, src/com/palmergames/bukkit/towny/listeners/TownyVehicleListener.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Resident.java, src/com/palmergames/bukkit/towny/object/TownBlock.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java, src/com/palmergames/bukkit/towny/object/metadata/BooleanDataField.java, src/com/palmergames/bukkit/towny/object/metadata/CustomDataField.java, src/com/palmergames/bukkit/towny/object/metadata/DecimalDataField.java, src/com/palmergames/bukkit/towny/object/metadata/IntegerDataField.java, src/com/palmergames/bukkit/towny/object/metadata/LongDataField.java, src/com/palmergames/bukkit/towny/object/metadata/StringDataField.java, src/com/palmergames/bukkit/towny/utils/EntityTypeUtil.java
Cleanup the mass of warnings listed by IDEs.
____
None.
____
None.
____
=> Cleanup Warning

.gitignore, src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/event/player/PlayerKilledPlayerEvent.java, src/com/palmergames/bukkit/towny/object/Identifiable.java, src/com/palmergames/bukkit/towny/war/flagwar/CellUnderAttack.java, src/com/palmergames/bukkit/towny/war/flagwar/listeners/FlagWarBlockListener.java
This PR does a few things:
- Cleans up some FlagWar code
- Removes 9-year+ old test code (Pre-GitHub); This code has never been used, so it got the snap.
- Adds a Deprecation annotation to the old CellUnderAttack constructor
- Adds _some_ Javadocs for the CellUnderAttack constructor
- Prevents pistons from modifying blocks protected during FlagWar (namely, the beacons). This has been a TODO for forever, now.
<details>
<h4>Old functionality</h4>
<p> Sticky Pistons could retract "protected" blocks.</p>
<h4>New functionality</h4>
<p>Sticky Pistons can no longer retract "protected" blocks.</p>
</details>
- Amends minor Javadoc warnings from elsewhere (just rolled it in with this...)
- Adds a folder related to [an IntelliJ plugin](https://plugins.jetbrains.com/plugin/12541-dependency-analytics) …
=> Small Clean-up, Sticky pistons cannot move immutable FlagWar blocks (e.g. a flag beacon)

resources/chinese.yml, resources/english.yml, resources/es-419.yml, resources/french.yml, resources/german.yml, resources/italian.yml, resources/korean.yml, resources/norwegian.yml, resources/polish.yml, resources/pt-br.yml, resources/russian.yml, resources/spanish.yml, resources/zh-TW.yml, src/com/palmergames/bukkit/towny/command/TownyCommand.java
Modifies the output of `/towny universe` to include a couple things:
- General Attribution of contributors
- Project Webpage Link (https://TownyAdvanced.github.io)
- Add TownyFlight and TownyNameUpdater to output, if present at runtime.
- Some formatting changes (mainly breaking up and moving parts of strings)
<details>
</details>
____
None - Though, there are new strings for translators to translate.
New Translatable Strings:
- `msg_universe_attribution`
- `msg_universe_contributors`
- `msg_universe_heart`
- `townblock_plu`
____
N/A - This is a general enhancement with no ticket.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I …
=> Expand `/towny universe` output.

resources/es-419.yml
Updates `es-419.yml` to the latest release **(0.96.4.0)**
____
None
____
None
____
=> Update es-419.yml 

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/TownyTimerHandler.java, src/com/palmergames/bukkit/towny/tasks/HourlyTimerTask.java, src/com/palmergames/bukkit/towny/tasks/ShortTimerTask.java
- New Config Option: plugin.hour_timer.hour_interval
- Default 60m
- The number of minutes in each "hour".
- Default is 60m.
- New Config Option: plugin.hour_timer.new_hour_time
- Default: 30m
- The time each "hour", when the hourly timer ticks.
- MUST be less than hour_interval. Default is 30m.
- New Config Option: plugin.hour_timer.short_interval
- Default: 20s
- The interval of each "short" timer tick.
- Default is 20s.
- TownySettings#calcTownLevelId(Town town)
- Method used to determine which town_level a town is, based on the
numeric order of the town_levels.
____
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I …
=> Merges some useful things from SiegeWar.

src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/tasks/HourlyTimerTask.java, src/com/palmergames/bukkit/towny/war/common/townruin/TownRuinSettings.java, src/com/palmergames/bukkit/towny/war/common/townruin/TownRuinUtil.java, src/com/palmergames/bukkit/towny/war/siegewar/SiegeWarSettings.java
- New settings class TownRuinSettings.
____
____
____
=> Town Ruin Separation

.github/workflows/compile-on-push.yml, .github/workflows/deploy-on-release.yml, pom.xml
Cleans up and updates multiple dependencies.
<details>
<summary>Changes</summary>
The following changes have been made:
- Updated Repositories
- Replace EssentialsX's repository with their new one. 
- They are doing a complete overhaul while they transition to Gradle. We will want to update the dependency at a later date as it will be changing it's groupId to `net.essentialsx` - this won't happen until 2.19.0 is released.
- Remove old GroupManager repository, as it's not being used for anything. (And was not following @ElgarL's GroupManager, either.)
- Updated Dependencies
- Update `citizensapi` from `2.0.25-SNAPSHOT` to `2.0.27-SNAPSHOT`
- Update `EssentialsX` from `2.16.1` to `2.18.2`
- Update `GroupManager` from version `2.5` to `2.9`
- Update `PaperLib` from `1.0.2` to `1.0.5`
- …
=> Update POM: Bump Dependencies and Update Essentials Repo

src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
Fixed a bug which prevented console commands from specifying discrete toggles in the TownyWorld command.
____
PR https://github.com/TownyAdvanced/Towny/pull/4336
____
=> Fix for console TownyWorld discretes

src/com/palmergames/bukkit/metrics/Metrics.java, src/com/palmergames/bukkit/towny/TownyAPI.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Town.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java, src/com/palmergames/bukkit/towny/object/economy/adapter/ReserveEconomyAdapter.java, src/com/palmergames/bukkit/towny/permissions/GroupManagerSource.java, src/com/palmergames/bukkit/towny/permissions/VaultPermSource.java, src/com/palmergames/bukkit/util/Colors.java, src/com/palmergames/util/MemMgmt.java, src/com/palmergames/util/TimeTools.java
The following commit contains changes that ensure the code executes as expected.
- Increase precision of mathematic functions by casting.
- Compare content of strings / objects, rather than locations in memory.
- Improve safety of closing Statements.
- Ensure the value of a variable is actually being assigned.
____
N/A - All changes are internal
____
A subset of #4481, again just trying to break it up into logical bits..
____ …
=> Ensure Objects are properly assigned, closed, and compared to improve safety and accuracy.

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/listeners/TownyServerListener.java, src/com/palmergames/bukkit/towny/object/Resident.java, src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
With the collection of resident UUIDs begun in 0.96.2.0 and expanded upon in 0.96.3.0 it is now possible to map player name changes internally, making the need for TownyNameUpdater unnecessary.
This PR adds: 
- a map to TownyUniverse.
- a much cleaner renamePlayer() in TownyDatabaseHandler.
- automatic disabling of TownyNameUpdater.jar.
- a cleaner and more stream-lined OnPlayerLogin.
____
____
Closes #2819 
____ …
=> Internal player name change handling.

pom.xml, src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java
The purpose of this PR is to implement Connection Pooling to MySQL. The benefit to this is having the ability to jump around on connections instead of having a single connection that might get stalled. This overall will improve performance of the data handling in MySQL and should be safer.
Showcase of these changes:
```
[15:13:19 INFO]: [Towny] Database: Loaded in 4347ms.
[15:13:19 INFO]: [Towny] Database: <50% of residents have stored UUIDs.
```
```
[15:13:46 INFO]:
[15:13:46 INFO]: -###---###-   [Towny 0.96.5.1]
[15:13:46 INFO]: #####-#####   Authors: Chris H (Shade), ElgarL, LlmDl
[15:13:46 INFO]: ###########    And contributors like you. <3
[15:13:46 INFO]: -#########-
[15:13:46 INFO]: --#######--   Residents: 140805 | Towns: 376 | Nations: 10
[15:13:46 INFO]: ----###----   Worlds: 4 …
```
=> Implemented MySQL Connection Pooling

src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java, src/com/palmergames/bukkit/towny/war/common/townruin/TownRuinSettings.java, src/com/palmergames/bukkit/towny/war/common/townruin/TownRuinUtil.java
Cleans up the Town Ruin feature introduced in https://github.com/TownyAdvanced/Towny/releases/tag/0.96.5.1. Made the Javadoc plugin stop spitting warnings, and my IDE / linter happy.
Fixes/Cleans:
- Added missing Javadoc parameters
- Mask implied constructors since these are utility classes.
- Methodized `setMayor()`, as it was duplicated between both methods (Removes TODO statement.) Also removed duplicate (inaccurate) inline comment for one of the callers.
- Collapsed exceptions with identical catches into singular statement.
- Collapsed if/if else statements with common output.
- Added a null-check in `OnPlayerLogin` task where `isRuined()` is called.
____
N/A - No additions relevant to server operators.
____
Cleans up after #4123 (original PR) and #4498 (actual implementation)
____
By …
=> Cleanup Town Ruin code - Javadoc and other changes.

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
A little qol change to thing that annoyed me and players of my server
____
N/A
____
N/A
____
=> Add space to ranks separator

pom.xml, src/com/palmergames/annotations/Unmodifiable.java
Seems like there's no need to shade in jetbrain annotations, since we don't use any of the runtime features. Thus this PR just removes the relocation and changes the dependency scope to provided.
____
=> Do not shade in jetbrain annotations.

src/com/palmergames/bukkit/towny/event/resident/ResidentJailEvent.java, src/com/palmergames/bukkit/towny/event/resident/ResidentUnjailEvent.java, src/com/palmergames/bukkit/towny/object/Resident.java
Originally posted as #4555 
____
____
____
=> Api/jail events courtesy of Kovalskki

resources/es-419.yml
Updates `es-419.yml` lang file with translated 0.93 strings.
____
____
____
=> Update es-419.yml to 0.93

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/event/nation/toggle/NationToggleNeutralEvent.java, src/com/palmergames/bukkit/towny/event/nation/toggle/NationToggleOpenEvent.java, src/com/palmergames/bukkit/towny/event/nation/toggle/NationTogglePublicEvent.java, src/com/palmergames/bukkit/towny/event/nation/toggle/NationToggleStateEvent.java
Part 2 of making the toggle events more abstract. This one is mainly just for consistency but still offers the same improvements that abstracting the `TownToggleEvents` did.
____
I have not tested it, but the changes are really small, I don't see anything breaking.
=> Make NationToggleEvents more abstract

src/com/palmergames/bukkit/config/ConfigNodes.java
This PR changes the default pool size of Towny because the current default might take up too many connections since the current number is multiplied by two (one set for saving, the other set for loading) database information.
Closes #4587.
____
____
____
=> Change default pool size

src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/event/plot/PlotNotForSaleEvent.java, src/com/palmergames/bukkit/towny/event/plot/PlotSetForSaleEvent.java
- Implemented PlotNotForSaleEvent
- Implemented PlotSetForSaleEvent
Closes #3981 
____
____
____
=> Implemented new Plot Events

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/object/economy/BankAccount.java
Adds BankAccount#getCachedBalance() and uses a configurable 10 minute cache time.
____
- New Config Option: economy.bank_account_cache_timeout
- default: 600s
- The time that the town and nation bank accounts' balances are
cached for, in seconds.
- Default of 600s is equal to ten minutes. Requires the server to be
stopped and started if you want to change this.
- Cached balances are used for PlaceholderAPI placeholders, town and
nation lists.
____
____ …
=> Simple bank caching.

src/com/palmergames/bukkit/towny/command/TownyCommand.java
Implemented /towny top balanace [all/town/nation]
____
____
____
=> New Towny Top Command

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java
Implemented the ability to configure the size of the `/towny top` command outputs.
____
```YAML
towny_top_size: '10'
```
____
____
=> Implemented configurable towny top size output

src/com/palmergames/util/Trie.java
There were some issues with Tab Completion and the handling of extended words which this PR fixes.
For example, suppose there are two towns with the name `TestTown` and `TestTown2`. When a player would attempt to tab-complete the town name, only `TestTown` would show up. 
There were also issues with removal. If the town `TestTown2` was deleted, then `TestTown` would also be deleted from the trie. 
____
Tested this on a local server with a couple different town and made sure tab-completion still worked and still properly removed keys when towns were deleted. Town names tested: 'TestTown', 'TestTown2', 'Tesmening', 'Tesmania'. 
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related …
=> Fix Tab Completion Issues

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/db/SQL_Schema.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/object/Town.java, src/com/palmergames/bukkit/towny/object/economy/BankAccount.java, src/com/palmergames/bukkit/towny/utils/MoneyUtil.java
=> Internal debt accounts

src/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java
Fix https://github.com/TownyAdvanced/Towny/issues/4647
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny License for perpetuity.
=> Trident Lightning Strike On PVP Disabled Plots

src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/chat/types/AllyType.java, src/com/palmergames/bukkit/towny/chat/types/NationType.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/db/TownyDataSource.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/event/DeleteNationEvent.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/TownyUniverse.java, src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java
The last of the TownyObject UUID refactor PRs (hopefully). This PR like the other PRs adds a map that tracks uuid -> nation. It also adds nullable fetching methods to TownyUniverse, deprecates the fetch methods in the database hander, and replaces usages appropriately. 
____
Tested on a local server, with a single player nation and an NPC nation. Everything seems to be working on the small-scale, so I don't expect any different with larger production servers. …
=> Nation UUID Map Refactor

src/com/palmergames/bukkit/towny/huds/PermHUD.java
This PR makes a small change to the /plot perm hud title so the full title is displayed (up to 128 characters)
Example:
Before:
After:
____
____
____
=> Small change to plot perm hud's title.

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/ResidentCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java, src/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/PlotGroup.java, src/com/palmergames/bukkit/towny/object/Resident.java, src/com/palmergames/bukkit/towny/object/Savable.java, src/com/palmergames/bukkit/towny/object/Town.java, src/com/palmergames/bukkit/towny/object/TownBlock.java, src/com/palmergames/bukkit/towny/object/TownyObject.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java, src/com/palmergames/bukkit/towny/object/economy/BankAccount.java, src/com/palmergames/bukkit/towny/object/inviteobjects/NationAllyNationInvite.java, src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java, src/com/palmergames/bukkit/towny/tasks/GatherResidentUUIDTask.java, src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java, src/com/palmergames/bukkit/towny/tasks/PlotClaim.java, src/com/palmergames/bukkit/towny/tasks/RepeatingTimerTask.java, src/com/palmergames/bukkit/towny/tasks/TownClaim.java, src/com/palmergames/bukkit/towny/war/common/townruin/TownRuinUtil.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java, src/com/palmergames/bukkit/towny/war/flagwar/FlagWar.java, src/com/palmergames/bukkit/towny/war/flagwar/listeners/FlagWarCustomListener.java
This is another preparation PR and more of a QoL refactor. It converts most usages of `TownyDataSource.saveObject(...)` to `TownyObject.save()`. E.g. `TownyDataSource.saveTown(town)` -> `town.save()`.
It's likely that during the database refactor, the datasource class will be removed (or at least deprecated) and another class will be used. By doing this refactor right now, we can easily switch out the usages without a large refactor in the future.
Made by the Intellij Structural Replace Gang
____
No logic was touched, so this is ready for review. Haven't tested yet. 
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that …
=> Add save method to Towny objects.

src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java
- Adds new Placeholder %townyadvanced_nation_map_color_hex%
____
____
____
=> Adds new Placeholder %townyadvanced_nation_map_color_hex%

src/com/palmergames/bukkit/towny/command/NationCommand.java
This PR fixes an error in PreNationEvent, where it tried to send an error message to a Town instead of a player
____
____
____
=> Fix PreNationEvent cancellation message

resources/ChangeLog.txt, src/com/palmergames/bukkit/towny/command/BaseCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java
Displays townless, online residents.
____
____
Closes #4674 
____
=> Add tab completion to /t add

src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
For what ever reason Towny somehow recorded a UUID for a player who has had their UUID change. This should handle those situations.
____
____
- Closes #4695
____
=> Assigns the correct UUID to players who have somehow gotten a previous UUID stored.

resources/es-419.yml
=> Update es-419 to Towny 0.98

resources/spanish.yml
Added missing gui_title translations. Also added Ngzhiwei to the credits as he had helped me translate some parts of the file.
=> Updated gui_titles

src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/huds/HUDManager.java, src/com/palmergames/bukkit/towny/huds/PermHUD.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java
This PR adds more functions to HUDManager to make it easier for any other plugin to use it. Some smaller changes included too.
____
____
____
=> Small HUDManager overhaul

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/listeners/TownyVehicleListener.java, src/com/palmergames/bukkit/towny/utils/EntityTypeUtil.java
Adds a new sub-command to townyadmin to give/remove nation ranks.
____
____
____
=> Add townyadmin command for giving/removing nation ranks

src/com/palmergames/bukkit/towny/war/eventwar/War.java
=> Fix event war plot attacking not working.

.gitignore, src/com/palmergames/bukkit/towny/command/PlotCommand.java
Adds events when toggling pvp, explosions, fire or mobs in a plot group.
____
____
____
=> Add PlotToggle events to toggling plot groups

pom.xml
Simple pull request bringing the POM file up to date with several dependencies and Maven plugins. also switches over to use HTTPS for several repositories.
____
- Repositories:
-  Prefer to use HTTPS instead of HTTP for PlaceholderAPI and CitizensAPI
- Dependencies:
- Updated to use Spigot-api 1.16.5
- Updated PaperLib to 1.0.6 &mdash; [Change Log][paper-changes] &ndash; [Commit Diff][paperlib-diff]
- Updated HikariCP to 4.0.1 &mdash; [Change Log][hikari-changes] &ndash; [Commit Diff][hikari-diff]
- Updated Log4J to 2.14.0 &mdash; [Release Notes][log4j release]
- Updated JetBrains Annotations to 20.1.0 &mdash; [Changelog][java-annotations]
-  Maven Plugins:
- Updated maven-compiler-plugin to 3.8.1 &mdash; [Release Notes][compiler-changes]
- Updated maven-javadoc-plugin to 3.2.0 &mdash; …
=> Update POM: Dependencies, Plugins, and HTTPS

src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/object/Nation.java
Fixes empty nations not being deleted on startup, and adds a null check in Nation#hasKing as a just in case.
____
____
____
=> Fix empty nations not being deleted on startup with flatfile

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java
Adds a new config option for ignoring the `min_plot_distance_from_town_plot` and `min_plot_distance_from_town_homeblock` for allies.
____
Adds TOWN_MIN_DISTANCE_IGNORED_FOR_ALLIES
____
Closes https://github.com/TownyAdvanced/SiegeWar/issues/119
____
=> Add config option for ignoring min_distance's for allies

resources/ChangeLog.txt, src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java, src/com/palmergames/bukkit/util/BlockUtil.java
____
____
- Closes #4783.
____
=> Fix up double-chest-on-plot-borders visual bugginess.

src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/db/SQL_Schema.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java
When this feature was added, the person who made the PR neglected to make it persistant.
____
____
Closes #4785 
____
=> Makes the maxPercentTaxAmount Persistent.

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/object/economy/Account.java, src/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java, src/com/palmergames/bukkit/towny/tasks/TownClaim.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java, src/com/palmergames/bukkit/towny/war/flagwar/FlagWar.java
Account#payToServer and Account#payFromServer were marked as being able
to throw an EconomyException. This led to Account#withdraw and
Account#deposit also being marked as being able to throw
EconomyExceptions.
This PR removes that and the various try/catch blocks that resulted from
withdraw/deposit being able to throw EconomyExceptions.
____
____
____
=> Removes unthrowable EconomyExceptions.

resources/english.yml, src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/TownyTimerHandler.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/SpawnPoint.java, src/com/palmergames/bukkit/towny/object/Town.java, src/com/palmergames/bukkit/towny/tasks/DrawSpawnPointsTask.java, src/com/palmergames/bukkit/towny/tasks/TownClaim.java
Results in a visual particle effect shown at town and nation spawns, as well as outpost and jail spawns.
As is the norm: I found more things I couldn't leave alone while adding them, which includes the following:
- Re-jiggering the homeblock and spawn setting for towns and nations.
- Reduces exceptions being able to be thrown.
- Moves the logic off of the Town and Nation object.
- Remove now-redundant forceSpawn methods in Town and Nation.
- Clean up things in the outposts' spawn adding/removing.
- Clean up things in the jails' spawn adding/removing.
- Add missing TownySetting for determining if nation spawns need to be
in the capital city.
____
____
Required in order to make multi-cell Jail plots much more usable for the mayors.
____
By making this pull request, I represent that I have …
=> Creation of SpawnPoint object, and DrawSpawnPointsTask.

src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/event/town/TownKickEvent.java, src/com/palmergames/bukkit/towny/event/town/TownPreMergeEvent.java
Adds a cancellable TownKickEvent that gets fired right before a resident is kicked from a town.
____
____
____
=> Add a TownKickEvent

resources/chinese.yml, resources/english.yml, resources/es-419.yml, resources/french.yml, resources/german.yml, resources/italian.yml, resources/korean.yml, resources/norwegian.yml, resources/polish.yml, resources/pt-br.yml, resources/russian.yml, resources/spanish.yml, resources/zh-TW.yml, src/com/palmergames/bukkit/towny/command/TownCommand.java
This PR makes it so the town merging 'not enough money' error shows the formatted balance, instead of an integer. Also adds 2 new checks, to make sure the succumbing town actually has outposts/purchased townblocks before displaying the respective error.
____
____
____
=> Formatted balance for not enough money error

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/event/nation/NationKingChangeEvent.java, src/com/palmergames/bukkit/towny/event/town/TownMayorChangeEvent.java
This PR adds 2 new cancellable events related to mayor/king switching.
____
____
____
=> Add NationKingChangeEvent and TownMayorChangeEvent

resources/english.yml, resources/es-419.yml, resources/french.yml, resources/german.yml, resources/italian.yml, resources/korean.yml, resources/norwegian.yml, resources/plugin.yml, resources/polish.yml, resources/pt-br.yml, resources/russian.yml, resources/spanish.yml, resources/zh-TW.yml, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
Adds a new command for adding or removing nation enemies or allies. Also adds some new errors when a nation is already allied or enemied, and fixes some lang strings.
____
Adds `towny.command.townyadmin.nation.enemy` and `towny.command.townyadmin.nation.ally`.
____
Closes #4819
____
=> Add townyadmin command for adding/removing nation allies or enemies

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownySettings.java
Adds a config option for enabling/disabling the drawspawnpointstask.
____
Adds plugin.visualized_spawn_points_enabled:
- If enabled, particles will appear around town, nation, outpost & jail spawns.
____
Closes #4857
____
=> Add config option for toggling visualized spawn points.

resources/chinese.yml, resources/danish.yml, resources/english.yml, resources/es-419.yml, resources/french.yml, resources/german.yml, resources/italian.yml, resources/korean.yml, resources/norwegian.yml, resources/polish.yml, resources/pt-br.yml, resources/russian.yml, resources/se-SV.yml, resources/spanish.yml, resources/zh-TW.yml, src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/command/InviteCommand.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/utils/ResidentUtil.java, src/com/palmergames/bukkit/towny/war/common/townruin/TownRuinUtil.java
TODO: testing.
____
- New Config Option:
global_town_settings.max_residents_capital_override
- Default: 0
- The maximum number of residents that can be joined to a capital city.
- Requires max_residents_capital_override to be above 0.
- Uses the greater of max_residents_capital_override and max_residents_per_town.
____
- Closes #4841.
____
=> Capital cities get increased max residents limit.

src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/event/NationPreTransactionEvent.java, src/com/palmergames/bukkit/towny/event/TownPreTransactionEvent.java, src/com/palmergames/bukkit/towny/exceptions/EconomyException.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java, src/com/palmergames/bukkit/towny/object/Government.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Town.java, src/com/palmergames/bukkit/towny/object/TownComparators.java, src/com/palmergames/bukkit/towny/object/economy/Account.java, src/com/palmergames/bukkit/towny/object/economy/BankAccount.java, src/com/palmergames/bukkit/towny/object/economy/GovernmentAccountAuditor.java, src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java, src/com/palmergames/bukkit/towny/tasks/PlotClaim.java, src/com/palmergames/bukkit/towny/utils/MoneyUtil.java, src/com/palmergames/bukkit/towny/utils/SpawnUtil.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java, src/com/palmergames/bukkit/towny/war/flagwar/FlagWar.java, src/com/palmergames/bukkit/towny/war/flagwar/listeners/FlagWarCustomListener.java
I re-re-evaluated the EconomyException and did some back-tracing into why it came to be, resulting in the same conclusion I got last time: the EconomyException is not needed at all any longer. 
This time I broke it down into 3 stages and 3 commits, see individual commit messages for the full details.
____
____
____
=> EconomyException removal.

resources/english.yml, src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/db/SQL_Schema.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/object/Resident.java, src/com/palmergames/bukkit/towny/object/Town.java, src/com/palmergames/bukkit/towny/object/TownBlock.java
Sorts resident lists by the date the residents joined the town at.
____
____
____
* Tested on flatfile, haven't tested SQL but should work fine.
=> Sort town resident list by date they joined it

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java
Adds a new config option for changing the maximum length of a tag.
____
New config option: filters_colour_chat.modify_chat.max_tag_length
- Default: 4
- Maximum length for Town and Nation tags.
____
Closes #4904 
____
=> Customizable tag lengths

src/com/palmergames/bukkit/towny/TownyMessaging.java
Fixes /n list by online showing the total amount of residents in a nation, instead of only online ones.
____
____
____
=> Fix /n list by online showing total residents

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/command/TownCommand.java
Adds a config option to automatically capitalise town names upon creation.
____
Adds global_town_settings.automatic_capitalisation:
- When enabled, town names will automatically be capitalised upon creation.
____
Closes #4891 
____
=> Add auto town name capitalisation

src/com/palmergames/bukkit/towny/db/SQL_Schema.java
=> Fix for the SQL broken in 0.96.7.15.

src/com/palmergames/bukkit/towny/ChunkNotification.java, src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
Fixes potential spam in console by adventure by converting the message string to a component using LegacyComponentSerializer instead of the standard Component.text()
____
____
#4938 
____
=> Fix potential console spam from adventure

src/com/palmergames/bukkit/towny/TownyAddonAPI.java, src/com/palmergames/bukkit/towny/TownyCommandAddonAPI.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/ResidentCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java, src/com/palmergames/bukkit/towny/object/AddonCommand.java
Adds a new command addon API, that allows plugin developers to add their own sub commands to Towny's existing commands.
Example:
```java
TownyCommandAddonAPI.addSubCommand(CommandType.TOWN, "mycommand", new MyCommand());
```
The above code adds "mycommand" as a subcommand for /t, the onCommand function in the MyCommand class is called whenever a player does /t mycommand.
And to add additional tab completion:
```java
AddonCommand addonCommand = new AddonCommand(CommandType.TOWN, "mycommand", new MyCommand());
addonCommand.setTabCompletion(0, Arrays.asList("suggestions","for","first","arg"));
addonCommand.setTabCompletion(1, Arrays.asList("suggestions","for","second","arg"));
TownyCommandAddonAPI.addSubCommand(addonCommand);
```
____
____
____
By making this pull request, I represent that I …
=> Add command addon API

resources/ChangeLog.txt, src/com/palmergames/bukkit/towny/TownyAsciiMap.java, src/com/palmergames/bukkit/towny/TownyLogger.java, src/com/palmergames/bukkit/towny/command/HelpMenu.java, src/com/palmergames/bukkit/towny/command/InviteCommand.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/ResidentCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java, src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java, src/com/palmergames/bukkit/towny/war/eventwar/War.java, src/com/palmergames/bukkit/util/ServerBroadCastTimerTask.java
facilitate further integration of the Adventure library for
future-translation-plans.
Undoes #4933 
____
____
____
=> Replace player.sendMessage() with TownyMessaging.sendMessage(), to

src/com/palmergames/bukkit/towny/utils/CombatUtil.java
=> Fix tamed dogs not being hittable inside towns.

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/ResidentCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
Fixes a few things I forgot to double check in the original addon API PR.
____
____
____
=> Fix a few tab completion issues with the addon API

src/com/palmergames/bukkit/towny/db/SQL_Schema.java
Notes and discussion on #4935. 
____
None
____
#4935 
____
=> Include tb_prefix in column drop check (Closes #4935)

src/com/palmergames/bukkit/towny/command/PlotCommand.java
=> Validate /plot group fs input

src/com/palmergames/bukkit/towny/command/TownyCommand.java
=> Fix addon api exception in the towny command

resources/es-419.yml
This pull request translates the following strings into `es-419`:
- `msg_command_outsider_blocked`
- (space left in case more strings are added to the language files)
____
____
____
=> Translate es-419

src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java, src/com/palmergames/bukkit/towny/tasks/NPCCleanupTask.java
Adds a new NPCCleanupTask that deletes any npcs without towns during the daily timer task.
____
____
____
=> Automatically clean up unused NPC residents

src/com/palmergames/bukkit/towny/db/TownySQLSource.java
- Closes #4990.
____
____
____
=> Fix loading resident jail cells/hours for sql servers.

pom.xml, resources/plugin.yml, src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/hooks/LuckPermsContexts.java
Adds towny contexts to LuckPerms. At the moment this is very similar to our townyperms.yml, but the difference is that these can be used together with other contexts (per world permissions for example).
Screenshot from the luckperms editor:
____
New config option: plugin.interfacing.luckperms_contexts
- If enabled, Towny contexts will be available in LuckPerms.
- https://luckperms.net/wiki/Context
____
____ …
=> Add luckperms contexts

src/com/palmergames/bukkit/towny/object/Resident.java
Removes the ability for players to add themselves or NPCs as friends
____
____
____
=> Fix players res friending themselves or NPCs

.github/workflows/compile-on-push.yml, .github/workflows/deploy-on-release.yml, pom.xml, src/com/palmergames/bukkit/towny/utils/TownUtil.java
Fixing the maven build when Javadocs are enabled (not using `github-actions` profile). Was failing due to a `@param` tag not matching the method's parameter name. Also took the liberty of doing some ~~spring~~ summer cleaning.
____
- Renamed the `github-actions` maven profile to `no-apidoc` to better convey purpose.
- Added `enforce-java-8-bytecode` automatic profile. Ensuring JVM 8 compatible bytecode from JDK 9+.
- The compiler should be forced to generate the bytecode for Java 8, by using the `-release 8` build flag.
- Relocated the `net.kyori.examination` package. Assumed it not being relocated prior was unintentional.
- Fixed the errant `@param` javadoc tag that was failing the builds.
- Also added a private constructor to the TownUtil which throws an IllegalStateException.
- Updated …
=> Fix building w/o `github-actions` maven profile; Ensure JVM 8 compatiblity with JDK9+

src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
=> Fix a NoSuchMethodError that can occur on 1.15

src/com/palmergames/bukkit/towny/war/common/WarZoneListener.java
=> Warzone Listener Able to Query null PlayerCache.

src/com/palmergames/bukkit/towny/event/damage/TownyDispenserDamageEntityEvent.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java, src/com/palmergames/bukkit/towny/utils/CombatUtil.java
Fixes a few todo's regarding cancelling dispenser damage, and fixes an accidental double inversion. Also adds a new TownyDispenserDamageEntityEvent that is used while checking.
____
____
____
=> Handle dispenser damage correctly

resources/english.yml, src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
=> Send a warning if /tw toggle is used when usingtowny is false.

src/com/palmergames/bukkit/towny/TownyAsciiMap.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/event/asciimap/WildernessMapEvent.java, src/com/palmergames/bukkit/towny/object/map/TownyMapData.java
=> Creates a cache of sorts for the wilderness coords on the Towny ASCII map.

LICENSE.md
____
____
- Closes #5038 (superceding it.)
____
=> Update License.md to include the full text.

src/com/palmergames/bukkit/towny/utils/CombatUtil.java
- Alter non-player vs non-player combat:
- In the wilderness it is allowed.
- If it is a tamed wolf, and the owner is online, and the owner can destroy in the plot where the defender non-player is, and the non-player is a protected entity, the wolf murdering other non-players is allowed.
- Closes #5059.
____
____
____
=> Be more lenient with non-player vs non-player damage in the wilderness.

pom.xml, resources/english.yml, resources/plugin.yml, src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/TownyUpdateChecker.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java, src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java, src/com/palmergames/bukkit/towny/tasks/UpdateCheckerTask.java, src/com/palmergames/bukkit/util/Version.java
Automatically checks for updates on startup, and notifies players with the update notifications permission node when logging in (if enabled)
____
New permission node: towny.admin.updatealerts
New config node: plugin.update_notifications.alerts
- default: true
- If enabled, players with the towny.admin.updatealerts permission will receive an update notification upon logging in.
New config node: plugin.update_notifications.major_only
- default: true
- If enabled, only full releases will trigger notifications if you are running a full release.
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced …
=> New version checker

resources/english.yml, src/com/palmergames/bukkit/towny/TownyAsciiMap.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java
=> Allows for plots to be claimed by clicking the $ on the ascii map.

resources/english.yml, src/com/palmergames/bukkit/towny/command/PlotCommand.java
... if the town is open and the townblock is not an embassy plot.
____
____
- Closes #4019.
____
=> Add ability for a nomad to be prompted to a join a town when they /plot claim... 

README.md
=> Add 1.17 to the readme

src/com/palmergames/bukkit/towny/command/TownCommand.java
Quick fix for an index out of bounds being thrown when there are no additional arguments to `/t unclaim`.
=> Fix index out of bounds for /t unclaim.

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/object/economy/GovernmentAccountAuditor.java
Implements the ability to configure the design of the bankhistory command's book design.
____
```YAML
BANKHISTORY( 
"bank_history", 
"", 
"", 
"", 
"  ############################################################", 
"  # +------------------------------------------------------+ #", 
"  # |                 Bank History settings                | #", 
"  # +------------------------------------------------------+ #", 
"  ############################################################", 
""), 
BANKHISTORY_BOOK( 
"bank_history.book", 
"{time}\n\n{type} of {amount} {to-from} {name}\n\nReason: {reason}\n\nBalance: {amount}", 
"", 
"# This allows you to modify the style displayed via bankhistory commands." 
), 
```
____
____
By making this pull request, I represent that I have the right to waive …
=> Implemented basic configuration format for audit history

src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
=> Fix canBlockMove always allowing wilderness

src/com/palmergames/bukkit/towny/listeners/TownyInventoryListener.java, src/com/palmergames/bukkit/towny/utils/PermissionGUIUtil.java
Adds a tutorial book to the bottom right of the permission GUI to make it easier for players to understand the basics of the new system. 
____
____
____
=> Add a tutorial book for the plot perm GUI

src/com/palmergames/bukkit/towny/command/TownCommand.java
Removes an unneeded permission check when running /t list, since permission checks are already done in the listTowns function.
Players with nodes for comptypes but not the towny.command.town.list.* node will now be able to run /t list by without problem. 
____
____
____
=> Remove unneeded permission check

src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
Protects doors from being breakable by zombies/vindicators inside towns.
____
____
____
=> Prevent zombies breaking doors in claimed areas.

src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Resident.java, src/com/palmergames/bukkit/towny/object/Town.java
=> Add some new getOrNull methods

resources/english.yml, src/com/palmergames/bukkit/config/CommentedConfiguration.java
=> Print yaml exception message if a file breaks formatting

src/com/palmergames/bukkit/towny/war/common/townruin/TownRuinUtil.java
=> Fix NPE when a town ruins

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java
Expands the output of `/towny universe`, as well as the output for `Towny#checkPlugins()` if the following plugins are found to be present on the server:
- TownyCamps
- TownyCultures
- TownyHistories
- FlagWar
- SiegeWar
____
n/a
____
n/a
____
=> Errata: Expand checkPlugin() and `/towny universe` output

src/com/palmergames/bukkit/towny/command/PlotCommand.java
Some error catch blocks were missing return statements which allowed the code to continue executing even though it shouldn't have.
____
=> Fix some fall-throughs in PlotCommand

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/config/migration/ConfigMigrator.java, src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/TownyTimerHandler.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/db/TownyDataSource.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java, src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java, src/com/palmergames/bukkit/towny/listeners/TownyServerListener.java, src/com/palmergames/bukkit/towny/object/Translation.java, src/com/palmergames/bukkit/towny/object/metadata/MetadataLoader.java, src/com/palmergames/bukkit/towny/permissions/GroupManagerSource.java, src/com/palmergames/bukkit/towny/tasks/BackupTask.java, src/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java, src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java, src/com/palmergames/util/FileMgmt.java
Replaces all uses of System.out/err with getLogger().info/warn
____
____
____
=> Replace all sysouts

src/com/palmergames/bukkit/towny/object/Translation.java
Makes it so you no longer need to hardcode in lang file names to the Translation object to check for lang names.
____
____
____
=> Scan the lang directory inside the jar to get lang file names

.github/CONTRIBUTING.MD
Update the "Updating Language Files" section to reflect the transition to Crowdin.
The old contents of this section were commented.
____
____
____
=> Update "Updating Language Files"

README.md
=> Update readme for the new release.

src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
- Adds the ability to rename towns and nations that do not pass name
validation.
- Flatfile only.
- Towns which are given a replacement name will carry over their
townblocks and residents.
- Nations which are given a replacement name will carry over their
towns.
- Should squash the last remaining common safemode cause.
____
____
____
=> Feature: Automatic name replacing

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/db/DatabaseConfig.java
- Migrates relevant settings from the config.yml to the database.yml, retaining drag-and-drop updating.
- TODO: more testing, initial testing is good though.
____
____
Closes #5175 
____
=> Creates database.yml

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/hooks/LuckPermsContexts.java
=> Make context calculation faster

src/com/palmergames/bukkit/towny/command/ResidentCommand.java
=> Check if resident is friended before sending removal message.

resources/lang/en-US.yml, src/com/palmergames/bukkit/towny/conversation/ResidentConversation.java, src/com/palmergames/bukkit/towny/conversation/TownyConversation.java, src/com/palmergames/bukkit/towny/listeners/TownyInventoryListener.java, src/com/palmergames/bukkit/towny/utils/PermissionGUIUtil.java
This PR adds a new "Add Player" option to the /plot perm gui screen, allowing players to add default permission overrides by typing the name in chat. 
After click:
____
____
____
=> Add prompts

src/com/palmergames/bukkit/towny/event/damage/TownyFriendlyFireTestEvent.java, src/com/palmergames/bukkit/towny/utils/CombatUtil.java
Added friendly fire test event for regional friendly fire option for plugins. They can do it with TownyPlayerDamagePlayerEvent but it will still show "Friendly Fire is disabled!" to players so yeah.
____
____
____
=> Add Friendly fire test event

src/com/palmergames/bukkit/towny/command/PlotCommand.java
=> Add missing owner test

.github/workflows/compile-on-push.yml, .github/workflows/deploy-on-release.yml, pom.xml, src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java, src/com/palmergames/bukkit/towny/listeners/TownyInventoryListener.java, src/com/palmergames/bukkit/towny/object/gui/EditGUI.java, src/com/palmergames/bukkit/towny/utils/CombatUtil.java
Adds jabel, which allows us to use java 16 features while keeping support for java 8
____
____
____
=> Raise language level to 16 using jabel

resources/lang/en-US.yml, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/object/Nation.java
- Also adds a better language string to the king of the remaining
nation.
- Also renames methods to be clearer, removes ability to throw
TownyException.
____
____
____
=> Fixes nation merging not doing the proximity check, returning null.

src/com/palmergames/bukkit/towny/object/Resident.java, src/com/palmergames/bukkit/util/BukkitTools.java
=> Add Resident#isOnline

src/com/palmergames/bukkit/towny/TownyMessaging.java
=> Prevent empty messages from being sent

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/listeners/TownyServerListener.java
=> Disable citizens compatability if citizens gets disabled.

src/com/palmergames/bukkit/towny/object/Translation.java
=> Fix plugin disabling if something is translated before fully loading translations.

resources/lang/en-US.yml, src/com/palmergames/bukkit/towny/TownyAPI.java, src/com/palmergames/bukkit/towny/TownyMessaging.java, src/com/palmergames/bukkit/towny/command/BaseCommand.java, src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java, src/com/palmergames/bukkit/towny/object/Translatable.java, src/com/palmergames/bukkit/towny/permissions/TownyPermissionSource.java, src/com/palmergames/bukkit/util/BukkitTools.java
* Players can now use /tw worldname like console can, with working tab completions
* Added /tw toggle wildernessuse
* Removed tab completions for /tw regen and /tw undo
____
____
____
=> Modernise /townyworld

src/com/palmergames/bukkit/towny/db/TownySQLSource.java
=> Use deprecated driver if needed

src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
=> Temporary fix for grass remaining snowy

.github/workflows/compile-on-push.yml
=> Make github actions not build commits from the crowdin branch

resources/lang/en-US.yml, resources/plugin.yml, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/conversation/SetupConversation.java, src/com/palmergames/bukkit/towny/conversation/TownyConversation.java
Adds a /ta install command, that allows server owners to set some basic config options in seconds.
____
____
____
=> Add a /ta install command

src/com/palmergames/bukkit/towny/object/Translation.java
=> Prevent spam if a player's locale is invalid.

src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
=> Change PlayerCacheUtil to once again check for a fakeplayer resident.

README.md, resources/ChangeLog.txt, src/com/palmergames/bukkit/config/CommentedConfiguration.java, src/com/palmergames/bukkit/towny/TownyAPI.java, src/com/palmergames/bukkit/towny/TownyLogger.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/confirmations/ConfirmationHandler.java, src/com/palmergames/bukkit/towny/tasks/TownClaim.java, src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java
Fixes my username being spelt wrong everywhere.
Removes old outpost code that was also implemented back when mysql didn't store outposts correctly.
____
Nope
____
Nope
____
=> Remove old Outpost code and fix my names.

src/com/palmergames/bukkit/towny/command/PlotCommand.java
=> Prevent outlaws from being able to join towns.

src/com/palmergames/bukkit/towny/tasks/CleanupTask.java, src/com/palmergames/util/FileMgmt.java
Fixes the CleanupTask so that it points towards a folder that actually exists
____
____
____
=> Fix backup cleaning not working

resources/lang/en-US.yml, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/db/SQL_Schema.java, src/com/palmergames/bukkit/towny/db/TownyDataSource.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/event/town/TownAddAlliedTownEvent.java, src/com/palmergames/bukkit/towny/event/town/TownAddEnemiedTownEvent.java, src/com/palmergames/bukkit/towny/event/town/TownRemoveAlliedTownEvent.java, src/com/palmergames/bukkit/towny/event/town/TownRemoveEnemiedTownEvent.java, src/com/palmergames/bukkit/towny/object/Town.java, src/com/palmergames/bukkit/towny/utils/CombatUtil.java
These are persistant entries in the database, which populate enemy and
ally lists for towns. The lists are viewable via `/t allylist
{townname}` and `/t enemylist {townname}`. The CombatUtil has been
modified to account for towns being enemied.
So far, these are used in EventWar for the TownWar and CivilWar war
types.
Adds 4 new cancel-able events for adding and removing allies and enemies from towns.
Adds 2 methods used specifically for loading allies and enemies (which bypass the cancel-able events.)
Drawbacks/design choices:
There is no way to set enemy and ally lists in game however, it is all
handled via the API. I am fairly happy with this limitation, I feel
exposing it ingame would take away from nations too much.
____
____
Closes #3476.
____
By making this pull request, I …
=> Add ally and enemy lists to Towns.

src/com/palmergames/bukkit/towny/ChunkNotification.java, src/com/palmergames/bukkit/towny/event/player/PlayerCacheGetTownBlockStatusEvent.java, src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
Enables another plugin to alter Towny's pre-determined TownBlockStatus,
used in the PlayerCache to determine the outcome of Towny's plot
permissions.
____
____
____
=> API: Add PlayerCacheGetTownBlockStatusEvent

src/com/palmergames/bukkit/towny/TownyMessaging.java
=> Fix variable name in javadoc

src/com/palmergames/bukkit/towny/TownyAPI.java, src/com/palmergames/bukkit/towny/object/Translation.java
=> Add ability to add translation strings apart from the LoadTranslationEvent.

resources/lang/en-US.yml, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/object/economy/Account.java, src/com/palmergames/bukkit/towny/object/economy/BankAccount.java
Implemented a baltop book view for town and nations.
Closes #4795 
____
`/town baltop <name>`
`/nation baltop <name>`
____
https://github.com/TownyAdvanced/Towny/issues/4795
____
=> Implemented town and nation baltops

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/event/nation/NationSetSpawnEvent.java, src/com/palmergames/bukkit/towny/event/town/TownSetSpawnEvent.java
=> Add events for when a town/nation spawn is set.

src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/event/plot/toggle/PlotToggleEvent.java, src/com/palmergames/bukkit/towny/event/plot/toggle/PlotToggleExplosionEvent.java, src/com/palmergames/bukkit/towny/event/plot/toggle/PlotToggleFireEvent.java, src/com/palmergames/bukkit/towny/event/plot/toggle/PlotToggleMobsEvent.java, src/com/palmergames/bukkit/towny/event/plot/toggle/PlotTogglePvpEvent.java
=> Add a TownBlock getter to PlotToggle events

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java
Parse the baltops for nations and towns and display them asynchronously, it otherwise causes huge lagspikes in large servers.
____
____
____
=> Parse baltops asynchronously

resources/lang/en-US.yml
Implements new lang keys for TownyChat.
Requires merging with https://github.com/TownyAdvanced/TownyChat/pull/34
____
____
____
=> Implemented new TownyChat lang messages

src/com/palmergames/bukkit/towny/event/plot/changeowner/PlotChangeOwnerEvent.java
=> Fix exception when running /plot claim

src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Town.java
=> Fix nation spawns not being cleared when a capital changes.

resources/lang/en-US.yml, src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java
=> Make the outsiders prevent pvp toggle apply to plots.

src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/command/ResidentCommand.java
=> Show online status for console when running /res.

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/object/Nation.java
=> Set the nation spawn to the town's spawn on creation.

src/com/palmergames/bukkit/towny/utils/SpawnUtil.java
____
____
Closes https://github.com/EarthMC/Issue-Tracker/issues/1427
____
=> Fix outlaws teleporting into towns they're outlawed in using /n spawn.

src/com/palmergames/bukkit/towny/object/Resident.java
=> Fix surname formatting.

src/com/palmergames/bukkit/towny/command/PlotCommand.java
=> Make the outsiders prevent pvp option apply to arenas aswell

src/com/palmergames/bukkit/towny/command/NationCommand.java
Fixes players getting an exception message instead of the /nation set help menu when running /nation set without any args.
99% of the diff is from the if statement being unwrapped.
____
____
____
=> Fix /nation set oobe.

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/TownyTimerHandler.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java, src/com/palmergames/bukkit/towny/tasks/NewDayScheduler.java
This pull request changes the way the new day timer is handled. Previously the new day was scheduled once on server startup, resulting in a delayed new day if the server has low TPS. The worse the tps, the worse the delay.
This PR changes the DailyTimerTask to be run by the NewDayScheduler. When the NDS is run, it re-calculates the next new day time, and if it is less than 2 minutes from now, it schedules the DailyTimerTask to run. If it is longer than 2 minutes from the next new day, the NewDayScheduler will run itself again in half of the time-to-new-day. Credit to silverwolfg11 with coming up with this idea a while ago.
If a server starts up with 12 hours until the new day it will run the scheduler at startup and then at 6h>3h>1h30m>45m>22m30s>11m15s>5m37s>2m48s>1m24s at which point it …
=> NewDay timer overhaul.

src/com/palmergames/bukkit/towny/object/economy/BankAccount.java
=> Fix possible npe when checking bankrupt status.

src/com/palmergames/bukkit/towny/object/Nation.java
=> Remove redundant nationSpawn variable

resources/lang/en-US.yml, src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/object/SpawnLocation.java, src/com/palmergames/bukkit/towny/object/statusscreens/StatusScreen.java
=> Add web map integration to status screens

src/com/palmergames/bukkit/util/ItemLists.java
=> Make the ItemLists class not an interface

src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/event/DeleteTownEvent.java
=> Fix the delete town event causing an NPE in edge cases.

src/com/palmergames/bukkit/towny/permissions/TownyPermissionSource.java
=> Fix javadoc warning

resources/lang/en-US.yml, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/db/TownyDataSource.java
I've added a command to ta so that admins can (force)merge towns and nations now.
____
`/ta <town|nation> <name> <merge|forcemerge> <other name>`
____
#5489
____
=> Add admin merge commands for nations and towns

src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Town.java
The main purpose of this PR is to move several methods from TownySettings into Town and Nation. Old methods point to the new ones, and have been marked deprecated. Additional getter methods have been introduced to facilitate these changes, and may be of use to plugins.
As part of a general-purpose clean-up, multiple changes were applied in 8091126e7e688c064c56142acf99dc2528c621e4. Most of these focus on readability and code quality, such as avoiding potential null-pointer exceptions. There should be no discernable difference in functionality, aside from speed discernable only during benchmarking. Some cleanup tasks were not attempted, as they are not presently compatible with Jabel.
____
- Town:
- Introduce `#getLevel()`, `#getLevel(int)`, `#getLevelID()`and `#getMaxLevel()`.
- Nation:
- …
=> Reorganization and cleanup of Town, Nation, and TownySettings

src/com/palmergames/bukkit/towny/event/PreNewTownEvent.java
=> Add 2 convenience methods to PreNewTownEvent

src/com/palmergames/bukkit/towny/command/BaseCommand.java
=> Fix possible tab completion NPE

src/com/palmergames/bukkit/towny/listeners/TownyVehicleListener.java, src/com/palmergames/bukkit/util/ItemLists.java
Expands the list of blocks that can kill a minecart to Cactus and Lava_Cauldron, which are a new ItemLists called MINECART_KILLERS.
____
____
Closes #5503.
____
=> Allow lava_cauldrons to kill minecarts.

src/com/palmergames/bukkit/towny/command/TownCommand.java
=> Call the pre new town event after any confirmations are confirmed.

src/com/palmergames/bukkit/towny/object/Translation.java
=> Replace underscores on override lang keys properly.

resources/lang/en-US.yml, src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/object/Translation.java
Allow translation of the "real-life money" warning that is shown when the console gives bonus townblocks to an player. To prevent server admins from removing this message, I added checks to the `Translation` class, which skips overrides for these strings.
____
____
____
=> Translate Console givebonus warning

src/com/palmergames/bukkit/towny/command/TownCommand.java
=> Fix a typo in a lang key use

src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java, src/com/palmergames/bukkit/towny/utils/EntityTypeUtil.java
____
____
https://github.com/EarthMC/Issue-Tracker/issues/1445
____
=> Prevent the theft of axolotls

src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/object/TownBlock.java, src/com/palmergames/bukkit/towny/object/TownBlockType.java, src/com/palmergames/bukkit/towny/object/TownBlockTypeHandler.java, src/com/palmergames/bukkit/towny/utils/TownRuinUtil.java
=> Replaces Towny's own usages of the deprecated getType() methods.

src/com/palmergames/bukkit/util/ItemLists.java
Fixes the minecart names in ItemLists, fixes chest minecart protection for servers running the default config
____
____
____
=> Fix minecart names in ItemLists

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/object/TownBlock.java, src/com/palmergames/bukkit/towny/object/TownBlockType.java, src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
Mainly comments and javadocs, but also undoing a variable change in
PlotCommand.
____
____
____
=> Cleanup on custom_types branch.

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/object/TownBlock.java, src/com/palmergames/bukkit/towny/object/TownBlockType.java
=> Adjust version reference from 0.97.5.3 to 0.97.5.4.

src/com/palmergames/bukkit/towny/db/SQL_Schema.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java
TownBlock types are now saved to a new typeName column, leaving the old type column intact until next release, in case someone has to downgrade their towny version.
____
____
____
=> Fix for SQL schema and new townblock type-saving.

src/com/palmergames/bukkit/config/CommentedConfiguration.java, src/com/palmergames/util/StringMgmt.java
~~Requires testing done on old spigot versions, paper but~~ this works fine on cutting-edge spigot builds and old builds.
____
____
____
=> Redo commented configuration to fix things up for latest Spigot changes.

src/com/palmergames/bukkit/towny/TownyAPI.java, src/com/palmergames/bukkit/towny/object/Translation.java, src/com/palmergames/bukkit/towny/object/TranslationLoader.java
TranslationLoader:
An object which allows a plugin to load language files into Towny's
translations hashmap. Enabling the given plugin to use Towny's built-in
messaging and translating so that messages will display in the player's own
Locale (determined by the client's locale setting.)
Language files should be saved in your plugin's resources\lang\ folder, using
valid Locale file names ie: en-US.yml, de-DE.yml. Locales which do not appear
in Minecraft will not be used.
You may opt to provide a global.yml file in your plugin's resources folder,
which will allow an admin to globally override language strings for all
locales.
Example: 
```java
Plugin plugin = Towny.getPlugin(); 
Path langFolderPath = Paths.get(plugin.getDataFolder().getPath()).resolve("lang");
TranslationLoader loader = new …
```
=> API: Add TranslationLoader, an easy-to-use class that loads Translations into Towny.

src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java, src/com/palmergames/bukkit/towny/listeners/TownyServerListener.java, src/com/palmergames/bukkit/towny/listeners/TownyVehicleListener.java, src/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java, src/com/palmergames/bukkit/towny/utils/EntityTypeUtil.java
=> Refactor some listener code.

src/com/palmergames/bukkit/towny/utils/CombatUtil.java
=> Fix entities being able to steal items from item frames.

src/com/palmergames/bukkit/towny/command/TownyCommand.java
=> Fix OOBE in the towny top command.

src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java
Add support for new PAPI placeholders for town status public and open.
____
=> Add PAPI placeholder for town public/open status

src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java
Added `%townyadvanced_player_location_plot_forsale%` placeholder.
____
____
Closes https://github.com/TownyAdvanced/Towny/issues/5220
____
=> Added forsale placeholder

resources/lang/en-US.yml, src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
This pull request sends an message to new players to indicate the locale system for Towny. It might be useful for people that haven't played Towny before (or the new releases that have the `Translatable` system. It could also be used when translating, or finding translation errors.
____
____
____
=> Add locale info message

resources/lang/en-US.yml, src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
=> Remove global registration message

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/object/TownBlockTypeHandler.java, src/com/palmergames/bukkit/towny/object/Translation.java, src/com/palmergames/bukkit/towny/object/TranslationLoader.java
- Skips putting the invalid languages into memory at all, filtering out
invalid languages from being loaded, made into reference files and being
loaded into the override langs.
- Removes unused imports in TownBlockTypeHandler.
- Adds config comments explaining how to enter in enabled languages.
- Add code to filter out .yml in locales when people invariably skip
reading the above comments.
____
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for …
=> Filter out undesired languages in the TranslationLoader

pom.xml, resources/config-migration.json, src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java, src/com/palmergames/bukkit/towny/utils/CombatUtil.java, src/com/palmergames/bukkit/towny/utils/EntityTypeUtil.java
=> Fix skeletons not hurting mobs inside claimed areas.

src/com/palmergames/bukkit/config/migration/ConfigMigrator.java
Make migrations aware of true migration count.
Clean up unused imports.
____
____
____
=> ConfigMigrator Additions

resources/config-migration.json, src/com/palmergames/bukkit/config/migration/ConfigMigrator.java, src/com/palmergames/bukkit/config/migration/MigrationType.java, src/com/palmergames/bukkit/towny/Towny.java
Adds a new migration type, that allows us to change the path of a config option while preserving the value.
____
____
____
=> New migration type: Move

src/com/palmergames/bukkit/towny/event/player/PlayerDeniedBedUseEvent.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Cancellable event when Towny denies a player using a bed.
____
____
#5608.
____
=> API: add PlayerDeniedBedUseEvent

src/com/palmergames/bukkit/towny/utils/CombatUtil.java, src/com/palmergames/bukkit/towny/utils/EntityTypeUtil.java
=> Make wolves inside towns mortal again.

src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/object/metadata/CustomDataField.java
Allow metadata labels and values to be components. This is intentionally added as two methods to maintain backwards compatibility and to allow child classes to override that method appropriately.
____
Tested on a local server with a simple test plugin that adds metadata through normal routes. I don't have the other Towny plugins that use metadata installed, so if someone who already has all of that setup wants to test and make sure that they still work that would be much appreciated.
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution …
=> Add component support to Metadata Labels and Values

src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/command/HelpMenu.java, src/com/palmergames/bukkit/towny/command/TownCommand.java
____
/t trust list
____
Closes #5615 
____
=> Add list subcommand to /town trust.

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/db/SQL_Schema.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java
~~Just want to double check that mysql servers handle the removal of the old column.~~
____
____
____
=> Remove player crop trampling world setting, in favour of using plot permissions.

src/com/palmergames/bukkit/towny/command/TownCommand.java
=> Fix /t trust remove not working.

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/command/ResidentCommand.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/object/Resident.java, src/com/palmergames/bukkit/towny/object/gui/EditGUI.java
Map is keyed by UUID instead of a String.
____
____
____
=> Change PlayerCache Map to use UUIDs instead of Names.

resources/lang/en-US.yml, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java, src/com/palmergames/bukkit/towny/tasks/NewDayScheduler.java
=> Fix newday being scheduled again after running /ta newday

src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/utils/ResidentUtil.java
=> Improve /ta town townname kick name feedback.

src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java, src/com/palmergames/bukkit/towny/listeners/TownyServerListener.java, src/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java, src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java, src/com/palmergames/bukkit/util/BukkitTools.java
... preventing many Towny operations from completing successfully.
____
____
____
=> Do a better job of catching when Citizens API is unavailable to us,

src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/object/TownBlockData.java, src/com/palmergames/bukkit/towny/object/TownBlockTypeHandler.java
Switches the itemuse, switch and allowedblocks lists over to EnumSets instead of a regular set.
____
____
____
=> Use EnumSet for switch and itemuse materials.

src/com/palmergames/bukkit/towny/TownyCommandAddonAPI.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
=> Add TOWNYADMIN_RELOAD commandtype.

src/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java
=> Fix mob removal task malfunctioning when using citizens.

src/com/palmergames/bukkit/util/ChatTools.java, src/com/palmergames/bukkit/util/Colors.java
This solves for hex codes breaking the formatTitle and formatSubtitle in ChatTools.
____
____
Closes #5680.
____
=> Switch over to ChatColor's colour-stripping.

src/com/palmergames/bukkit/towny/object/Government.java, src/com/palmergames/bukkit/towny/object/Nation.java, src/com/palmergames/bukkit/towny/object/Resident.java, src/com/palmergames/bukkit/towny/object/Town.java
Implements ForwardingAudience on government and resident, for some nice to have methods. Will be nice to have for #5672 and potentially other areas.
Allows us to use .sendMessage directly on resident, town and nation objects, including all other Audience methods.
____
____
____
=> Implement ForwardingAudience on government and resident.

src/com/palmergames/bukkit/towny/object/metadata/ByteDataField.java, src/com/palmergames/bukkit/towny/utils/MetaDataUtil.java
=> Clear errer in metadataloader, fill out metadatautil.

src/com/palmergames/bukkit/towny/object/metadata/ByteDataField.java, src/com/palmergames/bukkit/towny/object/metadata/MetadataLoader.java, src/com/palmergames/bukkit/towny/object/metadata/TownyCDFDeserializer.java, src/com/palmergames/bukkit/towny/utils/MetaDataUtil.java
=> Create a new Byte datafield.

src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/event/town/TownTrustAddEvent.java, src/com/palmergames/bukkit/towny/event/town/TownTrustRemoveEvent.java
=> Fix command feedback when using trust commands via console.

src/com/palmergames/bukkit/towny/command/TownyCommand.java
=> Fix /towny plotclearblocks always saying that towny is disabled.

src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
=> Remove assertions from flatfile source.

src/com/palmergames/bukkit/config/migration/ConfigMigrator.java, src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/TownyAPI.java, src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/command/BaseCommand.java, src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/command/ResidentCommand.java, src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java, src/com/palmergames/bukkit/towny/db/TownyDataSource.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/event/PlayerChangePlotEvent.java, src/com/palmergames/bukkit/towny/huds/HUDManager.java, src/com/palmergames/bukkit/towny/object/Town.java, src/com/palmergames/bukkit/towny/object/WorldCoord.java, src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java, src/com/palmergames/bukkit/towny/tasks/TownClaim.java, src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java
Moves a lot of code that is in the TownyDataSource into the TownyAPI, all getters are deprecated and will be removed come 0.99.0.0
____
____
____
=> Pre 0 98 0 0 deprecations

src/com/palmergames/bukkit/config/ConfigNodes.java, src/com/palmergames/bukkit/towny/TownyFormatter.java, src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/command/TownCommand.java, src/com/palmergames/bukkit/towny/object/Town.java, src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java
=> Add possibility for towns to have unlimited claims.

README.md, pom.xml
=> Update readme for new release

src/com/palmergames/bukkit/config/CommentedConfiguration.java, src/com/palmergames/bukkit/towny/db/DatabaseConfig.java
Adding line.trim().isEmpty() to the CommentedConfiguration solves the
new lines.
Change in DatabaseConfig are logic-related.
Not sure how this wasn't having an effect on the main config.
____
____
____
=> Fixes database and townyperms files growing new lines.

src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java, src/com/palmergames/bukkit/towny/utils/SpawnUtil.java
Replaces all uses of Player#getBedSpawnLocation with paperlib's async one. (except one, technically)
____
____
____
=> Get bed spawn locations async in SpawnUtil

resources/lang/en-US.yml, src/com/palmergames/bukkit/config/migration/WorldMigrationAction.java, src/com/palmergames/bukkit/towny/TownySettings.java, src/com/palmergames/bukkit/towny/command/PlotCommand.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java, src/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java
Apparently much faster.
Redo /plot clear to parse over the TownBlock a single time, apparently
much faster also.
____
____
____
=> Enumsets for townyworld

src/com/palmergames/bukkit/towny/object/TownyWorld.java
=> Fix explosion revert entities regression

src/com/palmergames/bukkit/config/ConfigNodes.java
- Small nonfunctional blurb updatem as SiegeWar no longer has the referenced type of invasion system.
____
Na
____
Na
____
- [  Na ] I have tested this pull request for defects on a server. 
=> Small Blurb Update

src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
=> Fix not being able to replace null mayors with /ta set mayor.

src/com/palmergames/util/FileMgmt.java
=> Fix long file names causing exceptions when backing up.

src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java, src/com/palmergames/util/StringMgmt.java
=> Convert legacy entity names to the new format.

src/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java
=> Add workaround for watchdog crashes causing problems.

src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java, src/com/palmergames/bukkit/towny/object/TownyWorld.java
Fixes /tw set usedefault causing an npe, and also makes /tw set wildperm a bit less strict.
____
____
____
=> Fix /tw set usedefault causing an NPE.

pom.xml, src/com/palmergames/bukkit/towny/Towny.java, src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java, src/com/palmergames/bukkit/util/Colors.java, src/com/palmergames/util/StringMgmt.java
Drops support for MC 1.14 and 1.15.
____
____
____
=> Set minimum MC version to 1.16.

resources/lang/en-US.yml, resources/plugin.yml, src/com/palmergames/bukkit/towny/command/ResidentCommand.java, src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java, src/com/palmergames/bukkit/towny/object/Resident.java, src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java, src/com/palmergames/bukkit/towny/utils/MetaDataUtil.java, src/com/palmergames/bukkit/towny/utils/ResidentUtil.java
Sets whether a resident see border Title messages (using_titles in the
config.)
____
____
Closes #5767.
____
=> Adds /res toggle bordertitles

src/com/palmergames/bukkit/config/migration/ConfigMigrator.java, src/com/palmergames/bukkit/config/migration/MigrationType.java
=> API: Allow other plugins to use ConfigMigrator & REMOVE MigrationType.

src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
=> Fix water being able to be placed in waterloggable blocks on plot borders.

src/com/palmergames/bukkit/towny/command/NationCommand.java, src/com/palmergames/bukkit/towny/event/nation/NationPreAddAllyEvent.java
This PR adds a cancellable `NationPreAddAllyEvent` event that is called before a nation sends an ally request or allies with an NPC nation. This is similar to the existing `NationPreAddEnemyEvent`.
____
N/A
____
N/A
____
=> Add NationPreAddAllyEvent

src/com/palmergames/bukkit/towny/permissions/TownyPerms.java
=> Update townyperms comment

src/com/palmergames/bukkit/towny/TownyUniverse.java, src/com/palmergames/bukkit/towny/db/TownyDataSource.java, src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java, src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java, src/com/palmergames/bukkit/towny/db/TownySQLSource.java, src/com/palmergames/bukkit/towny/hooks/LuckPermsContexts.java, src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
=> Improve hibernated residents loading

src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java, src/com/palmergames/util/TimeMgmt.java
Adds new placeholders relating to time until a new day, which can be useful for linking up with other plugins, such as DeluxeMenus, and having a different item depending on how much time is left in the towns day, or a warning if there is less than x amount of time left in a day. 
Added Placeholders:
`%townyadvanced_time_until_new_day_hours_raw% - Display the raw number of hours until new day.`
`%townyadvanced_time_until_new_day_minutes_raw% - Display the raw number of minutesuntil new day.`
`%townyadvanced_time_until_new_day_seconds_raw% - Display the raw number of seconds until new day.`
`%townyadvanced_time_until_new_day_formatted% - Display the amount of time until a new day, formatted and translated.`
`%townyadvanced_time_until_new_day_hours_formatted% - Display the amount of hours …
=> New time-related placeholders till New Day

src/com/palmergames/bukkit/towny/command/TownCommand.java
=> Open baltop book synchronously

src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java, src/com/palmergames/bukkit/towny/TownyTimerHandler.java, src/com/palmergames/bukkit/towny/command/TownyCommand.java, src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java, src/com/palmergames/bukkit/towny/object/Translation.java, src/com/palmergames/bukkit/towny/tasks/NewDayScheduler.java, src/com/palmergames/util/TimeMgmt.java
Related to #5856
____
____
____
=> Cache towny time

src/com/palmergames/bukkit/towny/Towny.java
=> Add descriptive error if Towny is being shaded.
