src/com/palmergames/bukkit/towny/command/BaseCommand.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
src/com/palmergames/bukkit/towny/utils/ResidentUtil.java
src/com/palmergames/bukkit/util/BukkitTools.java

Protect invisible player from town add tab completes.

---

src/com/palmergames/bukkit/towny/listeners/TownyLoginListener.java

Changes it so the AsyncPlayerPreLoginEvent is used rather than the PlayerLoginEvent for checking player's usernames.
____
____
____

Check player name async on login

---

src/com/palmergames/bukkit/towny/command/NationCommand.java

Show ally requests to players with accept permissions.

---

src/com/palmergames/bukkit/towny/TownyFormatter.java

Fix runCommand for plots button

---

src/com/palmergames/bukkit/towny/command/TownCommand.java

Add player name to /t claim withdraw reason

---

src/com/palmergames/bukkit/towny/TownyTimerHandler.java
src/com/palmergames/bukkit/towny/event/MobRemovalEvent.java
src/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java

Make the mob removal task partially async

---

src/com/palmergames/bukkit/towny/TownyMessaging.java

____
____
Related to #5893
____

Handle different Objects which aren't CommandSenders in the main sendErroMsg method.

---

src/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java

Fix potential comod error during mob removal

---

src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/event/PreNewTownEvent.java

Uses the spawn location that will actually be used, instead of the player's location. The Player#getLocation can be inacurrate if the player was sent a confirmation and moved before actually confirming it.
____
____
____

Improve accuracy of PreNewTownEvent#getTownLocation

---

src/com/palmergames/bukkit/towny/TownyMessaging.java

Undeprecate and rework one of the sendMessage() methods.

---

.github/workflows/compile-on-push.yml
.github/workflows/deploy-on-release.yml
.github/workflows/label-on-pr.yml

Update actions versions

---

src/com/palmergames/bukkit/towny/TownyMessaging.java
src/com/palmergames/bukkit/towny/command/TownCommand.java

Small change to showing costs to spawn in lists.

---

src/com/palmergames/bukkit/towny/TownyFormatter.java

Small fix to capital hover on nation status screen.

Fix hover on nation capital on nation status screen.

---

src/com/palmergames/bukkit/towny/TownySettings.java
src/com/palmergames/bukkit/towny/object/Translation.java

Fix possible stackoverflow exception for translations

---

src/com/palmergames/bukkit/towny/object/comparators/GovernmentComparators.java
src/com/palmergames/bukkit/towny/object/economy/Account.java

Makes the GovernmentComparator for comparing bank balances not touch the
economy plugin, by never being the reason the Account's CachedBalance is
considered stale.
Solves an issue experienced by a server, for which there's no other
discern-able reason. 
This stops the economy plugin potentially being inundated with cache updates on /t list and /n list.
____
____
____

Protect the economy plugin being asked for bank balances during listing.

---

src/com/palmergames/bukkit/config/ConfigNodes.java
src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java

Protect borders from sculk spread, if the server is using a new enough version of spigot, which has fixed the API.

---

README.md

Fix README typo re: 1.19 version number

---

src/com/palmergames/bukkit/towny/command/TownCommand.java

Check if economy is enabled in town plots command

---

src/com/palmergames/bukkit/towny/event/executors/TownyActionEventExecutor.java
src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

Handles filling/emptying of buckets or bottles, washing, and extinguishing using the CauldronLevelChangeEvent instead of only handling a few via the player interact event.
____
Closes https://github.com/EarthMC/Issue-Tracker/issues/1549
____

Handle more kinds of changes to cauldrons

---

resources/lang/en-US.yml
src/com/palmergames/bukkit/towny/command/NationCommand.java
src/com/palmergames/bukkit/towny/command/TownCommand.java

Replace the ugliest feedback message I ever used.

---

src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
src/com/palmergames/bukkit/towny/object/Resident.java

Add Resident#getAccountOrNull

---

src/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java
src/com/palmergames/bukkit/towny/object/TownyWorld.java
src/com/palmergames/bukkit/towny/utils/CombatUtil.java

Make townyworld's trident strike list use uuid instead of eid

---

src/com/palmergames/bukkit/util/NameValidation.java

Add baltop as banned name

---

pom.xml
src/com/palmergames/bukkit/towny/Towny.java
src/com/palmergames/bukkit/towny/TownyUniverse.java
src/com/palmergames/bukkit/towny/object/TownyObject.java
src/com/palmergames/util/StringMgmt.java

Adds an exclusion for Vault's bukkit api in our pom & replaces commons lang usages with the guava equavalents. commons lang was removed from the spigot api in 1.19, but due to vault it was still included for us.
____
____
____

Exclude transitive bukkit api dependency

---

src/com/palmergames/bukkit/towny/TownyFormatter.java
src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java
src/com/palmergames/bukkit/towny/TownySettings.java
src/com/palmergames/bukkit/towny/object/Nation.java
src/com/palmergames/bukkit/towny/object/economy/BankAccount.java

Replace town/nation levels with records

---

resources/lang/en-US.yml
resources/plugin.yml
src/com/palmergames/bukkit/towny/TownySettings.java
src/com/palmergames/bukkit/towny/command/NationCommand.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/object/comparators/ComparatorCaches.java
src/com/palmergames/bukkit/towny/object/comparators/ComparatorType.java
src/com/palmergames/bukkit/towny/object/comparators/GovernmentComparators.java

Adds a new upkeep comparator type, also adds a few short circuits to the upkeep methods in TownySettings
____
Adds the towny.command.nation.list.upkeep and towny.command.town.list.upkeep permission nodes
____
Closes #5964 
____

Add upkeep comparator type

---

src/com/palmergames/util/StringMgmt.java

Fixes a NoSuchMethodError when running 1.16 by adding our own string wrap implementation
____

Create our own wrapper impl

---

src/com/palmergames/bukkit/towny/object/Translation.java

Makes it easier to debug lang file formatting errors by printing the translated text, lang key, arguments & stacktrace to console instead of the player just receiving the exception message.
____
Closes #6036 
____

Make it easier to debug lang file formatting errors

---

src/com/palmergames/bukkit/towny/command/NationCommand.java
src/com/palmergames/bukkit/towny/command/TownCommand.java

Fix /t deposit & /n deposit running sync

---

resources/lang/en-US.yml
src/com/palmergames/bukkit/towny/command/PlotCommand.java

Include the plot price in the /plot fs feedback message

---

src/com/palmergames/bukkit/towny/command/PlotCommand.java

Ensure player gets feedback message when setting a group for sale

---

src/com/palmergames/bukkit/towny/command/PlotCommand.java

Re-check group set cost after confirmation is accepted

---

src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

Add null check to teleport listener

---

pom.xml

Updates adventure-platform-bukkit to 4.1.2, which has support for 1.19.1.
____

Update platform bukkit to 4.1.2

---

src/com/palmergames/bukkit/towny/object/Translator.java

Add Translator#component

---

src/com/palmergames/bukkit/towny/TownyFormatter.java
src/com/palmergames/bukkit/towny/event/statusscreen/StatusScreenEvent.java

Adds new component methods to status screen events and changes how lines are added to the screen via the event.
____
Closes #6087 
____

Add component support for status screen events

---

src/com/palmergames/bukkit/towny/TownyFormatter.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/event/town/toggle/TownToggleExplosionEvent.java
src/com/palmergames/bukkit/towny/object/Town.java

Renames the town "BANG" methods to something simpler
____

Rename town explosion methods

---

pom.xml
src/com/palmergames/bukkit/towny/TownyMessaging.java
src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
src/com/palmergames/bukkit/towny/object/Translatable.java
src/com/palmergames/bukkit/towny/utils/TownyComponents.java

Add TownyComponents class

---

src/com/palmergames/bukkit/towny/TownyAsciiMap.java
src/com/palmergames/bukkit/towny/event/asciimap/WildernessMapEvent.java

Makes the ascii map use components for the compass/legend and uses Translator#component wherever possible.
____

Make the ASCII map fully use components

---

pom.xml
src/com/palmergames/bukkit/util/ChatTools.java

Handle bold characters in titles using pixelwidth

---

src/com/palmergames/bukkit/towny/command/PlotCommand.java

Allow /plot set name to be used on plots in groups

---

src/com/palmergames/bukkit/towny/TownyMessaging.java

Re-directs TownyMessaging from having many end points for messages, into
the sendMessage(Sender, String) method.
Having a singular end-point for all messaging will make it easier to
colour/minimessage things, and allow for more consistency.
____
____
Supercedes #6109 
____

Reflow TownyMessaging

---

src/com/palmergames/bukkit/towny/TownyFormatter.java
src/com/palmergames/bukkit/towny/TownyMessaging.java
src/com/palmergames/bukkit/towny/object/statusscreens/StatusScreen.java

Adds status screen changes from the minimessage branch, which fixes a few possible formatting issues.
The status screen will now append the entire component (if it fits) instead of appending each child of the component one by one, which fixes spaces being added between child components.
This PR also fixes style bleeding by appending everything to an empty component.
____

Add status screen changes from minimessage branch

---

src/com/palmergames/bukkit/towny/TownyAPI.java
src/com/palmergames/bukkit/towny/TownyUniverse.java
src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
src/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java
src/com/palmergames/bukkit/towny/object/Town.java
src/com/palmergames/bukkit/towny/object/TownBlock.java
src/com/palmergames/bukkit/towny/object/TownyWorld.java
src/com/palmergames/bukkit/towny/object/WorldCoord.java
src/com/palmergames/bukkit/util/BukkitTools.java

A selection of changes to bring in from the UUID branch.

---

src/com/palmergames/bukkit/towny/TownyUniverse.java
src/com/palmergames/bukkit/towny/db/TownyDataSource.java
src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
src/com/palmergames/bukkit/towny/db/TownySQLSource.java
src/com/palmergames/bukkit/towny/object/ObjectGroup.java
src/com/palmergames/bukkit/towny/object/Town.java
src/com/palmergames/bukkit/util/BukkitTools.java

Adopt plot group .id to .uuid changes.

---

resources/lang/en-US.yml
src/com/palmergames/bukkit/towny/TownyFormatter.java

Replace Component.texts with alternatives in formatter.

---

resources/lang/en-US.yml
src/com/palmergames/bukkit/towny/TownyMessaging.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/object/comparators/ComparatorCaches.java
src/com/palmergames/bukkit/towny/object/metadata/CustomDataField.java
src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java

Remove instances of legacy making it into components

---

src/com/palmergames/bukkit/towny/TownyMessaging.java
src/com/palmergames/bukkit/towny/object/economy/GovernmentAccountAuditor.java
src/com/palmergames/bukkit/towny/tasks/UpdateCheckerTask.java
src/com/palmergames/bukkit/util/BookFactory.java

Replace ChatColor.stripColor uses with Colors.strip

---

src/com/palmergames/bukkit/towny/object/economy/Account.java

Add a catch to Account's constructor

---

pom.xml
src/com/palmergames/bukkit/towny/TownyAsciiMap.java
src/com/palmergames/bukkit/towny/TownyFormatter.java
src/com/palmergames/bukkit/towny/TownyMessaging.java
src/com/palmergames/bukkit/towny/command/NationCommand.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
src/com/palmergames/bukkit/towny/object/Translatable.java
src/com/palmergames/bukkit/towny/object/metadata/CustomDataField.java
src/com/palmergames/bukkit/towny/object/statusscreens/StatusScreen.java
src/com/palmergames/bukkit/towny/utils/TownyComponents.java
src/com/palmergames/bukkit/util/ChatTools.java
src/com/palmergames/bukkit/util/Colors.java
src/com/palmergames/util/StringMgmt.java

____
____
Supersedes #5672 
____

MiniMessage!

---

src/com/palmergames/bukkit/towny/Towny.java
src/com/palmergames/bukkit/towny/permissions/VaultPermSource.java

Fallback to another Vault chat implementation if an invalid one is detected

---

src/com/palmergames/bukkit/towny/object/TranslationLoader.java

Fixes an issue with new reference file creation that was introduced in #6146.
____

Fix new reference file creation not working

---

src/com/palmergames/bukkit/towny/object/Resident.java

Use getPlayerExact for resident#getPlayer

---

src/com/palmergames/bukkit/towny/command/TownCommand.java

Use town sing translation in TownCommand

---

src/com/palmergames/bukkit/towny/TownyAPI.java

Add TownyAPI#getTown(Player)

---

src/com/palmergames/bukkit/towny/TownyAPI.java

Make TownyAPI#getOnlinePlayers(ResidentList) thread safe

---

src/com/palmergames/util/StringMgmt.java

Fix legacy hex code parsing not working

---

src/com/palmergames/bukkit/towny/TownyMessaging.java
src/com/palmergames/bukkit/towny/command/BaseCommand.java
src/com/palmergames/bukkit/towny/command/TownCommand.java

Simplify parameters used for TownCommand title & surname methods

---

src/com/palmergames/bukkit/towny/object/SpawnPoint.java
src/com/palmergames/bukkit/towny/tasks/DrawSpawnPointsTask.java

Catch exceptions from spawn point particle spawning

---

src/com/palmergames/bukkit/towny/TownyAPI.java

API: Add TownyAPI#getNation(Player)

---

src/com/palmergames/bukkit/towny/TownyMessaging.java
src/com/palmergames/bukkit/util/ChatTools.java

Replace ChatTools.stripColour with Colors.strip

---

src/com/palmergames/bukkit/towny/command/NationCommand.java
src/com/palmergames/bukkit/towny/command/PlotCommand.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/confirmations/Confirmation.java
src/com/palmergames/bukkit/towny/confirmations/ConfirmationBuilder.java
src/com/palmergames/bukkit/towny/confirmations/ConfirmationHandler.java
src/com/palmergames/bukkit/towny/confirmations/ConfirmationTransaction.java
src/com/palmergames/bukkit/towny/utils/TownRuinUtil.java

This bakes-in the ability for a Confirmation to require an account to pay a set amount of funds for the Accepted confirmation to proceed.
____
____
____

Add a ConfirmationTransaction to Confirmations.

---

src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/util/BukkitTools.java

Adds a BukkitTools#isEventCancelled convenience method for quickly calling an event and checking whether it was cancelled.
____

Add BukkitTools#isEventCancelled

---

src/com/palmergames/bukkit/util/BukkitTools.java

Use getPlayerExact for BukkitTools#isOnline

---

src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java

Adds /townyadmin town new townname npc, which allows admins to create npc towns without having to leave their own town, create a new town, set mayor of new town to an npc, leave the town town & join their own town back.
____
Closes #6205
____

Add /townyadmin town new townname npc

---

src/com/palmergames/bukkit/towny/event/resident/ResidentToggleModeEvent.java
src/com/palmergames/bukkit/towny/object/Resident.java

Adds a new ResidentToggleModeEvent that is called when a player uses /res toggle \<mode>, and can be used by plugins to decide whether the mode will be toggled or not.
____

Add ResidentToggleModeEvent

---

src/com/palmergames/bukkit/towny/utils/EntityTypeUtil.java

Protects players from end crystal damage in areas with pvp disabled by adding it to the ExplosivePVPEntityTypes list.
____

Protect against ender crystal damage in pvp disabled areas.

---

src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java

Remove resident as trusted in towns/plots upon deletion

---

src/com/palmergames/bukkit/towny/event/damage/TownBlockExplosionTestEvent.java
src/com/palmergames/bukkit/towny/event/executors/TownyActionEventExecutor.java

This PR implements a new event, `TownBlockExplosionTestEvent`, that allows developers to override Towny's decision on whether to allow explosions in a townblock. This is similar in principle to the existing `TownBlockPVPTestEvent`. 
(Not sure whether this is the best way to go about this, but it does work) 
____
____
#5970
____

Add TownBlockExplosionTestEvent

---

src/com/palmergames/bukkit/towny/TownySettings.java

Use toLowerCase(Locale.ROOT) in TownySettings

---

src/com/palmergames/bukkit/towny/TownyFormatter.java

Hide tax component on status screens if taxes are off.

---

src/com/palmergames/bukkit/util/ItemLists.java

https://minecraft.fandom.com/wiki/Java_Edition_22w42a#Experimental_Additions
____
____
____

Add bamboo raft to boats item list

---

pom.xml

Bump Jabel to 1.0.0

---

.github/labeler.yml

Specify .github/workflows/ directory for CI/CD label

---

src/com/palmergames/bukkit/towny/TownyUpdateChecker.java
src/com/palmergames/bukkit/towny/tasks/UpdateCheckerTask.java

Make UpdateCheckerTask implement runnable

---

src/com/palmergames/bukkit/towny/ChunkNotification.java
src/com/palmergames/bukkit/towny/TownyFormatter.java
src/com/palmergames/bukkit/towny/TownyMessaging.java
src/com/palmergames/bukkit/towny/command/PlotCommand.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
src/com/palmergames/bukkit/towny/permissions/BukkitPermSource.java
src/com/palmergames/bukkit/towny/permissions/GroupManagerSource.java
src/com/palmergames/bukkit/towny/permissions/TownyPermissionSource.java
src/com/palmergames/bukkit/towny/permissions/TownyPerms.java
src/com/palmergames/bukkit/towny/utils/CombatUtil.java
src/com/palmergames/bukkit/util/BukkitTools.java

Supersedes #5494 
____
____
____

Use getPlayerExact in more places

---

src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

Fix lecterns requiring destroy perms to open.

---

src/com/palmergames/bukkit/towny/event/actions/TownyActionEvent.java
src/com/palmergames/bukkit/towny/event/executors/TownyActionEventExecutor.java

Fix action event isMessageSupressed method

---

src/com/palmergames/annotations/Unmodifiable.java
src/com/palmergames/bukkit/towny/TownyUniverse.java
src/com/palmergames/bukkit/towny/object/TownyObject.java

Replaces our unmodifiable annotation with the jetbrains unmodifiable annotation so that inspections work.
____
____
____

Replace unmodifiable annotation with jetbrains equivalent

---

src/com/palmergames/bukkit/towny/command/PlotCommand.java
src/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java

Minor regen api refactor

---

.github/CONTRIBUTING.MD

Copied from the original PR at #6251:
> It's the time of my triyearly PR! This pull request reformats the `CONTRIBUTING.md` file by: 
> - Fixing grammar errors.
> - Simplifying rules, making them easier to understand.
> - Simplifying sections, removing redundant content.
> - Make use of new GFM features like footnotes.
> - Remove commented out section (pre-crowdin translation)
____
____
____

Reformat Contributing (Reopened)

---

src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java

PAPI: Add %townyadvanced_nation_or_town_name%

---

src/com/palmergames/bukkit/towny/listeners/TownyLoginListener.java

Fix NPE on startup

---

src/com/palmergames/bukkit/towny/TownySettings.java
src/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java

Reduces duplicate code.
Makes NPC-based mobs cause environmental kills and potentially cost the player money.
____
____
____

Refactor EntityMonitorListener

---

src/com/palmergames/bukkit/towny/TownySettings.java

Created this branch a while ago but seems like I never created a pull request for it. Removes a redundant isWilderness check in favour of a != null so that IJ stops warning about it technically being nullable.
____

Remove redundant isWilderness check

---

resources/plugin.yml

Fix broken yaml in plugin.yml

---

src/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
src/com/palmergames/bukkit/towny/permissions/TownyPerms.java

Use method handles in townyperms

---

src/com/palmergames/bukkit/towny/TownyAsciiMap.java

Make ascii map symbol options reloadable

---

src/com/palmergames/bukkit/towny/object/metadata/CustomDataFieldType.java
src/com/palmergames/bukkit/towny/object/metadata/LocationDataField.java
src/com/palmergames/bukkit/towny/object/metadata/MetadataLoader.java
src/com/palmergames/bukkit/towny/object/metadata/TownyCDFDeserializer.java
src/com/palmergames/bukkit/towny/utils/MetaDataUtil.java

Allows for easy storing and loading of Locations in TownyObject metadata.
____
____
____

Add new MetaDataType: Location

---

src/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java

Use the world's wild revert delay

---

src/com/palmergames/bukkit/towny/event/PlayerLeaveTownEvent.java

getLefttown() changed to getLeftTown()
____
____
____
- [ x] I have tested this pull request for defects on a server. 

Fix typo in PlayerLeaveTownEvent

---

resources/plugin.yml
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java

Doing so will allow a player to deposit money into any town bank.
This feature will require an admin to give the node to their players in the townyperms.yml, it is disabled by default.
____
New command node: /t deposit {amount} {townname}
New permission node: towny.command.town.deposit.othertown, not a child node of towny.command.town.deposit.
____
Closes #6346.
____

Make it possible to use /t deposit amount townname

---

src/com/palmergames/bukkit/towny/command/TownyWorldCommand.java

Fix possible /tw set wildname NPE

---

src/com/palmergames/bukkit/towny/object/economy/BankTransaction.java

Also changed the constructor to a regular long, since it should never be null.
____
____
____

Expose unformatted time in BankTransaction

---

src/com/palmergames/bukkit/towny/Towny.java
src/com/palmergames/bukkit/towny/TownyAPI.java
src/com/palmergames/bukkit/towny/TownyAsciiMap.java
src/com/palmergames/bukkit/towny/TownyPlaceholderExpansion.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
src/com/palmergames/bukkit/towny/event/executors/TownyActionEventExecutor.java
src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
src/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java
src/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java
src/com/palmergames/bukkit/towny/utils/CombatUtil.java

Lookup towny worlds via uuid

---

src/com/palmergames/bukkit/towny/TownyAPI.java

Temporarily use name for world lookups again

---

src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
src/com/palmergames/bukkit/towny/regen/PlotBlockData.java
src/com/palmergames/util/FileMgmt.java

Add support for plotsnapshots made with MC 1.19 and newer, saving plotblockdata below y level 1.
Snapshots now save down to the world bottom.
Older snapshots are loaded and have a min height of 0 set, which allows them to be regenerated with the same code as newer snapshots.
We now split up snapshots knowing the correct vertical range, which allows us to find the correct start and end point for each x,z "slice" of the snapshot.
PlotBlockData version has been "documented" and versions 3 and lower will no longer be loaded, as these used id:data or a type:data-to-material hack to work. This has resulted in many of the switch statements being removed entirely.
PlotBlockData version 5 now stores a minHeight int, similar to the height int. If we are loading a version 5 plot snapshot we pull the …

Support for y less than 0 for revert-on-unclaim.

---

pom.xml
resources/ChangeLog.txt
resources/plugin.yml
src/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
src/com/palmergames/bukkit/towny/utils/SpawnUtil.java

Nodes that allow special people to bypass spawning to nation-towns or allied-nation's-towns which are not public and public has been required in the config.
____
- New Permission Nodes:
- towny.town.spawn.nation.bypass_public:
- description: User is permitted to use /town spawn when:
- they are a member of the same nation and, 
- the town isn't public and, 
- is_nation_ally_spawning_requiring_public_status is true.
- default: false, and not a child node of towny.town.spawn.* 
- towny.town.spawn.ally.bypass_public: 
- description: User is permitted to use /town spawn when:
- they are a member of an allied nation and,
- the town isn't public and,
- is_nation_ally_spawning_requiring_public_status is true. 
- default: false, and not a child node of towny.town.spawn.* 
- Give either of these …

bypasspublic town spawn nodes

---

src/com/palmergames/bukkit/towny/event/BankTransactionEvent.java
src/com/palmergames/bukkit/towny/event/NationPreTransactionEvent.java
src/com/palmergames/bukkit/towny/event/NationTransactionEvent.java
src/com/palmergames/bukkit/towny/event/PlayerEnterTownEvent.java
src/com/palmergames/bukkit/towny/event/PlayerLeaveTownEvent.java
src/com/palmergames/bukkit/towny/event/PlotChangeOwnerEvent.java
src/com/palmergames/bukkit/towny/event/TownPreTransactionEvent.java
src/com/palmergames/bukkit/towny/event/TownTransactionEvent.java
src/com/palmergames/bukkit/towny/event/TownyPreTransactionEvent.java
src/com/palmergames/bukkit/towny/event/TownyTransactionEvent.java

Replaces the "server performance will be affected" warning with the one we've defined
____
____
____

Use bukkit warning annotation for our deprecated events

---

src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

Ignore end portal respawns

---

src/com/palmergames/bukkit/config/ConfigNodes.java
src/com/palmergames/bukkit/towny/TownySettings.java
src/com/palmergames/bukkit/towny/command/TownCommand.java

Add min distance options for new towns

---

src/com/palmergames/bukkit/towny/Towny.java
src/com/palmergames/bukkit/towny/command/TownyCommand.java
src/com/palmergames/bukkit/towny/hooks/PluginIntegrations.java
src/com/palmergames/bukkit/towny/hooks/TownyPlaceholderExpansion.java
src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
src/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java
src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
src/com/palmergames/bukkit/towny/listeners/TownyServerListener.java
src/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java
src/com/palmergames/bukkit/towny/utils/MoneyUtil.java
src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
src/com/palmergames/bukkit/util/BukkitTools.java

Centralize 3rd Party plugin usage into new PluginIntegrations class, removing overhead from within the Towny class.
Startup's 3rd party plugin information about permissions, economy, addons and warnings is also handled here.
/towny universe command also sources a more complete TownyAdvanced/Sponsor plugins list from here.
Some 3rd party plugin methods in Towny.java have been deprecated as well but no one ought to have been using them. These will return false.
BukkitTools#checkCitizens has been deprecated with the method pointing at the replacement method.
TownyPlaceholderExpansion has been moved to the hooks package.
~~Adds our own suggestPaper.~~
____
____
Supercedes/Closes #6350
____
By making this pull request, I represent that I have the right to waive copyright and related rights to …

Add PluginIntegrations class.

---

resources/lang/en-US.yml
src/com/palmergames/bukkit/towny/TownyMessaging.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
src/com/palmergames/bukkit/towny/object/TownBlock.java
src/com/palmergames/bukkit/towny/tasks/TownClaim.java
src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java

- Changes it from using Thread to Runnable.
- Probably fixes a unclaim refund exploit.
- Clearer comments.
- More readable code.
- Fix refunds for /t unclaim all.
____
____
____

Give TownClaim some TLC

---

src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java

Fix paintings and item frames being unbreakable.

---

src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java

Add tab complete for /ta nation recheck

---

resources/lang/en-US.yml
src/com/palmergames/bukkit/towny/command/NationCommand.java
src/com/palmergames/bukkit/towny/object/Nation.java

Add confirmation to /n set capital

---

src/com/palmergames/bukkit/towny/hooks/PluginIntegrations.java
src/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
src/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java

Checks for elitemobs meta in entities.
____
____
____

Add support for EliteMobs mob removal.

---

src/com/palmergames/bukkit/towny/TownyAPI.java
src/com/palmergames/bukkit/towny/db/SQL_Schema.java
src/com/palmergames/bukkit/towny/db/TownyDataSource.java
src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
src/com/palmergames/bukkit/towny/db/TownySQLSource.java
src/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java
src/com/palmergames/bukkit/towny/object/TownyWorld.java

Feature/world UUID loading

---

src/com/palmergames/bukkit/towny/command/NationCommand.java
src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java

Replace some hardcoded town and nation strings with translatables

---

src/com/palmergames/bukkit/towny/command/BaseCommand.java

Returns a regular list instead of an unmodifiable one in order to prevent an exception if something is added.
[line 343/344 of TownCommand](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/command/TownCommand.java#L343)
____
____
____

Fix exception when tab completing /t jail with no town

---

src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java

Might still want to handle falling blocks as well.
____
____
Closes #6470.
____

Prevent liquid spilling in actively regenerating plots which were unclaimed.

---

src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java

Fix /ta forcemerge having swapped town names in message

---

src/com/palmergames/bukkit/towny/command/PlotCommand.java
src/com/palmergames/bukkit/towny/huds/PermHUD.java
src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
src/com/palmergames/bukkit/towny/object/TownBlock.java
src/com/palmergames/bukkit/towny/object/TownyWorld.java
src/com/palmergames/bukkit/towny/object/WorldCoord.java
src/com/palmergames/bukkit/towny/regen/PlotBlockData.java

Replace world with weakref in WorldCoord

---

src/com/palmergames/bukkit/towny/object/WorldCoord.java

Fix worldcoord from location parsing

---

src/com/palmergames/bukkit/towny/command/TownCommand.java

Fix /t claim doing economy calls on the main thread

---

pom.xml
resources/config-migration.json
resources/townyperms.yml
src/com/palmergames/bukkit/towny/command/NationCommand.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/permissions/TownyPerms.java

Adds a 'peaceful' section to the townyperms.yml, which is given out to peaceful players.
____
____
Closes #6015.
____

Add set of nodes that are given to peaceful players.

---

src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

See issue linked below
____
____
Fix for #6494 
____

Fix switch and item use being triggered on left-click

---

src/com/palmergames/bukkit/towny/TownyAPI.java
src/com/palmergames/bukkit/towny/TownyAsciiMap.java
src/com/palmergames/bukkit/towny/TownySettings.java
src/com/palmergames/bukkit/towny/chat/types/AllyType.java
src/com/palmergames/bukkit/towny/chat/types/NationType.java
src/com/palmergames/bukkit/towny/chat/types/TownType.java
src/com/palmergames/bukkit/towny/chat/variables/NationVariable.java
src/com/palmergames/bukkit/towny/chat/variables/TownVariable.java
src/com/palmergames/bukkit/towny/command/BaseCommand.java
src/com/palmergames/bukkit/towny/command/HelpMenu.java
src/com/palmergames/bukkit/towny/command/NationCommand.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
src/com/palmergames/bukkit/towny/db/TownySQLSource.java
src/com/palmergames/bukkit/towny/huds/MapHUD.java
src/com/palmergames/bukkit/towny/huds/PermHUD.java
src/com/palmergames/bukkit/towny/object/Nation.java
src/com/palmergames/bukkit/towny/object/Resident.java
src/com/palmergames/bukkit/towny/object/Town.java
src/com/palmergames/bukkit/towny/utils/TownRuinUtil.java

- Many getNation() and getTown() calls are replaced when safe to do so.
- Add BaseCommand#getNationFromTownOrThrow(Town).
- Fix up nomads that own plots not colouring in the ascii maps.
____
____
____

Reduce potential NotRegisteredException calls using newer methods.

---

src/com/palmergames/bukkit/towny/tasks/PlotClaim.java

Fix claiming free plots causing useless bank history

---

src/com/palmergames/bukkit/towny/object/Resident.java
src/com/palmergames/bukkit/towny/object/TownBlock.java

Only remove non embassies from the left town on resident leave

---

resources/lang/en-US.yml
src/com/palmergames/bukkit/towny/TownyAsciiMap.java
src/com/palmergames/bukkit/towny/command/BaseCommand.java
src/com/palmergames/bukkit/towny/command/NationCommand.java
src/com/palmergames/bukkit/towny/command/PlotCommand.java
src/com/palmergames/bukkit/towny/command/ResidentCommand.java
src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
src/com/palmergames/bukkit/towny/command/TownyCommand.java
src/com/palmergames/bukkit/towny/huds/HUDManager.java
src/com/palmergames/bukkit/towny/huds/MapHUD.java
src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
src/com/palmergames/bukkit/towny/utils/MoneyUtil.java
src/com/palmergames/bukkit/towny/utils/OutpostUtil.java
src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
src/com/palmergames/bukkit/towny/utils/TownRuinUtil.java

Replace code that throws NotRegisteredExceptions.
Replace messaging used by BaseCommand's getOrThrow methods to be more relevant to players.
Replace getResidentOrThrow(UUID) with getResidentOrThrow(Player) for better feedback messages.
____
____
____

Minor changes to reduce NRE usage.

---

src/com/palmergames/bukkit/towny/object/Government.java
src/com/palmergames/bukkit/towny/object/economy/BankAccount.java
src/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java

Creates a Government field for BankAccounts, so getting the Town is more reliable.
Deprecates old constructor that set a balanceCap.
Fixes getBalanceCap() to use the new dynamic caps. Correctly limits bankruptcy to when Bankruptcy is enabled.
____
____
____

Bank Account update

---

src/com/palmergames/bukkit/towny/event/economy/TownEntersBankruptcyEvent.java
src/com/palmergames/bukkit/towny/object/economy/BankAccount.java

Thrown when a town enters bankruptcy.
____
____
____

API: TownEntersBankruptcyEvent

---

pom.xml

Update paper repo url

---

src/com/palmergames/bukkit/towny/command/PlotCommand.java
src/com/palmergames/bukkit/towny/event/plot/PlayerChangePlotTypeEvent.java

Thrown when a player successfully changes a plot's TownBlockType.
____
____
____

API: Add PlayerChangePlotTypeEvent

---

src/com/palmergames/bukkit/towny/db/TownySQLSource.java

Fixes an NPE that can sometimes occur when using SQL, this PR prevents the query queue being polled concurrently which could happen if polling took more than 5 ticks (100ms)
____
Closes #6514
____

Fix sql source query NPE

---

src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java

Fix /ta set mayor causing an npe if the old mayor is null

---

src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

Closes #6530 
____
____
#6530 
____

Fix pressure plates not respecting switch permissions

---

src/com/palmergames/bukkit/towny/Towny.java
src/com/palmergames/bukkit/towny/TownySettings.java
src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
src/com/palmergames/bukkit/towny/exceptions/TownyException.java

Make town and nation level related errors easier to debug

---

src/com/palmergames/bukkit/towny/tasks/BackupTask.java
src/com/palmergames/util/FileMgmt.java

Changes the folder structure in the tar backups to remove the plugins/Towny part of the path from being included.
Also removes a catch in the method so that the IOException is properly thrown to the BackupTask
____

Relativize paths in tar.gz backups

---

src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java

Fixes sync economy calls being done in the OnPlayerLogin task and fixes up a few IDE warnings.
____

Fix upkeep warning message doing sync economy calls

---

src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/tasks/TownClaim.java

Fix unclaim refunds doing sync economy calls

---

src/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java

Fix backups for windows

---

src/com/palmergames/bukkit/towny/command/PlotCommand.java
src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
src/com/palmergames/bukkit/towny/confirmations/ConfirmationBuilder.java
src/com/palmergames/bukkit/towny/object/Translatable.java
src/com/palmergames/bukkit/towny/utils/MoneyUtil.java

Fix some Translatable.toString issues

---

src/com/palmergames/bukkit/towny/db/FlatFileSaveTask.java
src/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
src/com/palmergames/util/FileMgmt.java

Path.of(String) should hopefully be the equivalent of new File(String)
____
____
____

Slightly improve mapToFile

---

src/com/palmergames/bukkit/towny/Towny.java
src/com/palmergames/bukkit/towny/object/ChangelogResult.java
src/com/palmergames/bukkit/towny/utils/ChangelogReader.java
src/com/palmergames/util/JavaUtil.java

Adds a seperate class for changelog reading for use in plugins that use the same changelog format as towny (i.e. addon/sponsor plugins). Also fixes version numbers not being yellow in towny's changelog.
____

Seperate changelog reading into its own class

---

src/com/palmergames/bukkit/towny/listeners/TownyLoginListener.java

Fixes npc prefixed usernames not always being blocked, which can cause issues.
____

Fix NPC prefixed usernames not being blocked

---

pom.xml
src/com/palmergames/bukkit/util/ItemLists.java

Hardest update I've ever done
____

Update to 1.19.4

---

src/com/palmergames/bukkit/towny/Towny.java
src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
src/com/palmergames/bukkit/towny/utils/MinecraftVersion.java

Protects signs from being edited by players with no permission, uses an item use test for waxing and a destroy test for editing.
https://www.minecraft.net/en-us/article/minecraft-snapshot-23w12a
____

Protect signs from being edited

---

src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java

Remove leftover debug stdout

---

src/com/palmergames/bukkit/towny/object/EconomyAccount.java
src/com/palmergames/bukkit/towny/object/Government.java
src/com/palmergames/bukkit/towny/object/economy/Account.java
src/com/palmergames/bukkit/towny/object/economy/BankAccount.java
src/com/palmergames/bukkit/towny/object/economy/TownyServerAccount.java

Fix up some missed stuffs

---

src/com/palmergames/bukkit/towny/hooks/TownyPlaceholderExpansion.java
src/com/palmergames/bukkit/towny/object/Resident.java
src/com/palmergames/bukkit/towny/permissions/TownyPerms.java

Adds %townyadvanced_resident_primary_rank%
Adds:
- Resident#getHighestPriorityTownRank
- Resident#getHighestPriorityNationRank
- Resident#getPrimaryRankPrefix
- TownyPerms#getResidentPrimaryRankPrefix
- TownyPerms#getHighestPriorityRank
____
____
Closes #4658
____

Add a rank-prefix, rank-priority system to Townyperms.

---

src/com/palmergames/bukkit/towny/command/TownCommand.java
src/com/palmergames/bukkit/towny/event/town/TownMayorChangeEvent.java
src/com/palmergames/bukkit/towny/event/town/TownMayorChangedEvent.java
src/com/palmergames/bukkit/towny/event/town/TownMayorChosenBySuccessionEvent.java
src/com/palmergames/bukkit/towny/object/Town.java

- Alters the TownMayorChangeEvent to include a getCommandSender.
- Add TownMayorChangedEvent which is not cancellable, alerts plugins of any change in mayor.
- Add TownMayorChosenBySuccessionEvent which allows a plugin to determine who will become mayor when Towny automatically chooses a mayor.
- Closes #6607.
____
____
____

API: Add town-changing mayor events.

---

src/com/palmergames/bukkit/towny/event/town/TownMayorChosenBySuccessionEvent.java

Fix NPE when finding a new mayor

---

resources/config-migration.json
src/com/palmergames/bukkit/config/migration/ConfigMigrator.java

Adds a migration for an old town level that was added in a version that predates the config migrator. Makes for a smoother experience for people migrating a very old config.
____

Add a migration for adding an old town level

---

src/com/palmergames/bukkit/util/ChatTools.java

Fix legacy format subtitle out of bounds

---

src/com/palmergames/bukkit/towny/TownyFormatter.java

Display mayor as none if town has no mayor

---

src/com/palmergames/bukkit/towny/db/SQLSchema.java
src/com/palmergames/util/FileMgmt.java

Purpose of this PR is to properly close sql resources and file resources when there is an error throw.  Previously, there was no code in the try except blocks that would close the resources.  By not closing these resources automatically, this can lead to a memory leak, issues with server files, or resource exhaustion.  Due to the simplicity of the try with resources functionality, this was used to automatically release the resources back to the system.
____
____
____ …

Cleanup Resources in Error

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java

Since I was only searching for Bukkit.getScheduler uses this one seems to have slipped past
____

Take care of a missed bukkit scheduler use

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java

Adds Folia to the bstats server type chart, forks of Paper will also no longer show up as Unknown.
____

Add Folia to bstats server type chart

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
Towny/src/main/java/com/palmergames/util/JavaUtil.java

Adds support for spigot's new tnt prime event so that those who for some reason haven't switched to paper yet can enjoy the benefits of TNT being protected from flaming player projectiles. Also makes the get origin and get primer entity method handles static & final so that these can be inlined, resulting in a slightly faster speed.
____

Support spigot's tnt prime event

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/UpdateCheckerTask.java
Towny/src/main/java/com/palmergames/bukkit/util/Version.java

Add some more readable convenience methods to Version

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java

Removes the first arg from the args that are passed into the nationTransaction method, similar to what happens with townTransaction in the TownCommand
____

Remove first arg for nation transaction method

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyAPI.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/huds/PermHUD.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java
Towny/src/main/resources/lang/en-US.yml

- Add admin setting for towns: forcemobs
- Used to force mobs on in a town.
____
- New Command: /ta town TOWNNAME toggle forcemobs.
____
- Closes #6659.
____

Add admin setting for towns: forcemobs

---

providers/BaseProviders/pom.xml
providers/FoliaProvider/pom.xml

Setup jabel for the provider modules

---

Towny/pom.xml
pom.xml

Fixes "build is platform dependent" warnings during compilation by moving the sourceEncoding property into the root pom.xml, so that it is applied automatically to every child module.
____

Set source encoding utf-8 for all modules

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/util/NameValidation.java
Towny/src/main/java/com/palmergames/util/TimeTools.java
Towny/src/test/java/com/palmergames/bukkit/towny/test/NameValidationTests.java
Towny/src/test/java/com/palmergames/bukkit/towny/test/TimeTests.java

Adds some more generic tests
____

Add some more tests

---

Towny/src/main/java/com/palmergames/util/Trie.java
Towny/src/test/java/com/palmergames/bukkit/towny/test/TrieTests.java

Closes https://github.com/EarthMC/Issue-Tracker/issues/1644
____

Fix trie insertion order weirdness

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java

Refactor the main class a bit

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/CooldownTimerTask.java

Changes the cooldown task to use a string key instead of an entry to avoid creating a new object every time a cooldown is checked. Also changes the hasCooldown to add an additional check for whether the cooldown is still actually active, to prevent -1 cooldowns being shown in some edge cases.
____

Use a proper key for the cooldowns map

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyLoginListener.java

The config is now loaded BEFORE the class is instanced so the reload listener is no longer triggered.
____

Fix login npe regression

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

Fix another NPE caused by listener registration change

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyAPI.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/WorldCoord.java

Most important performance change this century
____

Marginally faster town or null

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/CommandList.java
Towny/src/test/java/com/palmergames/bukkit/towny/test/CommandListTests.java

Changes our commandlist implementation to be more trie-like and allow subcommands to be blocked.
Blocking a root command i.e. /town will block any town subcommands, blocking a subcommand will not block the root command or any other sub commands.
This PR does remove the ability to only block commands in a specific namespace, since I don't think it was ever all too useful to begin with.
____
Closes #6642
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) …

Allow subcommands to be blocked

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java

Fix the seventh null mayor npe

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/comparators/GovernmentComparators.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/comparators/NationComparators.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/comparators/TownComparators.java

Use a more suitable comparator for our caches

---

Towny/src/main/java/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java

Fix exception when using negative radius for a circle claim

---

Towny/src/main/java/com/palmergames/bukkit/towny/invites/InviteHandler.java

Makes the invite handler use a concurrent hashmap to fix a CME that I came across, also removes a redundant set.
____

Use a concurrent hashmap for invite handler invites

---

Towny/src/main/java/com/palmergames/bukkit/towny/hooks/PluginIntegrations.java

Removes the part about installing vault/reserve if it's already running on the server.
____

Remove 'install vault' recommendation if it's present

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/PlayerCache.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java

Makes a few small improvements to some of the player cache related code.
____

minor improvements to player cache

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyEconomyHandler.java

I couldn't find any other uses so I hope these are the last, getPlayerExact is preferred because it doesn't do partial matches.
____

replace last use of non-get player exact

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
Towny/src/main/resources/lang/en-US.yml

Happening in advance of negative tax support being added, requested in #6705.
Mainly un-nesting code, extracting methods to un-nest code.
Adds clearer messaging that will appear in the bankhistory books and new messages displaying how much tax is collected by the towns and nations.
____
____
____

Refactor Town and Nation tax collection

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

Checking whether a task is currently queued involves iterating through all tasks until it's found so by skipping that we have a small improvement in performance.
____

Skip is warmup task running for movement

---

Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/resources/plugin.yml

Fix cooldown loading exception message on first startup

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/AbstractRegistryList.java
Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java
Towny/src/main/java/com/palmergames/bukkit/util/ItemLists.java

Port ItemList changes from enum branch

---

Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java

Cleanup the mob removal task

---

Towny/src/main/java/com/palmergames/bukkit/towny/utils/TownRuinUtil.java

Fixes an NPE if the town being reclaimed has a null mayor, and also fixes a few IDE warnings in the same file.
____

Fix possible reclaimTown NPE

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java

Fixes up isTownyUpdating to only be true when the new version is newer than the last run version so that it doesn't try to print changelogs for downgrades.
____

Fix changelog warning message when downgrading

---

Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/HelpMenu.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/time/dailytaxes/TownPaysNationConqueredTaxEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Nation.java
Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
Towny/src/main/resources/lang/en-US.yml
Towny/src/main/resources/plugin.yml

- A feature that lets nations set a conquered tax which is paid by the conquered towns, in addition to the normal nation tax.
- Conquered Tax is set using /n set conqueredtax {amount}
- ConqueredTax appears on the nation status screen.
____
```
- API: Added TownPaysNationConqueredTaxEvent
- Thrown before Towny charges a conquered town the nation conquered tax.
- A cancellable event that lets a plugin alter the amount if they choose.
- New Permission Node: towny.command.nation.set.conqueredtax
- Child node of towny.command.nation.set.*
- No change required to the townyperms.yml
- New Command: /nation set conqueredtax {amount}
- Sets a nation's conquered tax, which is paid by the conquered towns.
- New Config Option: nation.default_taxes.default_nation_conquered_tax
- Default: 0
- The …
```

Added Nation Conquered Tax:

---

Towny/src/main/java/com/palmergames/bukkit/towny/hooks/PluginIntegrations.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java

Hopefully the last time I'll have to touch this class in a long while
____
Closes #6767 
____

Make the mob removal task a bit more thread safe on folia

---

Towny/src/main/java/com/palmergames/bukkit/util/Colors.java

Fix legacy conversion for underlined text

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java

fix a possible null datasource npe

---

Towny/src/main/java/com/palmergames/bukkit/util/Colors.java
Towny/src/test/java/com/palmergames/bukkit/towny/test/text/LegacyConversionTests.java

Totally not an excuse to refactors bits of the Colors class, I've probably added those comments next to the legacy fields about 3 times prior over the last year but never pushed it
____

Add legacy conversion unit tests

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java

Include the descriptive error message as part of the exception message instead of logging it, as it can get a bit buried
____

Improve config levels section parsing failure logging

---

Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java

Refactors the SQL source to remove the old connection field. Only one connection is still used at a time since saving & loading both only use 1 thread at a time, but these changes would make such a change require less diff.
____
Closes #5993
____

Refactor sql source to remove use of connection field

---

Towny/src/main/java/com/palmergames/bukkit/util/EntityLists.java

Update some incorrect entity keys

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

This should be the last use of non-methodhandle reflection in areas that get called more than once taken care of
definitely not causing a merge conflict
____

Use method handle for respawn flags

---

Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/MoneyUtil.java

```
- Add alternate debt cap calculation system for Bankruptcy.
- Instead of using the townblock and town costs, it takes the cost of a town's upkeep times a number of days.
- This way it can be assured that a town will always become deleted/reach the debt cap after X number of days.
- Closes #6775.
-  New Config Option: economy.bankruptcy.debt_cap.debt_cap_uses_fixed_days
- When true a town will only be allowed to be bankrupt for a specific number of days, before they will be deleted, requires delete_towns_that_reach_debt_cap to be true.
- New Config Option: economy.bankruptcy.debt_cap.allowed_days
- Default: 7
- When debt_cap_uses_fixed_days is set to true, how many days will a town be allowed to be bankrupt?
```
____
____
Closes #6775.
____
By making this pull request, …

Add an alternate debt cap calculation.

---

Towny/pom.xml
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

The PR that adds the getCause method is currently still open, but I tested and it works perfectly.
Adds some exclusions to our providers to avoid different API versions from leaking in aswell
____

Use paper's open sign event for detecting sign edits

---

Towny/src/main/java/com/palmergames/bukkit/towny/huds/HUDManager.java
Towny/src/main/resources/lang/en-US.yml

Fix scoreboards on Folia by disabling them

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java

Fix negating tax_exempt not working

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DrawSmokeTask.java

Fixes an issue where we were accessing world state async
____

Draw cellborders sync

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DrawSmokeTask.java

No longer creates a bunch of short lived town world pair objects and just gets the string key from them directly
____

Refactor the draw smoke task a bit

---

Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyWorld.java
Towny/src/main/resources/config-migration.json

Fix saving of entity lists so that Entities whose names dont match EntityType Registry keys are not wiped out on save/load.

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java

Fix a typo that was causing an exception

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyMessaging.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/hooks/TownyPlaceholderExpansion.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/comparators/ComparatorCaches.java
Towny/src/main/java/com/palmergames/util/Pair.java

Caches town/nation uuids so that we don't have to look them up via the contents of a formatted component. The previous solution was broken since we were removing underscores when formatting the name, but this new way will be a lot more reliable.
____
Closes #6814
____

Handle top placeholders better

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java

Uses an internal class instead of an API class to improve the testability of Towny via mockbukkit, since mockbukkit uses the paper API but doesn't have support for the Folia scheduling API.
____

User internal class for expanded scheduling check

---

Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java

Make towny handle longer world names on sql.

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyUniverse.java

Fix a typo in TownyUniverse

---

Towny/src/main/java/com/palmergames/bukkit/towny/ChunkNotification.java

Replaces underscores with spaces for plot names/plot group names in chunk notification messages
____
Closes #6829
____

Remove underscores from plot names in chunk notifs

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java

Use better method for determining invitee online status

---

Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java

This won't work on spigot but it makes the javadoc for getUUIDSafely more accurate, since it was previously still causing mojang api calls (method is luckily unused by us)
____

Add getOfflinePlayerIfCached to BukkitTools

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
Towny/src/main/java/com/palmergames/bukkit/towny/permissions/TownyPerms.java

Use invokeExact where possible

---

Towny/pom.xml
Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/resources/plugin.yml

It's been half a year since this was originally marked as deprecated which is long enough for anyone using it to switch off it, this should improve the testability of towny since you no longer need essentials on the test classpath.
____

Remove essentials maven dependency

---

Towny/src/main/java/com/palmergames/bukkit/towny/permissions/TownyPerms.java

Allows nodes with {townname} and {nationname} to be prefixed with a -, and some general cleanup
____

Allow negating nodes with {townname} and {nationname}

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/AbstractRegistryList.java
Towny/src/main/java/com/palmergames/bukkit/util/EntityLists.java

Part 1 of switching from class names to actual names, we'll now be able to use instanceofs for registry lists, this is especially useful for entities since not a lot of tags exist for those.
____

Implement a filter method for registry lists

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownyCommandAddonAPI.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownyUniverse.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/BaseCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/InviteCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/ResidentCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/conversation/SetupConversation.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/DatabaseConfig.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlock.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlockTypeHandler.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyPermission.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Translation.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TranslationLoader.java
Towny/src/main/java/com/palmergames/bukkit/towny/permissions/TownyPermissionSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/permissions/TownyPerms.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/NameUtil.java
Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java

Take care of all the places we weren't using Locale.ROOT with toLowerCase()

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/AbstractRegistryList.java

Fix registry lists' add method not working as expected

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java

Fix teleport refund being done synchronously

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/MinecraftVersion.java

Remove redundant 1.20 check

---

.github/workflows/compile-on-push.yml
.github/workflows/deploy-on-release.yml
.github/workflows/deploy_prerelease.yml
Towny/pom.xml

Skip tests by default

---

Towny/src/main/java/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java

Gets rid of a bit of old code
____

Refactor the regen API to use hashmaps

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/Government.java

adds a getColor() getter method to the government class that returns a awt Color
____
____
mainly making  for use in https://github.com/TownyAdvanced/SiegeWar/pull/875
____

Add getMapColor to Government.

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

Prevent unwanted early returns for if we have 2 cases that can happen at once
____

Fix returning early in the PlayerInteractEvent listeners

---

Towny/src/main/java/com/palmergames/bukkit/config/CommentedConfiguration.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/AbstractRegistryList.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/MinecraftVersion.java
Towny/src/test/java/com/palmergames/bukkit/towny/test/RegistryListTests.java

Fix Item Registry matching incorrectly

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/ChunkNotificationUtil.java

Cancel chunk notification tasks on logout

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
providers/FoliaProvider/src/main/java/com/palmergames/bukkit/towny/scheduling/impl/FoliaTaskScheduler.java

Folia's async scheduler on paper runs independently of the main thread, so it can still execute tasks when the server is shutting down. By cancelling all our active tasks we prevent any unexpected behavior/errors from any stray tasks still running.
____

Cancel scheduled tasks on shutdown

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/hooks/PluginIntegrations.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/SpawnType.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/SpawnUtil.java

- Important methods that should always be ran and which don't throw TownyInitExceptions themselves have been moved out of the try block.
- Most importantly, commands are now always registered which makes it possible to use /ta reload again.
- The list of towny errors has been changed to a set to ensure that an error can only be added once, and that using removeError will always make a subsequent isError for the same error will always be false.
- Checking for third party plugins now always happens because the permission source would otherwise be null. If the main config does not load correctly economy will be enabled as soon as the config successfully loads.
- Improved the error logging when something does not /ta reload correctly, if something isn't reloading correctly it'll now enable …

Make it possible to recover from safemode without restarting

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/Government.java

Remove an outdated comment

---

Towny/src/main/java/com/palmergames/bukkit/towny/event/PlayerChangePlotEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
Towny/src/main/resources/plugin.yml
Towny/src/main/resources/townyperms.yml

Adds a ~~`towny.notify`~~ `towny.receives-plot-notifications` permission that must be present in order for players to be notified when they move between plots.
- ~~Is `towny.notify` the best name for the permission? Is there a more descriptive name?~~
- Renamed to `towny.receives-plot-notifications`
- ~~As-is, servers that upgrade to a version with this change would have to manually add `towny.notify` to `townyperms.yml` to restore notification functionality as it was before the update. I'm not sure of the best way to get around this - as far as I can tell, there is no current precedent for migrating `townyperms.yml`.~~
- Resolved by making the permission default in `plugin.yml`
____
New permission node: `towny.receives-plot-notifications`.
____
#6907
____
By making this pull request, I …

Add towny.receives-plot-notifications permission

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownyAsciiMap.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/PlayerCache.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/SpawnUtil.java

Turned config gets into fields for marginally faster access and removed last location caching
____
____
____

Improve move event listener/player cache a bit

---

Towny/src/main/java/com/palmergames/bukkit/towny/hooks/PluginIntegrations.java

No more warnings when starting a brand new server with just towny, the other warnings will still get logged at the old level.
____

Make the ecowarn line log on the INFO level

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java

Fixes a regression that was introduced in my last PR 
____

Fix exception after creating a new PlayerCache

---

Towny/src/main/resources/plugin.yml

Add contributors to plugin.yml

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/MoneyUtil.java
Towny/src/test/java/com/palmergames/bukkit/towny/test/BonusBlockPurchaseTests.java
Towny/src/test/java/com/palmergames/bukkit/towny/test/RegistryListTests.java

Speed up calculating bonus block costs

---

Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java

Fix Hibernated Residents table being keyed improperly.

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/ResidentCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
Towny/src/main/resources/config-migration.json
Towny/src/main/resources/lang/en-US.yml
Towny/src/main/resources/plugin.yml
Towny/src/main/resources/townyperms.yml

This adds a /res equivalent of the "board" on /t and /n, I have chosen the word "about" in place of board as I think it fits better for a person. I tried to replicate the functionality of the other board commands as best as I can.
____
- `/res set about [clear/none/reset/msg]`
- `towny.command.resident.set.about`
- `/ta set about [username] [clear/none/reset/msg]`
- `towny.command.townyadmin.set.about`
____
#6617 
____ …

Add "about" section to resident status screen

---

Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java

Adds a simple catch so that everything doesn't blow up if it doesn't save properly. Also added a groupID line that's (while unused) still probably nice to have in the long run, and to make it more similar to the sql format.
____

Catch exceptions during plot group saving

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/HelpMenu.java
Towny/src/main/java/com/palmergames/bukkit/util/ChatTools.java
Towny/src/main/resources/lang/en-US.yml

Also: Fix an errant space in ChatTools.
____
____
____

Upgrade HelpMenus to accept Translatables for multilanguage help menus.

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/HelpMenu.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/ResidentCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java

Adds HelpMenus for everything that was not yet using them. 
Removes AlreadyRegisteredException.
Lots of if/else to switch statements.
And more!
____
____
____

Refactor Resident Command

---

Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java

Only warn the log when the world isn't loaded 20 ticks after Towny first tries to load it.

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyUniverse.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Nation.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlock.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyObject.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyWorld.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/TownRuinUtil.java

The issue presented itself when the Resident purge was set to remove-town-only, which resulted in Towns not being removed when their last resident is removed.
Resident#removeTown() was set to ignore the EmptyTownException, which we're now listening to in order to remove the Town when the town becomes empty.
Additionally:
- the DailyTimerTask has had a couple of tests added to make sure we're not parsing over since-removed Towns when factoring conquered-days or deleting 0 plot towns.
- removing a Resident from the datasource can no longer save a non-existent Town which has that Resident as an outlaw or trusted resident.
- removing a Nation can no longer cause a Town that no longer exists in the Universe to save itself.
- the OnPlayerLogin task is no longer saving the default Town when it …

Fix removing Town from residents not being able to delete 1 man towns.

---

Towny/src/main/java/com/palmergames/bukkit/towny/confirmations/ConfirmationHandler.java

Run sync confirmations on the player's region

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyAPI.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownyMessaging.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/InviteCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/ResidentCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyWorldCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/commandobjects/ConfirmCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlockType.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyWorld.java
Towny/src/main/java/com/palmergames/bukkit/towny/permissions/TownyPermissionSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/MetaDataUtil.java

Fixes a bunch of IDE warnings, mainly in the command classes. 
____

Fix a lot of IDE warnings

---

.editorconfig
.gitattributes

Makes git more aware of the line endings towny uses, also effectively disables intellij's import on demand feature to prevent unnecessary diff
____

Add gitattributes file

---

Towny/src/main/java/com/palmergames/bukkit/towny/event/time/dailytaxes/PreTownPaysNationTaxEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownBlock.java

Add missing deprecation annotations

---

.editorconfig

Disable trimming trailing whitespace

---

.github/workflows/compile-on-push.yml
.github/workflows/test.yml

Add testing workflow

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/CombatUtil.java

Uses a method from paper to get the entity that was the cause of the lightning for better protection.
____

Improve trident lightning protection

---

Towny/pom.xml
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

Temporarily downgrade spigot to fix tests

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyAsciiMap.java
Towny/src/main/java/com/palmergames/bukkit/towny/huds/MapHUD.java

Prevents catching unwanted stuff and marginally improves the amount of allocations the method does, an alternative would be using a cached exception but I think this is the best.
____

Remove exception based control flow from map hud

---

Towny/src/main/resources/plugin.yml

Towny no longer has any direct integration with iconomy, and since it also hooks into vault in onLoad we don't need to enable after it anymore
____

Remove iConomy soft dependency

---

Towny/pom.xml
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java

Bump mockbukkit to 3.21.0

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/Translation.java

Add hasTranslation method

---

Towny/pom.xml

Bump adventure platform bukkit to 4.3.1

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TownClaim.java

Fix unclaim all message missing color

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/BaseCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/MinecraftVersion.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/ResidentUtil.java
Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java

player#canSee(Player) wasn't enough for older servers using the PremiumVanish plugin.
on older servers with PremiumVanish enabled we will check for a universally-adopted metadata.
____
____
closes #7022
closes #7003
____

Fix support for Vanished players on servers using PremiumVanish and MC versions older than 1.19.3

---

Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/nation/NationCalculateNationLevelNumberEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/hooks/TownyPlaceholderExpansion.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Nation.java

Changes the lookup of NationLevel from using TownySettings to using the Nation directly, nation#getNationLevel.
Deprecates some methods in Nation and replaces them with methods in TownySettings.
Changes some variable names to make things clearer.
____
```
- New Config Option: global_nation_settings.nation_level_is_determined_by_town_count_instead_of_resident_count
- When set to true, the nation's NationLevel is determined by the
number of towns in the nations, instead of the number of residents.
- API: Added NationCalculateNationLevelNumberEvent, an event thrown when Towny decides what NationLevel number a Nation will have, which ultimately decides which NationLevel the Nation receives. Useful for plugins that want to artifically increase or decrease a Nation's …
```

Make it possible to determine a Nation's NationLevel using the amount of towns instead of amount of residents.

---

Towny/src/main/java/com/palmergames/bukkit/towny/utils/MoneyUtil.java
Towny/src/test/java/com/palmergames/bukkit/towny/test/BonusBlockPurchaseTests.java

Includes added test for a user's configuration which caused this to be noticed.
____
____
____

Fix the purchased block calculation not taking into account a town which has already hit the max price.

---

Towny/src/main/java/com/palmergames/bukkit/towny/utils/MoneyUtil.java

Make all negative purchased blocks prices count as disabled

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/town/TownCalculateTownLevelNumberEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/hooks/TownyPlaceholderExpansion.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/BankAccount.java

Following up on what was done to the nationlevel calculations, this does the same reflow of logic, and additional API event.
____
____
____

Refactor TownLevel calculation to include a new API event and reflow.

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/AbstractRegistryList.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/MinecraftVersion.java
Towny/src/main/java/com/palmergames/bukkit/util/ItemLists.java

Add projectile breaking protection for dripstone & pots

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/ResidentCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java

Make status screen sending respect the async eco setting

---

Towny/src/main/java/com/palmergames/bukkit/util/DrawUtil.java

Fix the draw smoke task being able to load chunks

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/Nation.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyWorld.java

Add equals and hashcodes overrides to Resident, Town, Nation & TownyWorld objects.

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/TownRuinUtil.java
Towny/src/main/resources/lang/en-US.yml

Prevent ruined towns from being bought

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java

Remove two cases of == equality check for residents

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java

Fix outposts being counted wrong in town merge vetting code.

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/NewDayScheduler.java

Re-checking isn't needed on newer versions since the async scheduler from folia's api doesn't have the same issue as the old one
____

Immediately schedule upcoming newday on paper

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java

Fix manually-set town levels not returning the correct TownLevel

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java

Prevent players without plot perms lighting campfires with flame arrows.

---

Towny/src/main/resources/config-migration.json

Fix config migrator file formatting

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java

Fix two nation command tab complete exceptions

---

Towny/src/main/java/com/palmergames/bukkit/util/BlockUtil.java
Towny/src/main/java/com/palmergames/bukkit/util/DrawUtil.java
Towny/src/main/java/com/palmergames/bukkit/util/ItemLists.java

Greatly improves the experience of looking for borders in forests.
____
____
____

Render border particles under leaves.

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/AbstractRegistryList.java
Towny/src/main/java/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java
Towny/src/main/java/com/palmergames/bukkit/util/ItemLists.java

Many attachable blocks are not given the Attachable interface, making that basically useless.
Instead an ItemLists was made up to keep the explodable attachables in check during the ProtectionRegenTasks, which now takes special care to nuke these blocks into Air.
Bonus: Adds ability to add ItemLists to ItemLists.
____
____
Closes #7154
Closes #5689
____

Prevent the drops that spawn from problem blocks which can be duped in explosion regenerations.

---

Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/CellSurface.java

____
```
- New Config Option: claiming.show_claiming_particles
- When false players will not see the particle flood effect when they claim townblocks.
```
____
____

Add claiming particles.

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java

Refactor town join command, which was not able to be run from the console.

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyWorldCommand.java

Switch statements and dropping the static globalWorld.
____
____
____

Refactor the TownyWorldCommand.

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java

Refactor townAddResident method.

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java

Refactor townSet and the subcommands.

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/PlotClaim.java
Towny/src/main/resources/lang/en-US.yml

Refactor the plot claim task to not be a mess.

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java

Update the town kicking method, and decouple the admin version of town kicking.

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/invites/InviteHandler.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/ResidentUtil.java
Towny/src/main/resources/lang/en-US.yml

Updates a lang string to actually be useful when revoking invites off a group of names.
____
____
____

Refactor townAdd method to better handle adding and revoking invites.

---

Towny/pom.xml
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/InviteCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/NationUtil.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/TownUtil.java
Towny/src/test/java/com/palmergames/bukkit/towny/test/PopulationTests.java

Also catches some uses of nations max residents.
Add PopulationTests.java, bump MockBukkit and Spigot.
- Tests would not run because MockBukkit knows about short_grass or w/e its called.
- TownyPlayerListener had a Action test change from being done on the non-existent GRASS changed to DIRT which will hopefully remain named DIRT until forever.
New testing found an error in part of the NationUtil so that's great.
____
____
____ …

Refactor max residents per town code into TownUtil accessed via a new Town method.

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java

Add a wrapper for getting potion names post-1.20.4.

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/CellSurface.java
Towny/src/main/java/com/palmergames/bukkit/util/BlockUtil.java
Towny/src/main/java/com/palmergames/bukkit/util/DrawUtil.java

Fix claiming particles breaking on Folia servers.

---

Towny/pom.xml
Towny/src/main/java/com/palmergames/bukkit/towny/hooks/PluginIntegrations.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyServerListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/CombatUtil.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java
Towny/src/main/java/com/palmergames/bukkit/util/BukkitTools.java
Towny/src/main/resources/plugin.yml

Citizens attaches metadata to its npcs which we can use to check, instead of using it directly
____

Remove explicit citizens dependency

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyUniverse.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/ResidentCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Towny/src/main/java/com/palmergames/bukkit/towny/exceptions/InvalidNameException.java
Towny/src/main/java/com/palmergames/bukkit/util/NameValidation.java
Towny/src/main/resources/lang/en-US.yml

Makes all of the individual tests private, resulting in the classes that needed them instead calling specific Name Validation methods which are built for their object type.
Some inconsistencies were uncovered:
- we're now using the config-blacklisted-names lists more thoroughly, which should result in less shenanigans in titles and boards.
- we're also now making towns/nations names play by more consistent rules, I believe I find some oversights which are now closed.
____
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under …

Overhaul the NameValidation class.

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyTimerHandler.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java

____
Closes #7261, #7221, #7202, #7253
____

Fix mob removal on folia

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/commandobjects/AcceptCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/commandobjects/CancelCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/commandobjects/ConfirmCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/commandobjects/DenyCommand.java

Cleans our commands up a bit since they did not need to extend BukkitCommand, also makes them implement plugin identifiable which makes it easy to see for other plugins that the commands are coming from us
____

Make our custom registered commands identifiable

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownyUniverse.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDataSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java

Realistically every server should have it at 100% by now, with the removal of name history and the timestamp endpoints there's not much that we could do to get it to 100% anymore. According to bstats only ~100 servers don't have it at 100 yet.
____

Remove uuid percentage tracking

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityListener.java

Instead of using an item list that would need updating in the future, an instanceof can do the trick aswell
____

Futureproof falling block checking

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/metadata/CustomDataField.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/metadata/DataFieldIO.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/metadata/ListDataField.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/metadata/MetadataLoader.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/metadata/TownyCDFDeserializer.java

Surprisingly, it works
____
Closes #6979
____

Add list metadata type

---

Towny/src/main/java/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java
Towny/src/main/java/com/palmergames/util/JavaUtil.java

Skips copying the chunks light data using a new method from paper, we only care about the blocks when taking a chunk snapshot here
____

Skip copying light data for our chunk snapshots

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java

Fix mob removal npe when townblock has no town

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/ResidentCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
Towny/src/main/resources/config-migration.json
Towny/src/main/resources/lang/en-US.yml
Towny/src/main/resources/plugin.yml
Towny/src/main/resources/townyperms.yml

Adds a `/res outlawlist {username}` command
____
`towny.command.resident.outlawlist`
____
#7278 
____
- [ x ] I have tested this pull request for defects on a server. 

Add /res outlawlist command

---

Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyPermission.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/TownRuinUtil.java
Towny/src/main/resources/lang/en-US.yml

Make ruined towns slowly open up their plot permissions.

---

Towny/src/main/java/com/palmergames/bukkit/towny/regen/TownyRegenAPI.java

Fix snapshot taking on older versions

---

.github/workflows/compile-on-push.yml
.github/workflows/test.yml

Would be able to see whether tests pass & get a link to the jar without opening a pr
____

Compile & test branches without a pr

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyUniverse.java

Fix the hasWorld causing SQL dbs to not load worlds with capital letters' townblocks.

---

Towny/src/main/java/com/palmergames/bukkit/towny/regen/WorldCoordEntityRemover.java

Fix unclaim entity delete not working on folia

---

Towny/src/main/java/com/palmergames/bukkit/towny/event/damage/TownyDamageEvent.java

Currently it may not work because TownBlock can be null
```
java.lang.NullPointerException: Cannot invoke "com.palmergames.bukkit.towny.object.TownBlock.getTownOrNull()" because "this.townblock" is null
at Towny-0.100.1.0.jar/com.palmergames.bukkit.towny.event.damage.TownyDamageEvent.getTown(TownyDamageEvent.java:56) ~[Towny-0.100.1.0.jar:?]
```
____
____
____

Fix potential NPE in TownyDamageEvent.

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyAPI.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/teleport/CancelledTownySpawnEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/teleport/CancelledTownyTeleportEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyEntityMonitorListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java

Event which is thrown when a player has their towny spawn cancelled via moving, damage, or via the TownyAPI class.
____
____
Closes #7353
____

Add CancelledTownyTeleportEvent

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/CellSurface.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/WorldCoord.java
Towny/src/main/java/com/palmergames/util/Pair.java
Towny/src/test/java/com/palmergames/bukkit/towny/object/WorldCoordTests.java

Don't process claim particles for unloaded chunks

---

Towny/src/main/java/com/palmergames/bukkit/towny/ChunkNotification.java

Stop non-Towny-using worlds showing a ChunkNotification when entered.

---

Towny/src/main/java/com/palmergames/bukkit/towny/event/LoadedMetadataEvent.java

Fix async LoadedMetadataEvent call on folia

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java

Fix npe in town add resident event listener

---

.github/workflows/compile-on-push.yml
.github/workflows/test.yml

On push is enough to make it run
____

Fix workflows running twice

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/TranslationLoader.java
Towny/src/main/java/com/palmergames/util/FileMgmt.java

Make our own getFileName

---

Towny/pom.xml

Should support 1.20.5/6 servers
____

Bump adventure platform bukkit to 4.3.3-SNAPSHOT

---

providers/PaperProvider/src/main/java/com/palmergames/bukkit/towny/scheduling/impl/PaperTaskScheduler.java

Fix scheduling 0 tick delayed task on paper

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDataSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/CancellableTownyEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/DeleteTownEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/PreDeleteTownEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/town/TownPreRuinedEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/TownRuinUtil.java

Expands the API with deletion causes for towns & exposes the sender who caused the deletion
____
Half addresses #7410
____

Expand town delete event with sender & causes

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDataSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/DeleteNationEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/PreDeleteNationEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/DailyTimerTask.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/TownUtil.java

Similarly expand the DeleteNationEvent

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/AbstractRegistryList.java
Towny/src/main/java/com/palmergames/bukkit/util/ItemLists.java

Make addItemList accept any list of the same type

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Transaction.java

Add TransactionEvents thrown by /ta withdraw and deposit commands.

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Resident.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java

NREs found in the AreaSelectonUtil have been prevented from being thrown.
A unused and very very old method in the Towny class has also been deprecated.
As a bonus this fixes a missing ! in one of the AreaSelectionUtil methods for picking out plots not owned by a resident.
____
____
____

Remove more potential NotRegisteredExceptions.

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/Translation.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/TranslationLoader.java
Towny/src/main/resources/lang/en-US.yml

Support partial reference files

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/AbstractRegistryList.java

Missing items in the explicit .add from item lists on older servers would cause an exception due to the config not being fully loaded yet
Closes #7452
____

don't fail on startup due to debug messaging

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java

Fix a bad scheduler call in take over claim code

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/plot/group/PlotGroupAddEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/plot/group/PlotGroupCreatedEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/plot/group/PlotGroupDeletedEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/TownRuinUtil.java

Add plot group creation/deletion events

---

Towny/src/main/java/com/palmergames/bukkit/towny/event/teleport/SuccessfulTownyTeleportEvent.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/SpawnUtil.java

Expose cost in successful teleport event

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/metadata/MetadataLoader.java

Always fire loaded metadata event

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java

Fix untranslated lang key from unwanted biome claiming

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/WorldCoord.java
Towny/src/test/java/com/palmergames/bukkit/towny/object/WorldCoordTests.java

The location was one block too far over for both x and z
____

Fix worldcoord upper corners being in another worldcoord

---

Towny/src/main/java/com/palmergames/bukkit/towny/utils/ResidentUtil.java

There is no reliable way to convert from block type -> item type, so this will have to do.
____
Closes #7575
____

Don't attempt to display non-items in guis

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java

Fix NPE when player without town tab completes /t outpost

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java

Fixes a minor memory leak after the sql dump command is used by shutting down the async saving task right after saving.
____

Shutdown saving task when making an sql dump

---

Towny/src/main/java/com/palmergames/bukkit/towny/utils/SpawnUtil.java

Fix safe spawn checking causing a sync chunk load

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TeleportWarmupTimerTask.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/SpawnUtil.java

Fix pets being abandoned in chunks that unload too fast after the player teleports away.

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/Nation.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java

Re-assign permissions for previous mayor after switch

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java

Limit /plot trust remove suggestions to trusted residents

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java

fix bug that prevents setting `/plot group toggle taxed <on/off>`
____
____
____

Fix error message shown when using /plot group toggle taxed

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java

Refactor OnPlayerLogin task for readability.

---

.github/workflows/compile-on-push.yml
.github/workflows/javadoc-test.yml
.github/workflows/publish-javadoc-on-full-release.yml
.github/workflows/publish_to_glare_repo.yml
.github/workflows/test.yml
Towny/pom.xml
pom.xml
providers/BaseProviders/pom.xml
providers/FoliaProvider/pom.xml
providers/PaperProvider/pom.xml

above spigot-api.
____
____
____

Fix testing broken in 1.21 bump, the main pom.xml requires paper-api

---

Towny/pom.xml
providers/FoliaProvider/pom.xml
providers/PaperProvider/pom.xml

Updates bridger for java 21 support, also fixes two links to paper's repository that 400 when accessed directly
____

Update bridger for java 21 support

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyLoginListener.java
Towny/src/test/java/com/palmergames/bukkit/towny/listeners/LoginListenerTests.java

Make the npc prefix check less strict and more precise

---

.github/workflows/compile-on-push.yml

Update to upload_artifact v4

---

Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/TownyServerAccount.java

Add config option for Closed Economy UUID to support modern Economy plugins
____
New Config Option: 
closed_economy: server_account_uuid
____
____

Add config option for Closed Economy UUID

---

Towny/pom.xml
Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
Towny/src/main/resources/config-migration.json

____
New Config Migration: ",TRIAL_SPAWNER" will be added to the town_mob_removal_ignored_spawn_causes list in the config.
This only works on Paper servers.
____
Closes #7709.
____

Add TRIAL_SPAWNER to default list of reasons Towny won't remove mobs.

---

Towny/src/main/java/com/palmergames/bukkit/towny/utils/CombatUtil.java

Fix an NPE in the isOutlawInTown method

---

Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java

The oldResident variable never had a UUID set, so contains and equals checks would always fail for it
____

Fix for resident rename weirdness

---

Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java

Probably isn't an issue when the server stops and starts.
Doing this as a PR because I'm not sure how much I like parsing every townblock on a player rename.
____
____
____

Fixes an issue where a renamed resident cannot access their trusted plots.

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownyEconomyHandler.java

Checks the existance vault/vaultunlocked classes rather than checking the version, to prevent mistaking other vault implementations for vaultunlocked.
____
Closes #7786
____

Use class existance to determine whether vault is present

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java

Don't log for cancelled pre claim events

---

Towny/src/main/java/com/palmergames/bukkit/towny/Towny.java
Towny/src/main/java/com/palmergames/bukkit/towny/TownyAsciiMap.java

Loads the ascii map class early so that the config reload listener can properly initialize the values from the config
____
Closes #7801
____

Call ascii map static initializer before initial config load

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/HelpMenu.java

Updated the help for `/t` from console to reflect the commands that console can execute:
- Removed help message for `/t` about your own town because console cannot join a town.
- Added help message for `/t reslist`.
____
____
____

Update console town help

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java

This PR fixes a NullPointerException caused when `/t reslist` was run from console with no town as an argument.
____
____
____

Fix error when /t reslist is run from console without a town argument

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyCustomListener.java
Towny/src/main/resources/lang/en-US.yml

Upon nation adding an enemy or a town adding, check over the town's trusted towns and trusted resident and townblocks' trusted residents, and remove towns and players who are trusted.
Also prevent adding plot, town, towntrust actions when the target is an outlaw or enemy.
____
____
Closes #7818
____

Cause outlawing and enemying to remove town/plot trust.

---

Towny/pom.xml
Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/utils/MinecraftVersion.java
Towny/src/main/resources/ChangeLog.txt
Towny/src/test/java/com/palmergames/bukkit/towny/config/BonusBlockPurchaseTests.java
Towny/src/test/java/com/palmergames/bukkit/towny/config/ConfigMigrationTests.java
Towny/src/test/java/com/palmergames/bukkit/towny/config/EntityTypeConversionTests.java
Towny/src/test/java/com/palmergames/bukkit/towny/listeners/LoginListenerTests.java
Towny/src/test/java/com/palmergames/bukkit/towny/object/PopulationTests.java
Towny/src/test/java/com/palmergames/bukkit/towny/object/RegistryListTests.java
Towny/src/test/java/com/palmergames/bukkit/towny/object/WorldCoordTests.java

Update MockBukkit to 4.50.0.

---

Towny/src/main/java/com/palmergames/bukkit/towny/TownySettings.java
Towny/src/main/java/com/palmergames/bukkit/towny/event/town/TownCalculateMaxTownBlocksEvent.java

Adds an event that is fired when the max town size is calculated, allowing plugins to change/override it in a more dynamic manner
____

Add TownCalculateMaxTownBlocksEvent

---

Towny/pom.xml

Updates adventure-platform-bukkit to a version compiled from bloodshot's PR with support for the latest version
____

Update adventure-platform for 1.21.7

---

Towny/src/main/java/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java

Rather than having to instanceof the entity's class against every single class of mob being removed, we can instead do the work up front and use a much faster contains instead.
____

Precompute mob removal classes to entity types

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/HelpMenu.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
Towny/src/main/resources/lang/en-US.yml

This PR makes it easy to rename town and nation ranks in-game. Players in the rank are preserved during the renaming process.
____
/ta townyperms townrank|nationrank renamerank [oldrankname] [newrankname]
____
____

Add renaming Towny ranks

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/TranslationLoader.java

Allows users of plugins using the TranslationLoader system to create their own global.yml, even if the jar does not contain a default one.
Also avoids reading the global.yml from the jar during every startup.
____

Always read global.yml for overrides

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
Towny/src/main/resources/plugin.yml
Towny/src/main/resources/townyperms.yml

Added permission validation for the town allylist command
____
A new permission: towny.command.town.allylist
____
No
____

permission validation for town allylist command was added

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java

Adds tab completions for all toggle commands for plot groups.
____
____
____

Add tab completions for /plot group toggle

---

Towny/src/main/java/com/palmergames/bukkit/towny/regen/PlotBlockData.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/ProtectionRegenTask.java

Logging what was there before allows people to properly restore what was there before using CoreProtect. Also prevents logging of air blocks being "placed", since in that case the block would only need to be logged as removed.
____

Log removed blocks with coreprotect

---

Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java
providers/BaseProviders/src/main/java/com/palmergames/bukkit/towny/scheduling/impl/BukkitScheduledTask.java
providers/BaseProviders/src/main/java/com/palmergames/bukkit/towny/scheduling/impl/BukkitTaskScheduler.java
providers/FoliaProvider/src/main/java/com/palmergames/bukkit/towny/scheduling/impl/FoliaScheduledTask.java
providers/FoliaProvider/src/main/java/com/palmergames/bukkit/towny/scheduling/impl/FoliaTaskScheduler.java
providers/PaperProvider/src/main/java/com/palmergames/bukkit/towny/scheduling/impl/PaperTaskScheduler.java

Replace AtomicReference usages in the task scheduler

---

Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDataSource.java
Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyDatabaseHandler.java
Towny/src/main/java/com/palmergames/bukkit/towny/tasks/TownClaim.java

Fix districts becoming un-unclaimable.

---

Towny/pom.xml

Whenever dependabot tried to update junit, it would always bump both dependencies separately, which causes the tests to fail. By using a property both can be bumped at once, if it's smart enough to figure that out.
____

Use a property for junit versions

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/ResidentCommand.java

Adds a new subcommand to the /res friend list command, which restricts the output of it to only online players.
____
Adds the /resident friend list online subcommand
____

Add /res friend list online subcommand

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/Translation.java

When a language contains a dash instead of an underscore, we try to normalize it. This normalization was done before we got the translations for this language, which caused an NPE.
____

Fix language dash -> underscore normalization NPE

---

Towny/src/main/java/com/palmergames/bukkit/towny/object/metadata/ListDataField.java

This PR adds a new constructor for the ListDataField metadata type for add-on plugins to use, so that they do not require a label.
____
____
____

Add new constructor for ListDataField

---

Towny/src/main/java/com/palmergames/bukkit/towny/command/NationCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/comparators/ComparatorCaches.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/comparators/ComparatorType.java
Towny/src/main/java/com/palmergames/bukkit/towny/object/comparators/TownComparators.java

Rather than being sorted by resident count, this sorts the /t list by forsale comparator by the for sale price of the town, with cheaper towns appearing first.
This PR also introduces comparator type predicates, to filter out lines that aren't relevant to what's being compared.
____

Sort /t list by forsale by for sale price
